import{describe,expect,it}from"vitest";
import{DocumentDomainError,DocumentManifestFactory,DocumentVersion,VerifiedEditorContentFactory}from"../../packages/core/document/src/public.js";
import{correlationId,idempotencyKey,sha256,stableCode,utcInstant,uuid,version}from"../../packages/shared-kernel/src/public.js";
const at=utcInstant("2026-08-22T01:00:00Z"),author=uuid("21000000-0000-4000-8000-000000000001"),contentHash=sha256("a".repeat(64)),manifestHash=sha256("b".repeat(64));
const verified=()=>new VerifiedEditorContentFactory({validateCanonicalizeAndHash:async()=>({content:{schemaId:stableCode("EDITOR.DOC.V1"),schemaVersion:1,data:{type:"doc",nodes:[]}},checksum:contentHash,validationEvidenceId:uuid("22000000-0000-4000-8000-000000000001")})}).create({type:"doc"});
const command=(expected:number,actorKind:"INTERNAL"|"SYSTEM"="INTERNAL")=>({actor:{userId:author,actorKind,at},expectedVersion:version(expected),eventId:uuid(`23000000-0000-4000-8000-${String(expected+1).padStart(12,"0")}`),correlationId:correlationId("m05:doc"),idempotencyKey:idempotencyKey(`m05:doc:${expected}`)});
const draft=async()=>DocumentVersion.draft({documentVersionId:uuid("24000000-0000-4000-8000-000000000001"),documentId:uuid("25000000-0000-4000-8000-000000000001"),versionNo:1,securityLevel:"L2",templateSource:"FREE_FORM",authorUserId:author,creationReason:stableCode("DOCUMENT.CREATE"),verifiedContent:await verified()});
const manifest=async()=>new DocumentManifestFactory({build:async input=>({...input,checksum:manifestHash,evidenceId:uuid("26000000-0000-4000-8000-000000000001")})}).create({manifestSchemaId:stableCode("DOCUMENT.MANIFEST.V1"),manifestSchemaVersion:1,contentChecksum:contentHash,attachments:[{attachmentId:uuid("27000000-0000-4000-8000-000000000001"),sha256:sha256("c".repeat(64)),mimeType:"application/pdf",sizeBytes:12,securityLevel:"L2"}],effectiveSecurityLevel:"L2",rendererId:stableCode("RENDERER.PDF"),rendererVersion:stableCode("V1")});
describe("SM-DOCUMENT-V1",()=>{
it("requires trusted canonical content and rejects stale edits",async()=>{const doc=await draft(),next=await verified();expect(()=>doc.edit(command(1),next)).toThrowError(/conflict/i);expect(()=>DocumentVersion.draft({...doc.snapshot(),verifiedContent:{snapshot:()=>({})} as never} as never)).toThrowError(DocumentDomainError);});
it("seals the canonical attachment/template/security manifest and never edits it",async()=>{const doc=await draft(),next=await verified();const sealed=doc.seal(command(0),await manifest()).snapshot;expect(sealed).toMatchObject({state:"REVIEW_READY",sealedSnapshotChecksum:manifestHash,sealedManifest:{attachments:[{securityLevel:"L2"}]}});expect(()=>doc.edit(command(1),next)).toThrowError(/Expected DRAFT/i);});
it("supersedes only state/link while preserving approved content and manifest",async()=>{const doc=await draft();doc.seal(command(0),await manifest());doc.submit(command(1),uuid("28000000-0000-4000-8000-000000000001"));doc.applyApprovalOutcome(command(2,"SYSTEM"),"APPROVED");const before=doc.snapshot();doc.supersede(command(3),{documentVersionId:uuid("24000000-0000-4000-8000-000000000002"),documentId:before.documentId,versionNo:2,priorVersionId:before.documentVersionId});const after=doc.snapshot();expect(after).toMatchObject({state:"SUPERSEDED",content:before.content,contentChecksum:before.contentChecksum,sealedSnapshotChecksum:before.sealedSnapshotChecksum,sealedManifest:before.sealedManifest,authorUserId:before.authorUserId,securityLevel:before.securityLevel});});
it("creates a strictly newer same-root revision after rejection",async()=>{const doc=await draft();doc.seal(command(0),await manifest());doc.submit(command(1),uuid("28000000-0000-4000-8000-000000000001"));doc.applyApprovalOutcome(command(2,"SYSTEM"),"REJECTED");const next=DocumentVersion.revision({previous:doc.snapshot(),documentVersionId:uuid("24000000-0000-4000-8000-000000000003"),authorUserId:author,creationReason:stableCode("DOCUMENT.REWORK"),verifiedContent:await verified()}).snapshot();expect(next).toMatchObject({documentId:doc.snapshot().documentId,versionNo:2,priorVersionId:doc.snapshot().documentVersionId,state:"DRAFT"});});
});
