import { describe, expect, it, vi } from "vitest";
import { AuthorizationService, TrustedActorContextFactory, TrustedResourceContextFactory } from "../../packages/core/authorization/src/public.js";
import { Attachment, TrustedDeliveryAuthorization } from "../../packages/core/file/src/public.js";
import { StorageContractError, SupabasePrivateStorageAdapter } from "../../packages/infrastructure/supabase-storage/src/public.js";
import { correlationId, idempotencyKey, sha256, stableCode, utcInstant, uuid, version } from "../../packages/shared-kernel/src/public.js";

const now=utcInstant("2026-08-22T03:00:00Z"),owner=uuid("51000000-0000-4000-8000-000000000001"),hash=sha256("4".repeat(64));
const documentVersionId=uuid("57000000-0000-4000-8000-000000000001");
const available=()=>{const a=Attachment.createIntent({attachmentId:uuid("52000000-0000-4000-8000-000000000001"),storageProvider:"SUPABASE_STORAGE",storageKey:"private/52/file.pdf",bucket:"documents-private",declaredMimeType:"application/pdf",declaredSizeBytes:4,expectedSha256:hash,securityLevel:"L2",createdBy:owner,createdAt:now,intentExpiresAt:utcInstant("2026-08-22T03:05:00Z")});const c=(v:number,k:"INTERNAL"|"SYSTEM")=>({actorUserId:owner,actorKind:k,at:utcInstant("2026-08-22T03:01:00Z"),expectedVersion:version(v),eventId:uuid(`53000000-0000-4000-8000-${String(v+1).padStart(12,"0")}`),correlationId:correlationId("m05:storage"),idempotencyKey:idempotencyKey(`m05:storage:${v}`)});a.uploadVerified(c(0,"SYSTEM"),{intentOwnerUserId:owner,mimeType:"application/pdf",sizeBytes:4,sha256:hash,headEvidenceId:uuid("58000000-0000-4000-8000-000000000001")});a.beginScan(c(1,"SYSTEM"));a.scanCompleted(c(2,"SYSTEM"),{clean:true,detectedMimeType:"application/pdf",scanEvidenceId:uuid("54000000-0000-4000-8000-000000000001"),scannerVersion:stableCode("SCANNER.V1")});return a.snapshot();};

async function trustedAuthorization(file=available(),options:{adminSystem?:boolean;securityEntitlements?:readonly ReturnType<typeof stableCode>[]}={}){
  const action=stableCode("technical_document.content.download"),evidenceId=uuid("59000000-0000-4000-8000-000000000001"),grantId=uuid("59000000-0000-4000-8000-000000000002");
  const assignment={assignmentId:uuid("59000000-0000-4000-8000-000000000003"),stableCode:action,validFrom:utcInstant("2026-01-01T00:00:00Z"),evidenceId};
  const adminRole={...assignment,assignmentId:uuid("59000000-0000-4000-8000-000000000005"),stableCode:stableCode("ADMIN_SYSTEM")};
  const identity={userId:owner,authSubject:"subject",accountKind:"INTERNAL" as const,accountStatus:"ACTIVE" as const,accountValidFrom:utcInstant("2026-01-01T00:00:00Z"),accountVersion:version(1),organizations:[],departments:[],positions:[],roles:options.adminSystem?[adminRole]:[],permissions:[assignment],vendorMemberships:[],actingAuthorities:[],evidenceIds:[evidenceId]};
  const grant={grantId,scopeKind:"DOCUMENT_VERSION" as const,targetId:documentVersionId,actionSetId:stableCode("DOCUMENT_SOURCE_READ"),actionSetVersion:version(1),actions:[action],validFrom:utcInstant("2026-01-01T00:00:00Z"),evidenceId};
  const actor=await new TrustedActorContextFactory({verify:async()=>({authSubject:"subject",sessionId:"session",assuranceLevel:"AAL2" as const,expiresAt:utcInstant("2026-08-23T00:00:00Z")})},{load:async()=>({identity,scopeGrants:[grant],securityEntitlements:options.securityEntitlements??[]})},{now:()=>now}).create("token",correlationId("m05:auth"));
  const securityLevel=file.securityLevel==="L3"?"SEC_L3_CONFIDENTIAL" as const:file.securityLevel==="L4"?"SEC_L4_CORE_SECRET" as const:"SEC_L2_INTERNAL" as const;
  const resource=await new TrustedResourceContextFactory({load:async()=>({resourceType:stableCode("ATTACHMENT_SOURCE"),resourceId:file.attachmentId,documentVersionId,ownerUserId:owner,securityLevel,workflowAllows:true,securityAllows:true,explicitDeny:false})}).load({resourceType:stableCode("ATTACHMENT_SOURCE"),resourceId:file.attachmentId},now);
  if(!resource)throw new Error("resource missing");const decisionId=uuid("59000000-0000-4000-8000-000000000004");return{authorization:TrustedDeliveryAuthorization.evaluate(new AuthorizationService(),actor,resource,file,decisionId),decisionId};
}

describe("private storage contract",()=>{
  it("rejects forged authorization before provider delivery",async()=>{const signed=vi.fn(),broker=vi.fn();const adapter=new SupabasePrivateStorageAdapter({createSignedUploadToken:async()=>"upload",createSignedDownloadUrl:signed,head:async()=>({mimeType:"application/pdf",sizeBytes:4,sha256:hash})},["documents-private"],()=>now,{audited:async(_i,op)=>op()},{issue:broker});await expect(adapter.createAuthorizedDelivery({attachment:available(),authorization:{decision:{allowed:true}} as never,requestedTtlSeconds:30})).rejects.toThrow();expect(signed).not.toHaveBeenCalled();expect(broker).not.toHaveBeenCalled();});
  it("binds the trusted decision id identically to audit and broker",async()=>{const file=available(),{authorization,decisionId}=await trustedAuthorization(file),audited=vi.fn(async(_i,op:()=>Promise<unknown>)=>op()),issued=vi.fn(async()=>({redemptionEndpoint:"/broker",oneTimeBrokerToken:"opaque"}));const adapter=new SupabasePrivateStorageAdapter({createSignedUploadToken:async()=>"upload",createSignedDownloadUrl:async()=>"never",head:async()=>({mimeType:"application/pdf",sizeBytes:4,sha256:hash})},["documents-private"],()=>now,{audited},{issue:issued});await adapter.createAuthorizedDelivery({attachment:file,authorization,requestedTtlSeconds:30});expect(audited.mock.calls[0]?.[0]).toMatchObject({decisionId});expect(issued.mock.calls[0]?.[0]).toMatchObject({authorizationDecisionId:decisionId,reauthorizeOnRedemption:true});});
  it("denies Admin-System alone but honors an explicit L3 source entitlement",async()=>{const l3={...available(),securityLevel:"L3" as const};const denied=await trustedAuthorization(l3,{adminSystem:true});expect(denied.authorization.decision).toMatchObject({allowed:false,reasonCode:"AUTHZ_SYSTEM_ADMIN_SOURCE_DENIED"});const allowed=await trustedAuthorization(l3,{adminSystem:true,securityEntitlements:[stableCode("ENTITLEMENT_L3_SOURCE_READ")]});expect(allowed.authorization.decision).toMatchObject({allowed:true,reasonCode:"FILE_DELIVERY_ALLOWED"});});
  it("requires server private key and caps upload grant TTL",async()=>{const adapter=new SupabasePrivateStorageAdapter({createSignedUploadToken:async()=>"upload",createSignedDownloadUrl:async()=>"never",head:async()=>({mimeType:"application/pdf",sizeBytes:4,sha256:hash})},["documents-private"],()=>now,{audited:async(_i,op)=>op()},{issue:async()=>({redemptionEndpoint:"/broker",oneTimeBrokerToken:"opaque"})});await expect(adapter.createUploadGrant({intentId:uuid("56000000-0000-4000-8000-000000000001"),attachmentId:available().attachmentId,documentVersionId,ownerUserId:owner,bucket:"public",storageKey:"x",mimeType:"application/pdf",sizeBytes:4,sha256:hash,expiresAt:utcInstant("2026-08-22T03:10:00Z")})).rejects.toBeInstanceOf(StorageContractError);});
});
