import type { CorrelationId, IdempotencyKey, Money, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import { nextVersion } from "@youone/shared-kernel/public";

export const RND_RECORD_EVENT_IDS = Object.freeze({ REGISTER: "EVT-RND-REGISTER", LINK_PROJECT: "EVT-RND-LINK-PROJECT", ADD_BUDGET_VERSION: "EVT-RND-ADD-BUDGET-VERSION", RECORD_EXPENDITURE: "EVT-RND-RECORD-EXPENDITURE", ADD_EVIDENCE: "EVT-RND-ADD-EVIDENCE", REGISTER_DEADLINE: "EVT-RND-REGISTER-DEADLINE" } as const);
export type RndRecordEventId = (typeof RND_RECORD_EVENT_IDS)[keyof typeof RND_RECORD_EVENT_IDS];
export interface RndActorSnapshot { readonly actorKind: "INTERNAL" | "HEADQUARTERS" | "VENDOR" | "SYSTEM"; readonly userId?: Uuid; readonly active: boolean; readonly authorities: readonly StableCode[] }
export interface RndCommand { readonly actor: RndActorSnapshot; readonly expectedVersion: Version; readonly at: UtcInstant; readonly eventId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }
export interface RndProgramSnapshot { readonly rndProgramId: Uuid; readonly programCode: string; readonly title: string; readonly agreementId: string; readonly managingAgency: string; readonly fundingAgency?: string; readonly agreementFrom: string; readonly agreementTo: string; readonly currency: string; readonly registeredByUserId: Uuid; readonly projectIds: readonly Uuid[]; readonly currentBudgetVersionId?: Uuid; readonly currentBudgetVersionNo?: number; readonly totalBudgetAmount: string; readonly totalExpenditureAmount: string; readonly expenditureCount: number; readonly evidenceCount: number; readonly deadlineCount: number; readonly version: Version; readonly createdAt: UtcInstant; readonly updatedAt: UtcInstant }
export interface RndProjectLinkSnapshot { readonly rndProjectLinkId: Uuid; readonly rndProgramId: Uuid; readonly projectId: Uuid; readonly linkedByUserId: Uuid; readonly linkedAt: UtcInstant }
export interface BudgetLineSnapshot { readonly budgetLineId: Uuid; readonly categoryCode: StableCode; readonly categoryLabel: string; readonly allocatedAmount: Money }
export interface BudgetVersionSnapshot { readonly budgetVersionId: Uuid; readonly rndProgramId: Uuid; readonly versionNo: number; readonly previousBudgetVersionId?: Uuid; readonly totalBudget: Money; readonly lines: readonly BudgetLineSnapshot[]; readonly reason: string; readonly checksum: Sha256; readonly sealedByUserId: Uuid; readonly sealedAt: UtcInstant }
export type ExpenditureTypedLink = { readonly kind: "PROJECT"; readonly projectId: Uuid } | { readonly kind: "CONTRACT_VERSION"; readonly contractId: Uuid; readonly contractVersionId: Uuid } | { readonly kind: "PURCHASE_RESOLUTION"; readonly purchaseRequestId: Uuid; readonly purchaseResolutionId: Uuid };
export interface ExpenditureSnapshot { readonly expenditureId: Uuid; readonly rndProgramId: Uuid; readonly budgetVersionId: Uuid; readonly budgetLineId: Uuid; readonly supplierId?: Uuid; readonly counterpartyName: string; readonly spentOn: string; readonly amount: Money; readonly purpose: string; readonly typedLinks: readonly ExpenditureTypedLink[]; readonly evidenceDueAt?: UtcInstant; readonly recordedByUserId: Uuid; readonly recordedAt: UtcInstant; readonly paymentInstructionCreated: false; readonly accountingJournalCreated: false; readonly rcmsWorkflowCloned: false }
export type RndEvidenceSubject = { readonly kind: "EXPENDITURE"; readonly expenditureId: Uuid } | { readonly kind: "REPORT_DEADLINE"; readonly reportDeadlineId: Uuid } | { readonly kind: "BUDGET_VERSION"; readonly budgetVersionId: Uuid };
export interface RndEvidenceSnapshot { readonly evidenceId: Uuid; readonly rndProgramId: Uuid; readonly subject: RndEvidenceSubject; readonly evidenceTypeId: StableCode; readonly attachmentId: Uuid; readonly attachmentChecksum: Sha256; readonly recordedByUserId: Uuid; readonly recordedAt: UtcInstant }
export interface ReportDeadlineSnapshot { readonly reportDeadlineId: Uuid; readonly rndProgramId: Uuid; readonly deadlineType: "REPORT" | "EVALUATION" | "SETTLEMENT" | "OTHER"; readonly title: string; readonly dueAt: UtcInstant; readonly evidenceRequired: boolean; readonly registeredByUserId: Uuid; readonly registeredAt: UtcInstant }
export interface RndRecordEvent { readonly eventId: Uuid; readonly eventType: StableCode; readonly aggregateId: Uuid; readonly aggregateVersion: Version; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey; readonly payload: Readonly<Record<string, string | number | boolean | null>> }
export interface RndAuditObligation { readonly eventType: StableCode; readonly actor: RndActorSnapshot; readonly aggregateId: Uuid; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly evidenceIds: readonly Uuid[] }
export interface RndMutation { readonly expectedVersion: Version; readonly snapshot: RndProgramSnapshot; readonly event: RndRecordEvent; readonly audit: RndAuditObligation; readonly immutableProjectLink?: RndProjectLinkSnapshot; readonly immutableBudgetVersion?: BudgetVersionSnapshot; readonly immutableExpenditure?: ExpenditureSnapshot; readonly immutableEvidence?: RndEvidenceSnapshot; readonly immutableDeadline?: ReportDeadlineSnapshot }
export class RndDomainError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "RndDomainError"; } }
const fail = (code: string, message: string): never => { throw new RndDomainError(code as StableCode, message); };
const immutable = <T>(value: T): T => Object.freeze(structuredClone(value)); const clone = <T>(value: T): T => structuredClone(value);
const DECIMAL = /^(?:0|[1-9][0-9]*)(?:\.[0-9]{1,6})?$/; const CURRENCY = /^[A-Z]{3}$/;
function requireText(value: string, code: string): void { if (!value.trim()) fail(code, "A non-empty value is required."); }
function amount(value: string, code: string, allowZero = false): bigint { if (!DECIMAL.test(value)) fail(code, "A non-negative decimal string with at most six places is required."); const [whole = "0", fraction = ""] = value.split("."); const scaled = BigInt(whole) * 1_000_000n + BigInt(fraction.padEnd(6, "0")); if (!allowZero && scaled <= 0n) fail(code, "Amount must be greater than zero."); return scaled; }
function amountString(value: bigint): string { const whole = value / 1_000_000n; const fraction = String(value % 1_000_000n).padStart(6, "0").replace(/0+$/, ""); return fraction ? `${whole}.${fraction}` : String(whole); }
function validateMoney(value: Money, currency: string, code: string): void { amount(value.amount, code); if (!CURRENCY.test(value.currency) || value.currency !== currency) fail(`${code}_CURRENCY`, "Amount must use the R&D Program ISO currency."); }
function internal(actor: RndActorSnapshot, authority: string): Uuid { const userId = actor.userId; if (actor.actorKind !== "INTERNAL" || !actor.active || !userId || !actor.authorities.includes(authority as StableCode)) fail("RND_INTERNAL_AUTHORITY_REQUIRED", `Active internal ${authority} authority is required; Vendor and Headquarters mutation are denied.`); return userId as Uuid; }
function unique<T>(values: readonly T[], code: string): void { if (new Set(values.map(String)).size !== values.length) fail(code, "Duplicate typed links are forbidden."); }
function validateDate(value: string, code: string): void { if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(`${value}T00:00:00Z`))) fail(code, "ISO date is required."); }

export class RndProgram {
  private constructor(private value: RndProgramSnapshot) {}
  public static register(input: Omit<RndProgramSnapshot, "projectIds" | "currentBudgetVersionId" | "currentBudgetVersionNo" | "totalBudgetAmount" | "totalExpenditureAmount" | "expenditureCount" | "evidenceCount" | "deadlineCount" | "version" | "createdAt" | "updatedAt">, command: Omit<RndCommand, "expectedVersion">): RndMutation { const userId = internal(command.actor, "rnd.program.register"); if (userId !== input.registeredByUserId) fail("RND_REGISTRAR_MISMATCH", "Trusted registrar mismatch."); requireText(input.programCode, "RND_PROGRAM_CODE_REQUIRED"); requireText(input.title, "RND_TITLE_REQUIRED"); requireText(input.agreementId, "RND_AGREEMENT_REQUIRED"); requireText(input.managingAgency, "RND_AGENCY_REQUIRED"); validateDate(input.agreementFrom, "RND_AGREEMENT_FROM_INVALID"); validateDate(input.agreementTo, "RND_AGREEMENT_TO_INVALID"); if (input.agreementFrom > input.agreementTo || !CURRENCY.test(input.currency)) fail("RND_AGREEMENT_PERIOD_OR_CURRENCY_INVALID", "Agreement period and ISO currency are required."); const snapshot: RndProgramSnapshot = { ...clone(input), projectIds: [], totalBudgetAmount: "0", totalExpenditureAmount: "0", expenditureCount: 0, evidenceCount: 0, deadlineCount: 0, version: 1 as Version, createdAt: command.at, updatedAt: command.at }; return RndProgram.mutation(snapshot, command, 0 as Version, RND_RECORD_EVENT_IDS.REGISTER, []); }
  public static restore(snapshot: RndProgramSnapshot): RndProgram { return new RndProgram(clone(snapshot)); }
  public snapshot(): RndProgramSnapshot { return clone(this.value); }
  public linkProject(command: RndCommand, input: { readonly rndProjectLinkId: Uuid; readonly projectId: Uuid }): RndMutation { this.guard(command); const userId = internal(command.actor, "rnd.program.manage"); if (this.value.projectIds.includes(input.projectId)) fail("RND_PROJECT_LINK_DUPLICATE", "Project/R&D N:M link already exists."); const link: RndProjectLinkSnapshot = immutable({ ...input, rndProgramId: this.value.rndProgramId, linkedByUserId: userId, linkedAt: command.at }); this.value = { ...this.value, projectIds: [...this.value.projectIds, input.projectId] }; return this.record(command, RND_RECORD_EVENT_IDS.LINK_PROJECT, [], { immutableProjectLink: link }); }
  public addBudgetVersion(command: RndCommand, input: Omit<BudgetVersionSnapshot, "rndProgramId" | "versionNo" | "previousBudgetVersionId" | "sealedByUserId" | "sealedAt">): RndMutation { this.guard(command); const userId = internal(command.actor, "rnd.budget.manage"); requireText(input.reason, "RND_BUDGET_REASON_REQUIRED"); if (input.lines.length === 0) fail("RND_BUDGET_LINE_REQUIRED", "Budget requires normalized category lines."); unique(input.lines.map((line) => line.budgetLineId), "RND_BUDGET_LINE_DUPLICATE"); unique(input.lines.map((line) => line.categoryCode), "RND_BUDGET_CATEGORY_DUPLICATE"); for (const line of input.lines) { requireText(line.categoryLabel, "RND_BUDGET_CATEGORY_LABEL_REQUIRED"); validateMoney(line.allocatedAmount, this.value.currency, "RND_BUDGET_LINE_AMOUNT_INVALID"); } validateMoney(input.totalBudget, this.value.currency, "RND_BUDGET_TOTAL_INVALID"); if (amount(input.totalBudget.amount, "RND_BUDGET_TOTAL_INVALID") !== input.lines.reduce((sum, line) => sum + amount(line.allocatedAmount.amount, "RND_BUDGET_LINE_AMOUNT_INVALID"), 0n)) fail("RND_BUDGET_TOTAL_MISMATCH", "Budget total must equal exact line allocations."); const versionNo = (this.value.currentBudgetVersionNo ?? 0) + 1; const budget: BudgetVersionSnapshot = immutable({ ...clone(input), rndProgramId: this.value.rndProgramId, versionNo, ...(this.value.currentBudgetVersionId ? { previousBudgetVersionId: this.value.currentBudgetVersionId } : {}), sealedByUserId: userId, sealedAt: command.at }); this.value = { ...this.value, currentBudgetVersionId: budget.budgetVersionId, currentBudgetVersionNo: budget.versionNo, totalBudgetAmount: budget.totalBudget.amount }; return this.record(command, RND_RECORD_EVENT_IDS.ADD_BUDGET_VERSION, [], { immutableBudgetVersion: budget }); }
  public recordExpenditure(command: RndCommand, input: Omit<ExpenditureSnapshot, "rndProgramId" | "recordedByUserId" | "recordedAt" | "paymentInstructionCreated" | "accountingJournalCreated" | "rcmsWorkflowCloned">): RndMutation { this.guard(command); const userId = internal(command.actor, "rnd.expenditure.record"); if (!this.value.currentBudgetVersionId || input.budgetVersionId !== this.value.currentBudgetVersionId) fail("RND_CURRENT_BUDGET_VERSION_REQUIRED", "Expenditure must reference the exact current immutable BudgetVersion."); requireText(input.counterpartyName, "RND_COUNTERPARTY_REQUIRED"); requireText(input.purpose, "RND_EXPENDITURE_PURPOSE_REQUIRED"); validateDate(input.spentOn, "RND_SPENT_ON_INVALID"); validateMoney(input.amount, this.value.currency, "RND_EXPENDITURE_AMOUNT_INVALID"); unique(input.typedLinks.map((link) => JSON.stringify(link)), "RND_EXPENDITURE_LINK_DUPLICATE"); for (const link of input.typedLinks) if (link.kind === "PROJECT" && !this.value.projectIds.includes(link.projectId)) fail("RND_EXPENDITURE_PROJECT_SCOPE_INVALID", "Expenditure Project link must belong to the Program N:M set."); const expenditure: ExpenditureSnapshot = immutable({ ...clone(input), rndProgramId: this.value.rndProgramId, recordedByUserId: userId, recordedAt: command.at, paymentInstructionCreated: false, accountingJournalCreated: false, rcmsWorkflowCloned: false }); this.value = { ...this.value, totalExpenditureAmount: amountString(amount(this.value.totalExpenditureAmount, "RND_TOTAL_EXPENDITURE_INVALID", true) + amount(input.amount.amount, "RND_EXPENDITURE_AMOUNT_INVALID")), expenditureCount: this.value.expenditureCount + 1 }; return this.record(command, RND_RECORD_EVENT_IDS.RECORD_EXPENDITURE, [], { immutableExpenditure: expenditure }); }
  public addEvidence(command: RndCommand, input: Omit<RndEvidenceSnapshot, "rndProgramId" | "recordedByUserId" | "recordedAt">): RndMutation { this.guard(command); const userId = internal(command.actor, "rnd.evidence.record"); const record: RndEvidenceSnapshot = immutable({ ...clone(input), rndProgramId: this.value.rndProgramId, recordedByUserId: userId, recordedAt: command.at }); this.value = { ...this.value, evidenceCount: this.value.evidenceCount + 1 }; return this.record(command, RND_RECORD_EVENT_IDS.ADD_EVIDENCE, [input.attachmentId], { immutableEvidence: record }); }
  public registerDeadline(command: RndCommand, input: Omit<ReportDeadlineSnapshot, "rndProgramId" | "registeredByUserId" | "registeredAt">): RndMutation { this.guard(command); const userId = internal(command.actor, "rnd.deadline.manage"); requireText(input.title, "RND_DEADLINE_TITLE_REQUIRED"); const deadline: ReportDeadlineSnapshot = immutable({ ...clone(input), rndProgramId: this.value.rndProgramId, registeredByUserId: userId, registeredAt: command.at }); this.value = { ...this.value, deadlineCount: this.value.deadlineCount + 1 }; return this.record(command, RND_RECORD_EVENT_IDS.REGISTER_DEADLINE, [], { immutableDeadline: deadline }); }
  private guard(command: RndCommand): void { if (command.expectedVersion !== this.value.version) fail("RND_STALE_VERSION", "Optimistic version mismatch."); }
  private record(command: RndCommand, eventType: RndRecordEventId, evidenceIds: readonly Uuid[], append: Partial<Pick<RndMutation, "immutableProjectLink" | "immutableBudgetVersion" | "immutableExpenditure" | "immutableEvidence" | "immutableDeadline">>): RndMutation { const expected = this.value.version; this.value = { ...this.value, version: nextVersion(this.value.version), updatedAt: command.at }; return { ...RndProgram.mutation(this.value, command, expected, eventType, evidenceIds), ...append }; }
  private static mutation(snapshot: RndProgramSnapshot, command: Omit<RndCommand, "expectedVersion">, expectedVersion: Version, eventType: RndRecordEventId, evidenceIds: readonly Uuid[]): RndMutation { return { expectedVersion, snapshot: immutable(snapshot), event: { eventId: command.eventId, eventType: eventType as StableCode, aggregateId: snapshot.rndProgramId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, payload: { recordVersion: snapshot.version, lifecycleStateDefined: false, paymentInstructionCreated: false, accountingJournalCreated: false, rcmsWorkflowCloned: false } }, audit: { eventType: eventType as StableCode, actor: clone(command.actor), aggregateId: snapshot.rndProgramId, occurredAt: command.at, correlationId: command.correlationId, evidenceIds: [...evidenceIds] } }; }
}

export const RND_LIFECYCLE_BLOCKED = Object.freeze({ availability: "BLOCKED" as const, reason: "OD-030-RND-STATE-MACHINE" as const, message: "RndProgram lifecycle state/event/close/reopen is undefined and fails closed." });
