import type { CorrelationId, IdempotencyKey, JsonValue, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";

export const DOCUMENT_MACHINE_ID = "SM-DOCUMENT-V1" as const;
export type SecurityLevel = "L1"|"L2"|"L3"|"L4";
export type DocumentVersionState = "DRAFT"|"REVIEW_READY"|"APPROVAL_PENDING"|"APPROVED"|"REJECTED"|"RECALLED"|"SUPERSEDED"|"RETENTION_HOLD"|"DISPOSAL_REQUESTED"|"QUARANTINED"|"DISPOSED";
export interface EditorContent { readonly schemaId: StableCode; readonly schemaVersion: number; readonly data: JsonValue }
export interface VerifiedEditorContentSnapshot { readonly content:EditorContent; readonly checksum:Sha256; readonly validationEvidenceId:Uuid }
const trustedContent = new WeakSet<object>();
const contentFactoryToken=Symbol("document-content-factory");
export class VerifiedEditorContent { constructor(private readonly value:VerifiedEditorContentSnapshot,token:symbol){if(token!==contentFactoryToken)fail("DOCUMENT_CONTENT_UNTRUSTED","Trusted content factory required.");trustedContent.add(this);} snapshot(){if(!trustedContent.has(this))fail("DOCUMENT_CONTENT_UNTRUSTED","Trusted content validation is required.");return clone(this.value);} }
export interface EditorContentCanonicalizerPort{validateCanonicalizeAndHash(raw:unknown):Promise<VerifiedEditorContentSnapshot>}
export class VerifiedEditorContentFactory{constructor(private readonly canonicalizer:EditorContentCanonicalizerPort){}async create(raw:unknown){const value=await this.canonicalizer.validateCanonicalizeAndHash(raw);if(value.content.schemaVersion<1)fail("DOCUMENT_SCHEMA_VERSION_INVALID","Schema version must be positive.");return new VerifiedEditorContent(clone(value),contentFactoryToken);}}
function contentSnapshot(value:VerifiedEditorContent){if(!trustedContent.has(value))fail("DOCUMENT_CONTENT_UNTRUSTED","Trusted content validation is required.");return value.snapshot();}
export interface TemplateVersionSnapshot { readonly templateVersionId: Uuid; readonly templateId: Uuid; readonly versionNo: number; readonly checksum: Sha256; readonly sealedAt: UtcInstant }
export interface DocumentAttachmentManifestItem {readonly attachmentId:Uuid;readonly sha256:Sha256;readonly mimeType:string;readonly sizeBytes:number;readonly securityLevel:SecurityLevel}
export interface SealedDocumentManifest {readonly manifestSchemaId:StableCode;readonly manifestSchemaVersion:number;readonly contentChecksum:Sha256;readonly templateVersionId?:Uuid;readonly templateChecksum?:Sha256;readonly attachments:readonly DocumentAttachmentManifestItem[];readonly effectiveSecurityLevel:SecurityLevel;readonly rendererId:StableCode;readonly rendererVersion:StableCode;readonly checksum:Sha256;readonly evidenceId:Uuid}
declare const manifestBrand:unique symbol;export type TrustedDocumentManifest=SealedDocumentManifest&Readonly<{[manifestBrand]:true}>;const trustedManifests=new WeakSet<object>();
export interface DocumentManifestBuilder{build(input:Omit<SealedDocumentManifest,"checksum"|"evidenceId">):Promise<SealedDocumentManifest>}
export class DocumentManifestFactory{constructor(private readonly builder:DocumentManifestBuilder){}async create(input:Omit<SealedDocumentManifest,"checksum"|"evidenceId">):Promise<TrustedDocumentManifest>{const built=Object.freeze(await this.builder.build(structuredClone(input)));if(built.contentChecksum!==input.contentChecksum||built.templateVersionId!==input.templateVersionId||built.templateChecksum!==input.templateChecksum||built.effectiveSecurityLevel!==input.effectiveSecurityLevel||built.rendererId!==input.rendererId||built.rendererVersion!==input.rendererVersion||JSON.stringify(built.attachments)!==JSON.stringify(input.attachments))fail("DOCUMENT_MANIFEST_BUILDER_MISMATCH","Manifest builder may hash but not alter the locked snapshot.");trustedManifests.add(built);return built as TrustedDocumentManifest;}}
export interface DocumentVersionSnapshot { readonly documentVersionId: Uuid; readonly documentId: Uuid; readonly versionNo: number; readonly priorVersionId?: Uuid; readonly state: DocumentVersionState; readonly optimisticVersion: Version; readonly securityLevel: SecurityLevel; readonly templateSource:"TEMPLATE_VERSION"|"FREE_FORM"; readonly template?: TemplateVersionSnapshot; readonly content: EditorContent; readonly contentChecksum: Sha256; readonly contentValidationEvidenceId:Uuid;readonly sealedSnapshotChecksum?:Sha256;readonly sealedManifest?:SealedDocumentManifest; readonly authorUserId: Uuid; readonly creationReason: StableCode; readonly approvalInstanceId?: Uuid; readonly sealedAt?: UtcInstant; readonly approvedAt?: UtcInstant; readonly supersededByVersionId?: Uuid }
export interface DocumentActor { readonly userId: Uuid; readonly actorKind: "INTERNAL"|"SYSTEM"; readonly at: UtcInstant }
export interface DocumentCommand { readonly actor: DocumentActor; readonly expectedVersion: Version; readonly eventId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }
export interface DocumentEvidence { readonly eventType: StableCode; readonly eventId: Uuid; readonly documentId: Uuid; readonly documentVersionId: Uuid; readonly aggregateVersion: Version; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey; readonly beforeHash: Sha256; readonly afterHash: Sha256; readonly reason: StableCode }
export interface DocumentMutation { readonly expectedVersion: Version; readonly snapshot: DocumentVersionSnapshot; readonly evidence: DocumentEvidence }
export class DocumentDomainError extends Error { constructor(readonly code: StableCode, message: string) { super(message); this.name = "DocumentDomainError"; } }
const fail = (code: string, message: string): never => { throw new DocumentDomainError(code as StableCode, message); };
const clone = <T>(value: T): T => structuredClone(value);

export class TemplateVersion {
  private constructor(private readonly value: TemplateVersionSnapshot) {}
  static sealed(snapshot: TemplateVersionSnapshot): TemplateVersion { if (snapshot.versionNo < 1 || !Number.isInteger(snapshot.versionNo)) fail("TEMPLATE_VERSION_INVALID", "Template version must be positive."); return new TemplateVersion(clone(snapshot)); }
  snapshot(): TemplateVersionSnapshot { return clone(this.value); }
}

export class DocumentVersion {
  private constructor(private value: DocumentVersionSnapshot) {}
  static draft(input: Omit<DocumentVersionSnapshot,"state"|"optimisticVersion"|"sealedAt"|"approvedAt"|"approvalInstanceId"|"supersededByVersionId"|"content"|"contentChecksum"|"contentValidationEvidenceId"|"sealedSnapshotChecksum"|"sealedManifest"> & {verifiedContent:VerifiedEditorContent}): DocumentVersion { if (input.versionNo < 1 || !Number.isInteger(input.versionNo)) fail("DOCUMENT_VERSION_NUMBER_INVALID", "Version number must be positive."); if((input.templateSource==="TEMPLATE_VERSION")!==Boolean(input.template))fail("DOCUMENT_TEMPLATE_SNAPSHOT_INVALID","Template source and snapshot must agree.");const verified=contentSnapshot(input.verifiedContent);const record=Object.fromEntries(Object.entries(input).filter(([key])=>key!=="verifiedContent")) as Omit<typeof input,"verifiedContent">;return new DocumentVersion({ ...clone(record),content:verified.content,contentChecksum:verified.checksum,contentValidationEvidenceId:verified.validationEvidenceId,state: "DRAFT", optimisticVersion: 0 as Version }); }
  static restore(snapshot: DocumentVersionSnapshot): DocumentVersion { if(snapshot.versionNo<1||!Number.isInteger(snapshot.versionNo)||Number(snapshot.optimisticVersion)<0)fail("DOCUMENT_SNAPSHOT_INVALID","Invalid version fields.");if((snapshot.templateSource==="TEMPLATE_VERSION")!==Boolean(snapshot.template))fail("DOCUMENT_TEMPLATE_SNAPSHOT_INVALID","Template source and snapshot must agree.");if(snapshot.state!=="DRAFT"&&(!snapshot.sealedAt||!snapshot.sealedManifest||snapshot.sealedSnapshotChecksum!==snapshot.sealedManifest.checksum))fail("DOCUMENT_SEAL_EVIDENCE_REQUIRED","Sealed lifecycle requires the exact canonical manifest.");if(snapshot.state==="APPROVAL_PENDING"&&!snapshot.approvalInstanceId)fail("DOCUMENT_APPROVAL_LINK_REQUIRED","Approval pending requires exact approval link.");if(snapshot.state==="APPROVED"&&(!snapshot.approvalInstanceId||!snapshot.approvedAt))fail("DOCUMENT_APPROVAL_EVIDENCE_REQUIRED","Approved state requires approval evidence.");return new DocumentVersion(clone(snapshot)); }
  static revision(input:{previous:DocumentVersionSnapshot;documentVersionId:Uuid;authorUserId:Uuid;creationReason:StableCode;verifiedContent:VerifiedEditorContent}):DocumentVersion{if(!["REJECTED","RECALLED","APPROVED"].includes(input.previous.state))fail("DOCUMENT_REVISION_SOURCE_INVALID","Revision requires rejected, recalled, or approved predecessor.");return DocumentVersion.draft({documentVersionId:input.documentVersionId,documentId:input.previous.documentId,versionNo:input.previous.versionNo+1,priorVersionId:input.previous.documentVersionId,securityLevel:input.previous.securityLevel,templateSource:input.previous.templateSource,template:input.previous.template,authorUserId:input.authorUserId,creationReason:input.creationReason,verifiedContent:input.verifiedContent});}
  snapshot(): DocumentVersionSnapshot { return clone(this.value); }
  edit(command: DocumentCommand, verifiedContent:VerifiedEditorContent): DocumentMutation { this.guard(command, "DRAFT"); this.requireAuthor(command);const verified=contentSnapshot(verifiedContent);return this.change(command, { ...this.value,content:verified.content,contentChecksum:verified.checksum,contentValidationEvidenceId:verified.validationEvidenceId }, "EVT-DOCUMENT-EDIT", "DOCUMENT_EDIT"); }
  seal(command: DocumentCommand,manifest:TrustedDocumentManifest): DocumentMutation { this.guard(command, "DRAFT"); this.requireAuthor(command);if(!trustedManifests.has(manifest))fail("DOCUMENT_MANIFEST_UNTRUSTED","Trusted manifest builder required.");if(manifest.contentChecksum!==this.value.contentChecksum||manifest.effectiveSecurityLevel!==this.value.securityLevel||manifest.templateVersionId!==this.value.template?.templateVersionId||manifest.templateChecksum!==this.value.template?.checksum)fail("DOCUMENT_MANIFEST_MISMATCH","Manifest must bind exact content, template and security.");return this.change(command, { ...this.value,sealedSnapshotChecksum:manifest.checksum,sealedManifest:structuredClone(manifest), state: "REVIEW_READY", sealedAt: command.actor.at }, "EVT-DOCUMENT-SEAL", "DOCUMENT_SEAL"); }
  submit(command: DocumentCommand, approvalInstanceId: Uuid): DocumentMutation { this.guard(command, "REVIEW_READY"); this.requireAuthor(command); return this.change(command, { ...this.value, state: "APPROVAL_PENDING", approvalInstanceId }, "EVT-DOCUMENT-SUBMIT", "DOCUMENT_SUBMIT"); }
  applyApprovalOutcome(command: DocumentCommand, outcome: "APPROVED"|"REJECTED"|"RECALLED"): DocumentMutation { this.guard(command, "APPROVAL_PENDING"); if (command.actor.actorKind !== "SYSTEM") fail("DOCUMENT_SYSTEM_OUTCOME_REQUIRED", "Approval outcome is a system transition."); return this.change(command, { ...this.value, state: outcome, approvedAt: outcome === "APPROVED" ? command.actor.at : undefined }, `EVT-DOCUMENT-${outcome === "APPROVED" ? "APPROVE" : outcome === "REJECTED" ? "REJECT" : "RECALL"}`, `DOCUMENT_${outcome}`); }
  supersede(command: DocumentCommand, newer: { documentVersionId: Uuid; documentId: Uuid; versionNo: number; priorVersionId?: Uuid }): DocumentMutation { this.guard(command, "APPROVED"); if (newer.documentId !== this.value.documentId || newer.priorVersionId !== this.value.documentVersionId || newer.versionNo <= this.value.versionNo) fail("DOCUMENT_SUCCESSOR_INVALID", "Successor must be a newer version of the same document root."); return this.change(command, { ...this.value, state: "SUPERSEDED", supersededByVersionId: newer.documentVersionId }, "EVT-DOCUMENT-REVISE", "DOCUMENT_SUPERSEDE"); }
  private guard(command: DocumentCommand, state: DocumentVersionState): void { if (command.expectedVersion !== this.value.optimisticVersion) fail("DOCUMENT_STALE_VERSION", "Optimistic version conflict; no automatic overwrite."); if (this.value.state !== state) fail("DOCUMENT_STATE_INVALID", `Expected ${state}, found ${this.value.state}.`); }
  private requireAuthor(command: DocumentCommand): void { if (command.actor.actorKind !== "INTERNAL" || command.actor.userId !== this.value.authorUserId) fail("DOCUMENT_AUTHOR_REQUIRED", "Only the internal author may perform this transition."); }
  private change(command: DocumentCommand, next: DocumentVersionSnapshot, eventType: string, reason: string): DocumentMutation { const before = this.value.sealedSnapshotChecksum??this.value.contentChecksum; this.value = { ...clone(next), optimisticVersion: (Number(this.value.optimisticVersion)+1) as Version }; return { expectedVersion: command.expectedVersion, snapshot: this.snapshot(), evidence: { eventType: eventType as StableCode, eventId: command.eventId, documentId: this.value.documentId, documentVersionId: this.value.documentVersionId, aggregateVersion: this.value.optimisticVersion, occurredAt: command.actor.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, beforeHash: before, afterHash: this.value.sealedSnapshotChecksum??this.value.contentChecksum, reason: reason as StableCode } }; }
}
