import type { CorrelationId, IdempotencyKey, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import type { CompletedControlledCopyApproval, ControlledCopyRecipientScopeSnapshot, ControlledCopyRequestSnapshot, ExactApprovedDocumentVersion, ExactCopyRecipient, PerPageWatermark, RenderedCopyEvidence, TechCopyMutation, TechnicalDocumentCopySnapshot } from "../domain/tech-copy.js";

export interface ApprovedDocumentVersionPort { getExactApproved(input: { readonly documentVersionId: Uuid; readonly versionNo: number; readonly checksum: string; readonly sealedAt: UtcInstant }): Promise<ExactApprovedDocumentVersion> }
export interface ControlledCopyApprovalPort { getCompletedExact(approvalInstanceId: Uuid): Promise<CompletedControlledCopyApproval> }
export interface ControlledCopyRecipientScopePort { revalidate(input: { readonly action: ControlledCopyRecipientScopeSnapshot["action"]; readonly recipient: ExactCopyRecipient; readonly projectId: Uuid; readonly contractId?: Uuid; readonly purposeHash: string; readonly at: UtcInstant }): Promise<ControlledCopyRecipientScopeSnapshot> }
export interface ControlledCopyNumberPort { reserveUnique(input: { readonly technicalDocumentCopyId: Uuid; readonly requestedCopyNo?: string }): Promise<string> }
export interface ControlledCopyRendererPort { render(input: { readonly request: ControlledCopyRequestSnapshot; readonly watermark: PerPageWatermark; readonly approval: CompletedControlledCopyApproval }): Promise<RenderedCopyEvidence> }
export interface ControlledCopyRepository { loadForUpdate(id: Uuid): Promise<TechnicalDocumentCopySnapshot | undefined>; insert(snapshot: TechnicalDocumentCopySnapshot): Promise<void>; save(snapshot: TechnicalDocumentCopySnapshot, expectedVersion: Version): Promise<boolean>; copyNumberExists(copyNo: string): Promise<boolean> }
export interface ControlledCopyEvidencePort { appendCustody(event: TechCopyMutation["custodyEvent"]): Promise<void>; appendAudit(input: { readonly actionId: StableCode; readonly technicalDocumentCopyId: Uuid; readonly actorUserId?: Uuid; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId }): Promise<void>; enqueue(input: { readonly eventId: StableCode; readonly technicalDocumentCopyId: Uuid; readonly version: Version; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }): Promise<void> }
export interface ControlledCopyTransaction { readonly repository: ControlledCopyRepository; readonly documents: ApprovedDocumentVersionPort; readonly approvals: ControlledCopyApprovalPort; readonly recipientScope: ControlledCopyRecipientScopePort; readonly copyNumbers: ControlledCopyNumberPort; readonly renderer: ControlledCopyRendererPort; readonly evidence: ControlledCopyEvidencePort }
export interface ControlledCopyUnitOfWork { transact<T>(work: (context: ControlledCopyTransaction) => Promise<T>): Promise<T> }
