import type { IdempotencyKey, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import { SAFETY_INCIDENT_MACHINE_ID, SAFETY_INSPECTION_MACHINE_ID, SAFETY_RECORD_EVENT_IDS, type EmergencyResponseSnapshot, type IncidentInvestigationSnapshot, type IncidentRecurrenceActionSnapshot, type IncidentVerificationSnapshot, type SafetyActor, type SafetyAuditObligation, type SafetyCorrectionAssignmentSnapshot, type SafetyCorrectionSubmissionSnapshot, type SafetyCorrectionVerificationSnapshot, type SafetyDomainEvent, type SafetyFindingSnapshot, type SafetyIncidentMutation, type SafetyIncidentSnapshot, type SafetyIncidentState, type SafetyInspectionItemSnapshot, type SafetyInspectionMutation, type SafetyInspectionSnapshot, type SafetyInspectionState, type SafetyManagerAssignmentSnapshot, type SafetyRetentionSnapshot, type SafetyTrainingAttendanceSnapshot, type SafetyTrainingSessionSnapshot, type SafetyTransition, type SiteSecuringSnapshot, type StopWorkOrderSnapshot } from "../domain/safety.js";

export interface SafetyManagerAssignmentRepository { assertNoConflictingActiveAssignment(snapshot: SafetyManagerAssignmentSnapshot): Promise<void>; insert(snapshot: SafetyManagerAssignmentSnapshot): Promise<void> }
export interface SafetyInspectionRepository { insert(snapshot: SafetyInspectionSnapshot): Promise<void>; save(snapshot: SafetyInspectionSnapshot, expectedVersion: Version): Promise<boolean>; appendItems(items: readonly SafetyInspectionItemSnapshot[]): Promise<void>; appendFindings(findings: readonly SafetyFindingSnapshot[]): Promise<void>; appendStopWorkOrder(snapshot: StopWorkOrderSnapshot): Promise<void>; appendCorrectionAssignment(snapshot: SafetyCorrectionAssignmentSnapshot): Promise<void>; appendCorrectionSubmission(snapshot: SafetyCorrectionSubmissionSnapshot): Promise<void>; appendCorrectionVerification(snapshot: SafetyCorrectionVerificationSnapshot): Promise<void> }
export interface SafetyIncidentRepository { insert(snapshot: SafetyIncidentSnapshot): Promise<void>; save(snapshot: SafetyIncidentSnapshot, expectedVersion: Version): Promise<boolean>; appendEmergencyResponse(snapshot: EmergencyResponseSnapshot): Promise<void>; appendSiteSecuring(snapshot: SiteSecuringSnapshot): Promise<void>; appendInvestigation(snapshot: IncidentInvestigationSnapshot): Promise<void>; appendRecurrenceAction(snapshot: IncidentRecurrenceActionSnapshot): Promise<void>; appendVerification(snapshot: IncidentVerificationSnapshot): Promise<void>; listInvestigationSlaBreachesForUpdate(at: UtcInstant): Promise<readonly SafetyIncidentSnapshot[]> }
export interface SafetyTrainingRepository { insertSession(snapshot: SafetyTrainingSessionSnapshot): Promise<void>; insertAttendance(snapshot: SafetyTrainingAttendanceSnapshot): Promise<void> }
export interface SafetyAuthorityPort { assertLabDirector(input: { readonly actor: SafetyActor; readonly at: UtcInstant }): Promise<void>; assertActiveSafetyAuthority(input: { readonly assignmentId?: Uuid; readonly actorUserId: Uuid; readonly eventId: StableCode; readonly at: UtcInstant }): Promise<void>; assertIncidentReportAuthority(input: { readonly actor: SafetyActor; readonly scope: SafetyIncidentSnapshot["scope"]; readonly at: UtcInstant }): Promise<void> }
export interface SafetyReferencePort { assertScope(input: SafetyInspectionSnapshot["scope"]): Promise<void>; assertPrivateEvidenceIds(ids: readonly Uuid[]): Promise<void>; assertRetention(snapshot: SafetyRetentionSnapshot): Promise<void>; assertTrainingSession(id: Uuid): Promise<void> }
export interface SafetyEvidencePort { appendTransition(transition: SafetyTransition): Promise<void>; appendAudit(obligation: SafetyAuditObligation): Promise<void>; enqueue(event: SafetyDomainEvent): Promise<void>; appendRecordAudit(input: { readonly eventId: StableCode; readonly aggregateId: Uuid; readonly actor: SafetyActor; readonly occurredAt: UtcInstant; readonly evidenceIds: readonly Uuid[] }): Promise<void>; enqueueRecord(input: { readonly eventId: StableCode; readonly aggregateId: Uuid; readonly occurredAt: UtcInstant; readonly idempotencyKey: IdempotencyKey; readonly payload: Readonly<Record<string, string | number | boolean | null>> }): Promise<void> }
export interface IncidentSlaAlertSnapshot { readonly incidentSlaAlertId: Uuid; readonly safetyIncidentId: Uuid; readonly dueAt: UtcInstant; readonly detectedAt: UtcInstant; readonly recipientUserId: Uuid; readonly idempotencyKey: IdempotencyKey; readonly stateObserved: SafetyIncidentState; readonly autoCompleted: false }
export interface IncidentSlaAlertRepository { insertIfAbsent(snapshot: IncidentSlaAlertSnapshot): Promise<"INSERTED" | "ALREADY_EXISTS"> }
export interface SafetyTransactionContext { readonly assignments: SafetyManagerAssignmentRepository; readonly inspections: SafetyInspectionRepository; readonly incidents: SafetyIncidentRepository; readonly training: SafetyTrainingRepository; readonly authority: SafetyAuthorityPort; readonly references: SafetyReferencePort; readonly alerts: IncidentSlaAlertRepository; readonly evidence: SafetyEvidencePort }
export interface SafetyUnitOfWork { transact<T>(work: (context: SafetyTransactionContext) => Promise<T>): Promise<T> }
export class SafetyApplicationError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "SafetyApplicationError"; } }

function actorUserId(actor: SafetyActor): Uuid { if (actor.actorKind !== "INTERNAL" || !actor.active || !actor.userId) throw new SafetyApplicationError("SAFETY_INTERNAL_ACTOR_REQUIRED" as StableCode, "A trusted active internal actor is required."); return actor.userId; }
async function authorizeMutation(context: SafetyTransactionContext, transition: SafetyTransition, actor: SafetyActor): Promise<void> { const userId = actorUserId(actor); await context.authority.assertActiveSafetyAuthority({ ...(actor.safetyAssignmentId ? { assignmentId: actor.safetyAssignmentId } : {}), actorUserId: userId, eventId: transition.eventId, at: transition.occurredAt }); }
async function appendEvidence(context: SafetyTransactionContext, expectedVersion: Version, transition: SafetyTransition, audit: SafetyAuditObligation, event: SafetyDomainEvent): Promise<void> { if (transition.fromVersion !== expectedVersion || transition.toVersion !== expectedVersion + 1 || event.aggregateVersion !== transition.toVersion || event.aggregateId !== transition.aggregateId || event.occurredAt !== transition.occurredAt) throw new SafetyApplicationError("SAFETY_EVIDENCE_ENVELOPE_INVALID" as StableCode, "Transition, audit and outbox must share exact version and occurrence provenance."); await context.evidence.appendTransition(transition); await context.evidence.appendAudit(audit); await context.evidence.enqueue(event); }
function assertInheritedRetention(root: SafetyRetentionSnapshot, child: SafetyRetentionSnapshot): void {
  if (root.policyVersionId !== child.policyVersionId || root.policyChecksum !== child.policyChecksum || root.referenceAt !== child.referenceAt || root.minimumYears !== child.minimumYears || root.applicableRegulatoryYears !== child.applicableRegulatoryYears || root.legalHoldUntil !== child.legalHoldUntil || root.retainUntil !== child.retainUntil) throw new SafetyApplicationError("SAFETY_CHILD_RETENTION_MISMATCH" as StableCode, "Append-only safety evidence must inherit the exact aggregate retention snapshot.");
}

export async function persistSafetyInspectionMutation(unitOfWork: SafetyUnitOfWork, mutation: SafetyInspectionMutation): Promise<void> {
  await unitOfWork.transact(async (context) => {
    await authorizeMutation(context, mutation.transition, mutation.audit.actor);
    await context.references.assertScope(mutation.snapshot.scope);
    await context.references.assertRetention(mutation.snapshot.retention);
    await context.references.assertPrivateEvidenceIds(mutation.audit.evidenceIds);
    for (const item of mutation.appendedItems ?? []) assertInheritedRetention(mutation.snapshot.retention, item.retention);
    for (const finding of mutation.appendedFindings ?? []) assertInheritedRetention(mutation.snapshot.retention, finding.retention);
    if (mutation.stopWorkOrder) assertInheritedRetention(mutation.snapshot.retention, mutation.stopWorkOrder.retention);
    if (mutation.correctionAssignment) assertInheritedRetention(mutation.snapshot.retention, mutation.correctionAssignment.retention);
    if (mutation.correctionSubmission) assertInheritedRetention(mutation.snapshot.retention, mutation.correctionSubmission.retention);
    if (mutation.correctionVerification) assertInheritedRetention(mutation.snapshot.retention, mutation.correctionVerification.retention);
    if (mutation.expectedVersion === 0) { if (mutation.snapshot.version !== 1 || mutation.transition.machineId !== SAFETY_INSPECTION_MACHINE_ID || mutation.transition.fromState !== undefined) throw new SafetyApplicationError("SAFETY_INSPECTION_CREATE_INVALID" as StableCode, "Inspection creation must be version 0 to 1."); await context.inspections.insert(mutation.snapshot); }
    else if (!await context.inspections.save(mutation.snapshot, mutation.expectedVersion)) throw new SafetyApplicationError("SAFETY_INSPECTION_STALE_VERSION" as StableCode, "Inspection optimistic lock lost.");
    if (mutation.appendedItems) await context.inspections.appendItems(mutation.appendedItems);
    if (mutation.appendedFindings) await context.inspections.appendFindings(mutation.appendedFindings);
    if (mutation.stopWorkOrder) await context.inspections.appendStopWorkOrder(mutation.stopWorkOrder);
    if (mutation.correctionAssignment) await context.inspections.appendCorrectionAssignment(mutation.correctionAssignment);
    if (mutation.correctionSubmission) await context.inspections.appendCorrectionSubmission(mutation.correctionSubmission);
    if (mutation.correctionVerification) await context.inspections.appendCorrectionVerification(mutation.correctionVerification);
    await appendEvidence(context, mutation.expectedVersion, mutation.transition, mutation.audit, mutation.event);
  });
}

export async function persistSafetyIncidentMutation(unitOfWork: SafetyUnitOfWork, mutation: SafetyIncidentMutation): Promise<void> {
  await unitOfWork.transact(async (context) => {
    const reporterCreate = mutation.expectedVersion === 0;
    if (!reporterCreate) await authorizeMutation(context, mutation.transition, mutation.audit.actor);
    else await context.authority.assertIncidentReportAuthority({ actor: mutation.audit.actor, scope: mutation.snapshot.scope, at: mutation.transition.occurredAt });
    await context.references.assertScope(mutation.snapshot.scope); await context.references.assertRetention(mutation.snapshot.retention); await context.references.assertPrivateEvidenceIds(mutation.audit.evidenceIds);
    if (mutation.emergencyResponse) assertInheritedRetention(mutation.snapshot.retention, mutation.emergencyResponse.retention);
    if (mutation.siteSecuring) assertInheritedRetention(mutation.snapshot.retention, mutation.siteSecuring.retention);
    if (mutation.investigation) assertInheritedRetention(mutation.snapshot.retention, mutation.investigation.retention);
    if (mutation.recurrenceAction) assertInheritedRetention(mutation.snapshot.retention, mutation.recurrenceAction.retention);
    if (mutation.verification) assertInheritedRetention(mutation.snapshot.retention, mutation.verification.retention);
    if (reporterCreate) { if (mutation.snapshot.version !== 1 || mutation.transition.machineId !== SAFETY_INCIDENT_MACHINE_ID || mutation.transition.fromState !== undefined) throw new SafetyApplicationError("SAFETY_INCIDENT_REPORT_INVALID" as StableCode, "Incident reporting must be version 0 to 1."); await context.incidents.insert(mutation.snapshot); }
    else if (!await context.incidents.save(mutation.snapshot, mutation.expectedVersion)) throw new SafetyApplicationError("SAFETY_INCIDENT_STALE_VERSION" as StableCode, "Incident optimistic lock lost.");
    if (mutation.emergencyResponse) await context.incidents.appendEmergencyResponse(mutation.emergencyResponse);
    if (mutation.siteSecuring) await context.incidents.appendSiteSecuring(mutation.siteSecuring);
    if (mutation.investigation) await context.incidents.appendInvestigation(mutation.investigation);
    if (mutation.recurrenceAction) await context.incidents.appendRecurrenceAction(mutation.recurrenceAction);
    if (mutation.verification) await context.incidents.appendVerification(mutation.verification);
    await appendEvidence(context, mutation.expectedVersion, mutation.transition, mutation.audit, mutation.event);
  });
}

export async function persistSafetyManagerAssignment(unitOfWork: SafetyUnitOfWork, snapshot: SafetyManagerAssignmentSnapshot, actor: SafetyActor, at: UtcInstant, idempotencyKey: IdempotencyKey): Promise<void> { await unitOfWork.transact(async (context) => { await context.authority.assertLabDirector({ actor, at }); await context.references.assertRetention(snapshot.retention); await context.references.assertPrivateEvidenceIds(snapshot.evidenceIds); await context.assignments.assertNoConflictingActiveAssignment(snapshot); await context.assignments.insert(snapshot); await context.evidence.appendRecordAudit({ eventId: SAFETY_RECORD_EVENT_IDS.ASSIGN_MANAGER as StableCode, aggregateId: snapshot.safetyManagerAssignmentId, actor, occurredAt: at, evidenceIds: snapshot.evidenceIds }); await context.evidence.enqueueRecord({ eventId: SAFETY_RECORD_EVENT_IDS.ASSIGN_MANAGER as StableCode, aggregateId: snapshot.safetyManagerAssignmentId, occurredAt: at, idempotencyKey, payload: { assignmentKind: snapshot.assignmentKind, assignmentScopeKind: snapshot.assignmentScope?.kind ?? "LAB", validFrom: snapshot.validFrom } }); }); }
export async function persistTrainingSession(unitOfWork: SafetyUnitOfWork, snapshot: SafetyTrainingSessionSnapshot, actor: SafetyActor, idempotencyKey: IdempotencyKey): Promise<void> { await unitOfWork.transact(async (context) => { await authorizeRecord(context, actor, SAFETY_RECORD_EVENT_IDS.RECORD_TRAINING, snapshot.recordedAt); await context.references.assertRetention(snapshot.retention); await context.references.assertPrivateEvidenceIds(snapshot.materialAttachmentIds); await context.training.insertSession(snapshot); await context.evidence.appendRecordAudit({ eventId: SAFETY_RECORD_EVENT_IDS.RECORD_TRAINING as StableCode, aggregateId: snapshot.safetyTrainingSessionId, actor, occurredAt: snapshot.recordedAt, evidenceIds: snapshot.materialAttachmentIds }); await context.evidence.enqueueRecord({ eventId: SAFETY_RECORD_EVENT_IDS.RECORD_TRAINING as StableCode, aggregateId: snapshot.safetyTrainingSessionId, occurredAt: snapshot.recordedAt, idempotencyKey, payload: { trainingType: snapshot.trainingType, autoCompleted: false } }); }); }
export async function persistTrainingAttendance(unitOfWork: SafetyUnitOfWork, snapshot: SafetyTrainingAttendanceSnapshot, actor: SafetyActor, idempotencyKey: IdempotencyKey): Promise<void> { await unitOfWork.transact(async (context) => { await authorizeRecord(context, actor, SAFETY_RECORD_EVENT_IDS.RECORD_ATTENDANCE, snapshot.recordedAt); await context.references.assertTrainingSession(snapshot.safetyTrainingSessionId); await context.references.assertRetention(snapshot.retention); await context.references.assertPrivateEvidenceIds(snapshot.completionEvidenceIds); await context.training.insertAttendance(snapshot); await context.evidence.appendRecordAudit({ eventId: SAFETY_RECORD_EVENT_IDS.RECORD_ATTENDANCE as StableCode, aggregateId: snapshot.safetyTrainingAttendanceId, actor, occurredAt: snapshot.recordedAt, evidenceIds: snapshot.completionEvidenceIds }); await context.evidence.enqueueRecord({ eventId: SAFETY_RECORD_EVENT_IDS.RECORD_ATTENDANCE as StableCode, aggregateId: snapshot.safetyTrainingAttendanceId, occurredAt: snapshot.recordedAt, idempotencyKey, payload: { status: snapshot.status, remedialRequired: snapshot.remedialRequired, autoCompleted: false } }); }); }
async function authorizeRecord(context: SafetyTransactionContext, actor: SafetyActor, eventId: string, at: UtcInstant): Promise<void> { const userId = actorUserId(actor); await context.authority.assertActiveSafetyAuthority({ ...(actor.safetyAssignmentId ? { assignmentId: actor.safetyAssignmentId } : {}), actorUserId: userId, eventId: eventId as StableCode, at }); }

export async function emitIncidentInvestigationSlaAlerts(unitOfWork: SafetyUnitOfWork, input: { readonly detectedAt: UtcInstant; readonly recipientUserId: Uuid; readonly makeAlertId: (incident: SafetyIncidentSnapshot) => Uuid; readonly makeIdempotencyKey: (incident: SafetyIncidentSnapshot) => IdempotencyKey }): Promise<{ readonly inserted: number; readonly alreadyExists: number }> {
  return unitOfWork.transact(async (context) => { const incidents = await context.incidents.listInvestigationSlaBreachesForUpdate(input.detectedAt); let inserted = 0; let alreadyExists = 0; for (const incident of incidents) { const investigationStartedOnTime = incident.investigationStartedAt !== undefined && incident.investigationStartedAt <= incident.investigationDueAt; if (investigationStartedOnTime || incident.investigationDueAt > input.detectedAt) continue; const alert: IncidentSlaAlertSnapshot = Object.freeze({ incidentSlaAlertId: input.makeAlertId(incident), safetyIncidentId: incident.safetyIncidentId, dueAt: incident.investigationDueAt, detectedAt: input.detectedAt, recipientUserId: input.recipientUserId, idempotencyKey: input.makeIdempotencyKey(incident), stateObserved: incident.state, autoCompleted: false }); const result = await context.alerts.insertIfAbsent(alert); if (result === "ALREADY_EXISTS") { alreadyExists += 1; continue; } inserted += 1; await context.evidence.appendRecordAudit({ eventId: SAFETY_RECORD_EVENT_IDS.INCIDENT_SLA_ALERT as StableCode, aggregateId: incident.safetyIncidentId, actor: { actorKind: "SYSTEM", active: true, positionIds: [], permissionIds: [] }, occurredAt: input.detectedAt, evidenceIds: [] }); await context.evidence.enqueueRecord({ eventId: SAFETY_RECORD_EVENT_IDS.INCIDENT_SLA_ALERT as StableCode, aggregateId: incident.safetyIncidentId, occurredAt: input.detectedAt, idempotencyKey: alert.idempotencyKey, payload: { dueAt: alert.dueAt, stateObserved: alert.stateObserved, autoCompleted: false } }); } return { inserted, alreadyExists }; });
}

export interface SafetyInternalListItemView { readonly safetyRecordId: string; readonly recordKind: "INSPECTION" | "INCIDENT" | "TRAINING"; readonly recordNo: string; readonly title: string; readonly state: SafetyInspectionState | SafetyIncidentState | "SCHEDULED" | "ATTENDANCE_OPEN"; readonly dueAt?: string; readonly severity?: "MINOR" | "MAJOR" | "CRITICAL"; readonly scopeLabel: string; readonly nextAction: StableCode | null }
export interface SafetyInternalDetailView extends SafetyInternalListItemView { readonly history: readonly { readonly eventId: StableCode; readonly occurredAt: string; readonly actorDisplayName: string }[]; readonly evidenceCount: number; readonly retentionUntil: string }
export interface VendorSafetyScopeView { readonly safetyRecordId: string; readonly recordKind: "INSTRUCTION" | "ACKNOWLEDGEMENT_REQUIRED" | "CORRECTIVE_TASK"; readonly title: string; readonly state: "OPEN" | "SUBMITTED" | "VERIFIED"; readonly projectId?: string; readonly contractId?: string; readonly dueAt?: string; readonly nextAction: StableCode | null }
export interface VendorSafetyProjectionSource extends VendorSafetyScopeView { readonly [key: string]: unknown }
export function projectVendorSafetyScope(source: VendorSafetyProjectionSource): VendorSafetyScopeView { return Object.freeze({ safetyRecordId: source.safetyRecordId, recordKind: source.recordKind, title: source.title, state: source.state, ...(source.projectId === undefined ? {} : { projectId: source.projectId }), ...(source.contractId === undefined ? {} : { contractId: source.contractId }), ...(source.dueAt === undefined ? {} : { dueAt: source.dueAt }), nextAction: source.nextAction }); }
export type SafetyInternalListResult = { readonly availability: "AVAILABLE"; readonly items: readonly SafetyInternalListItemView[] } | { readonly availability: "FORBIDDEN"; readonly items: readonly [] } | { readonly availability: "UNAVAILABLE"; readonly items: readonly []; readonly reason: "QUERY_ADAPTER_NOT_CONFIGURED" };
export type SafetyInternalDetailResult = { readonly availability: "AVAILABLE"; readonly detail: SafetyInternalDetailView } | { readonly availability: "FORBIDDEN" | "NOT_FOUND"; readonly detail: null } | { readonly availability: "UNAVAILABLE"; readonly detail: null; readonly reason: "QUERY_ADAPTER_NOT_CONFIGURED" };
export type VendorSafetyListResult = { readonly availability: "AVAILABLE"; readonly items: readonly VendorSafetyScopeView[] } | { readonly availability: "FORBIDDEN"; readonly items: readonly [] } | { readonly availability: "UNAVAILABLE"; readonly items: readonly []; readonly reason: "QUERY_ADAPTER_NOT_CONFIGURED" };
export interface SafetyQueryPort { listInternal(): Promise<SafetyInternalListResult>; getInternal(safetyRecordId: string): Promise<SafetyInternalDetailResult>; listMineVendorScope(): Promise<VendorSafetyListResult> }
export const SAFETY_VENDOR_FORBIDDEN_FIELDS = Object.freeze(["injuredPersonIdentity", "medicalDetails", "causeDeliberation", "internalNotes", "employeeDiscipline", "privateEvidence", "storagePath", "signedUrl"] as const);
