import type { CorrelationId, IdempotencyKey, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";

export const TECH_COPY_MACHINE_ID = "SM-TECHDOC-COPY-V1" as const;
export const TECH_COPY_EVENT_IDS = Object.freeze({ REQUEST: "EVT-TECHCOPY-REQUEST", SUBMIT: "EVT-TECHCOPY-SUBMIT", APPROVE: "EVT-TECHCOPY-APPROVE", RENDER: "EVT-TECHCOPY-RENDER", PRINT: "EVT-TECHCOPY-PRINT", HANDOVER: "EVT-TECHCOPY-HANDOVER", RETURN_DUE: "EVT-TECHCOPY-RETURN-DUE", RETURN: "EVT-TECHCOPY-RETURN", DESTROY: "EVT-TECHCOPY-DESTROY", OVERDUE: "EVT-TECHCOPY-OVERDUE" } as const);
export const TECH_COPY_PERMISSION_IDS = Object.freeze({ REQUEST: "technical_document.copy.request", PRINT: "technical_document.copy.print", CUSTODY: "technical_document.copy.custody", RETURN: "technical_document.copy.return", DESTROY: "technical_document.copy.destroy" } as const);
export type TechCopyState = "REQUESTED" | "APPROVAL_PENDING" | "APPROVED" | "RENDERED" | "PRINTED" | "HANDED_OVER" | "RETURN_DUE" | "RETURNED" | "DESTROYED" | "OVERDUE" | "CANCELLED";
export type TechCopySecurityLevel = "L3" | "L4";

export interface TechCopyActor { readonly kind: "INTERNAL" | "VENDOR" | "SYSTEM"; readonly userId?: Uuid; readonly active: boolean; readonly permissionIds: readonly StableCode[]; readonly serviceId?: "INTERNAL_DOCUMENT_SERVICE" | "TECH_COPY_FOLLOW_UP" }
export interface TechCopyCommand { readonly actor: TechCopyActor; readonly expectedVersion: Version; readonly occurredAt: UtcInstant; readonly commandId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }
export interface ExactApprovedDocumentVersion { readonly documentId: Uuid; readonly documentVersionId: Uuid; readonly versionNo: number; readonly state: "APPROVED"; readonly securityLevel: TechCopySecurityLevel; readonly projectId: Uuid; readonly contractId?: Uuid; readonly sealedSnapshotChecksum: Sha256; readonly sealedAt: UtcInstant; readonly approvedAt: UtcInstant; readonly sourceAttachmentId: Uuid; readonly sourceAttachmentRowVersion: Version; readonly sourceHash: Sha256 }
export interface ExactCopyRecipient { readonly recipientUserId: Uuid; readonly recipientDisplayName: string; readonly vendorId: Uuid; readonly vendorDisplayName: string }
export interface ControlledCopyRecipientScopeSnapshot { readonly action: "REQUEST" | "RENDER" | "PRINT" | "HANDOVER"; readonly recipientUserId: Uuid; readonly vendorId: Uuid; readonly projectId: Uuid; readonly contractId?: Uuid; readonly vendorMembershipId: Uuid; readonly vendorMembershipVersion: Version; readonly projectGrantId: Uuid; readonly projectGrantVersion: Version; readonly contractGrantId?: Uuid; readonly contractGrantVersion?: Version; readonly evaluatedAt: UtcInstant; readonly validUntil: UtcInstant; readonly evidenceIds: readonly Uuid[]; readonly snapshotChecksum: Sha256 }
export interface ControlledCopyRequestSnapshot { readonly technicalDocumentCopyId: Uuid; readonly copyNo: string; readonly document: ExactApprovedDocumentVersion; readonly recipient: ExactCopyRecipient; readonly initialScope: ControlledCopyRecipientScopeSnapshot; readonly purpose: string; readonly purposeCode: StableCode; readonly purposeHash: Sha256; readonly returnOrDestructionDueAt: UtcInstant; readonly requestedByUserId: Uuid; readonly requestedAt: UtcInstant; readonly requestVersion: Version; readonly requestChecksum: Sha256; readonly requestSealedAt: UtcInstant; readonly reprintOfCopyId?: Uuid; readonly reprintReason?: string }

export interface ApprovalParticipantEvidence { readonly participantId: Uuid; readonly userId: Uuid; readonly positionId: "POSITION_LAB_DIRECTOR" | "POSITION_REPRESENTATIVE"; readonly actionId?: Uuid; readonly approvedAt?: UtcInstant }
export interface ApprovalStepEvidence { readonly sequence: number; readonly role: "APPROVAL"; readonly completionMode: "SEQUENTIAL" | "ANY_ONE"; readonly required: true; readonly positionId: "POSITION_LAB_DIRECTOR" | "POSITION_REPRESENTATIVE"; readonly participants: readonly ApprovalParticipantEvidence[] }
export interface CompletedControlledCopyApproval { readonly approvalInstanceId: Uuid; readonly approvalInstanceVersion: Version; readonly state: "COMPLETED"; readonly subjectKind: "TECHNICAL_DOCUMENT_COPY_REQUEST"; readonly technicalDocumentCopyId: Uuid; readonly requestVersion: Version; readonly requestChecksum: Sha256; readonly requestSealedAt: UtcInstant; readonly documentVersionId: Uuid; readonly documentVersionNo: number; readonly documentChecksum: Sha256; readonly documentSealedAt: UtcInstant; readonly recipientUserId: Uuid; readonly vendorId: Uuid; readonly purposeHash: Sha256; readonly completedAt: UtcInstant; readonly terminalActionId: Uuid; readonly steps: readonly ApprovalStepEvidence[] }

export interface PerPageWatermark { readonly recipientDisplayName: string; readonly vendorDisplayName: string; readonly projectId: Uuid; readonly copyNo: string; readonly securityLevel: TechCopySecurityLevel; readonly issuerUserId: Uuid; readonly issuerDisplayName: string; readonly printedAt: UtcInstant; readonly purpose: string; readonly redistributionProhibition: string }
export interface RenderedCopyEvidence { readonly rendererId: StableCode; readonly rendererVersion: StableCode; readonly sourceHash: Sha256; readonly outputHash: Sha256; readonly outputAttachmentId: Uuid; readonly outputAttachmentRowVersion: Version; readonly outputVisibility: "PRIVATE"; readonly pageCount: number; readonly watermarkedPageCount: number; readonly watermark: PerPageWatermark; readonly watermarkChecksum: Sha256; readonly manifestChecksum: Sha256; readonly renderedAt: UtcInstant }
const trustedRenders = new WeakSet<object>();
const renderToken = Symbol("controlled-copy-render");
export class VerifiedRenderedCopy {
  public constructor(private readonly value: RenderedCopyEvidence, token: symbol) { if (token !== renderToken) fail("TECH_COPY_RENDER_UNTRUSTED", "Trusted renderer result is required."); trustedRenders.add(this); }
  public snapshot(): RenderedCopyEvidence { if (!trustedRenders.has(this)) fail("TECH_COPY_RENDER_UNTRUSTED", "Trusted renderer result is required."); return structuredClone(this.value); }
  public static assertTrusted(value: VerifiedRenderedCopy): void { if (!trustedRenders.has(value)) fail("TECH_COPY_RENDER_UNTRUSTED", "Trusted renderer result is required."); }
}
export class VerifiedRenderedCopyFactory {
  public create(expected: { readonly request: ControlledCopyRequestSnapshot; readonly issuerUserId: Uuid; readonly printedAt: UtcInstant }, value: RenderedCopyEvidence): VerifiedRenderedCopy {
    const request = expected.request;
    const watermark = value.watermark;
    if (value.sourceHash !== request.document.sourceHash || value.outputVisibility !== "PRIVATE" || value.pageCount < 1 || value.pageCount !== value.watermarkedPageCount || !value.rendererId || !value.rendererVersion) fail("TECH_COPY_RENDER_EVIDENCE_INVALID", "Private output, exact source hash, renderer version and every-page watermark evidence are required.");
    if (watermark.recipientDisplayName !== request.recipient.recipientDisplayName || watermark.vendorDisplayName !== request.recipient.vendorDisplayName || watermark.projectId !== request.document.projectId || watermark.copyNo !== request.copyNo || watermark.securityLevel !== request.document.securityLevel || watermark.issuerUserId !== expected.issuerUserId || watermark.printedAt !== expected.printedAt || watermark.purpose !== request.purpose || !watermark.redistributionProhibition.trim()) fail("TECH_COPY_WATERMARK_MISMATCH", "Every-page watermark must bind the exact request and print issue time.");
    return new VerifiedRenderedCopy(Object.freeze(structuredClone(value)), renderToken);
  }
}

export interface PrintEvidence { readonly printEventId: Uuid; readonly printedByUserId: Uuid; readonly printerDeviceRef: string; readonly printedAt: UtcInstant; readonly pageCount: number; readonly evidenceIds: readonly Uuid[] }
export interface HandoverEvidence { readonly handoverEventId: Uuid; readonly handedOverByUserId: Uuid; readonly acknowledgedByRecipientUserId: Uuid; readonly acknowledgedAt: UtcInstant; readonly pageCount: number; readonly evidenceIds: readonly Uuid[] }
export interface CustodyCompletionEvidence { readonly eventId: Uuid; readonly completedByUserId: Uuid; readonly pageCountReconciled: number; readonly reason: string; readonly evidenceIds: readonly Uuid[]; readonly completedAt: UtcInstant }
export interface TechCopyCustodyEvent { readonly eventId: Uuid; readonly eventType: (typeof TECH_COPY_EVENT_IDS)[keyof typeof TECH_COPY_EVENT_IDS]; readonly fromState?: TechCopyState; readonly toState: TechCopyState; readonly actorUserId?: Uuid; readonly occurredAt: UtcInstant; readonly evidenceIds: readonly Uuid[] }
export interface TechnicalDocumentCopySnapshot { readonly request: ControlledCopyRequestSnapshot; readonly state: TechCopyState; readonly optimisticVersion: Version; readonly approval?: CompletedControlledCopyApproval; readonly render?: RenderedCopyEvidence; readonly print?: PrintEvidence; readonly handover?: HandoverEvidence; readonly returnEvidence?: CustodyCompletionEvidence; readonly destructionEvidence?: CustodyCompletionEvidence; readonly scopeRevalidations: readonly ControlledCopyRecipientScopeSnapshot[]; readonly custodyEvents: readonly TechCopyCustodyEvent[]; readonly updatedAt: UtcInstant }
export interface TechCopyMutation { readonly expectedVersion: Version; readonly snapshot: TechnicalDocumentCopySnapshot; readonly custodyEvent: TechCopyCustodyEvent; readonly auditActionId: StableCode; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }

export interface ControlledCopyRequestCanonicalizerPort { canonicalizeAndHash(raw: Omit<ControlledCopyRequestSnapshot, "requestVersion" | "requestChecksum" | "requestSealedAt">): ControlledCopyRequestSnapshot }
const trustedRequests = new WeakSet<object>(); const requestToken = Symbol("controlled-copy-request");
export class VerifiedControlledCopyRequest { public constructor(private readonly value: ControlledCopyRequestSnapshot, token: symbol) { if (token !== requestToken) fail("TECH_COPY_REQUEST_UNTRUSTED", "Trusted request factory required."); trustedRequests.add(this); } public snapshot(): ControlledCopyRequestSnapshot { if (!trustedRequests.has(this)) fail("TECH_COPY_REQUEST_UNTRUSTED", "Trusted request factory required."); return structuredClone(this.value); } public static assertTrusted(value: VerifiedControlledCopyRequest): void { if (!trustedRequests.has(value)) fail("TECH_COPY_REQUEST_UNTRUSTED", "Trusted request factory required."); } }
export class VerifiedControlledCopyRequestFactory { public constructor(private readonly canonicalizer: ControlledCopyRequestCanonicalizerPort) {} public create(raw: Omit<ControlledCopyRequestSnapshot, "requestVersion" | "requestChecksum" | "requestSealedAt">): VerifiedControlledCopyRequest { const value = this.canonicalizer.canonicalizeAndHash(structuredClone(raw)); const { requestVersion: _requestVersion, requestChecksum: _requestChecksum, requestSealedAt: _requestSealedAt, ...unchanged } = value; void _requestVersion; void _requestChecksum; void _requestSealedAt; if (JSON.stringify(unchanged) !== JSON.stringify(raw)) fail("TECH_COPY_CANONICALIZER_SUBJECT_CHANGED", "Canonicalizer may hash and seal but cannot change the exact request subject."); assertRequest(value); return new VerifiedControlledCopyRequest(Object.freeze(structuredClone(value)), requestToken); } }

export class TechnicalDocumentCopy {
  private constructor(private value: TechnicalDocumentCopySnapshot) {}
  public static request(verified: VerifiedControlledCopyRequest, command: Omit<TechCopyCommand, "expectedVersion">): TechCopyMutation & { readonly aggregate: TechnicalDocumentCopy } {
    VerifiedControlledCopyRequest.assertTrusted(verified); const request = verified.snapshot(); assertInternal(command.actor, TECH_COPY_PERMISSION_IDS.REQUEST); if (command.actor.userId !== request.requestedByUserId || command.occurredAt !== request.requestedAt) fail("TECH_COPY_REQUEST_ACTOR_MISMATCH", "Requester and occurrence snapshot must match the direct internal actor.");
    if (command.actor.userId === request.recipient.recipientUserId) fail("TECH_COPY_RECIPIENT_IMPERSONATION_DENIED", "The internal requester and external recipient identities must remain distinct.");
    const aggregate = new TechnicalDocumentCopy(Object.freeze({ request, state: "REQUESTED", optimisticVersion: 0 as Version, scopeRevalidations: Object.freeze([request.initialScope]), custodyEvents: Object.freeze([]), updatedAt: command.occurredAt }));
    return { ...aggregate.record(undefined, "REQUESTED", TECH_COPY_EVENT_IDS.REQUEST, command, request.initialScope.evidenceIds), aggregate };
  }
  public static restore(snapshot: TechnicalDocumentCopySnapshot): TechnicalDocumentCopy { assertSnapshot(snapshot); return new TechnicalDocumentCopy(structuredClone(snapshot)); }
  public static reprint(previous: TechnicalDocumentCopySnapshot, verified: VerifiedControlledCopyRequest, command: Omit<TechCopyCommand, "expectedVersion">): TechCopyMutation & { readonly aggregate: TechnicalDocumentCopy } {
    const next = verified.snapshot(); if (!next.reprintOfCopyId || next.reprintOfCopyId !== previous.request.technicalDocumentCopyId || !next.reprintReason?.trim() || next.copyNo === previous.request.copyNo) fail("TECH_COPY_REPRINT_INVALID", "Reprint requires prior copy, new copy number and reason.");
    if (next.document.documentVersionId !== previous.request.document.documentVersionId || next.document.sealedSnapshotChecksum !== previous.request.document.sealedSnapshotChecksum || next.recipient.recipientUserId !== previous.request.recipient.recipientUserId || next.recipient.vendorId !== previous.request.recipient.vendorId || next.purposeHash !== previous.request.purposeHash) fail("TECH_COPY_REPRINT_SUBJECT_MISMATCH", "Reprint must preserve the exact approved document, recipient/vendor and purpose.");
    return TechnicalDocumentCopy.request(verified, command);
  }
  public snapshot(): TechnicalDocumentCopySnapshot { return structuredClone(this.value); }
  public submit(command: TechCopyCommand): TechCopyMutation { this.guard(command, ["REQUESTED"]); this.requireRequester(command.actor); return this.move("APPROVAL_PENDING", TECH_COPY_EVENT_IDS.SUBMIT, command, []); }
  public applyCompletedApproval(command: TechCopyCommand, approval: CompletedControlledCopyApproval): TechCopyMutation { this.guard(command, ["APPROVAL_PENDING"]); assertSystem(command.actor, "INTERNAL_DOCUMENT_SERVICE"); assertApproval(this.value.request, approval); this.value = { ...this.value, approval: Object.freeze(structuredClone(approval)) }; return this.move("APPROVED", TECH_COPY_EVENT_IDS.APPROVE, command, []); }
  public render(command: TechCopyCommand, verified: VerifiedRenderedCopy, scope: ControlledCopyRecipientScopeSnapshot): TechCopyMutation { this.guard(command, ["APPROVED"]); assertSystem(command.actor, "INTERNAL_DOCUMENT_SERVICE"); if (!this.value.approval) fail("TECH_COPY_APPROVAL_REQUIRED", "Completed approval is required before render."); VerifiedRenderedCopy.assertTrusted(verified); const render = verified.snapshot(); if (render.renderedAt !== command.occurredAt) fail("TECH_COPY_RENDER_TIME_MISMATCH", "Render occurrence must match evidence."); assertScope(this.value.request, scope, "RENDER", command.occurredAt); this.value = { ...this.value, render: Object.freeze(render), scopeRevalidations: this.withScope(scope) }; return this.move("RENDERED", TECH_COPY_EVENT_IDS.RENDER, command, scope.evidenceIds); }
  public print(command: TechCopyCommand, evidence: PrintEvidence, scope: ControlledCopyRecipientScopeSnapshot): TechCopyMutation { this.guard(command, ["RENDERED"]); assertInternal(command.actor, TECH_COPY_PERMISSION_IDS.PRINT); const render = this.value.render!; if (evidence.printedByUserId !== command.actor.userId || evidence.printedAt !== render.watermark.printedAt || evidence.pageCount !== render.pageCount || evidence.evidenceIds.length === 0 || !evidence.printerDeviceRef.trim()) fail("TECH_COPY_PRINT_EVIDENCE_INVALID", "Internal printer, device, exact watermarked print time/page count and evidence are required."); assertScope(this.value.request, scope, "PRINT", command.occurredAt); this.value = { ...this.value, print: Object.freeze(structuredClone(evidence)), scopeRevalidations: this.withScope(scope) }; return this.move("PRINTED", TECH_COPY_EVENT_IDS.PRINT, command, [...scope.evidenceIds, ...evidence.evidenceIds]); }
  public handover(command: TechCopyCommand, evidence: HandoverEvidence, scope: ControlledCopyRecipientScopeSnapshot): TechCopyMutation { this.guard(command, ["PRINTED"]); assertInternal(command.actor, TECH_COPY_PERMISSION_IDS.CUSTODY); if (evidence.handedOverByUserId !== command.actor.userId || evidence.acknowledgedByRecipientUserId !== this.value.request.recipient.recipientUserId || evidence.pageCount !== this.value.print?.pageCount || evidence.evidenceIds.length === 0 || evidence.acknowledgedAt !== command.occurredAt) fail("TECH_COPY_HANDOVER_EVIDENCE_INVALID", "Exact recipient acknowledgement and all-page handover evidence are required."); assertScope(this.value.request, scope, "HANDOVER", command.occurredAt); this.value = { ...this.value, handover: Object.freeze(structuredClone(evidence)), scopeRevalidations: this.withScope(scope) }; return this.move("HANDED_OVER", TECH_COPY_EVENT_IDS.HANDOVER, command, [...scope.evidenceIds, ...evidence.evidenceIds]); }
  public markReturnDue(command: TechCopyCommand): TechCopyMutation { this.guard(command, ["HANDED_OVER"]); assertSystem(command.actor, "TECH_COPY_FOLLOW_UP"); if (command.occurredAt < this.value.request.returnOrDestructionDueAt) fail("TECH_COPY_RETURN_NOT_DUE", "Follow-up begins only when the due time is reached."); return this.move("RETURN_DUE", TECH_COPY_EVENT_IDS.RETURN_DUE, command, []); }
  public markOverdue(command: TechCopyCommand): TechCopyMutation { this.guard(command, ["RETURN_DUE"]); assertSystem(command.actor, "TECH_COPY_FOLLOW_UP"); return this.move("OVERDUE", TECH_COPY_EVENT_IDS.OVERDUE, command, []); }
  public recordReturn(command: TechCopyCommand, evidence: CustodyCompletionEvidence): TechCopyMutation { this.guard(command, ["HANDED_OVER", "RETURN_DUE", "OVERDUE"]); assertInternal(command.actor, TECH_COPY_PERMISSION_IDS.RETURN); this.assertCompletion(command, evidence); this.value = { ...this.value, returnEvidence: Object.freeze(structuredClone(evidence)) }; return this.move("RETURNED", TECH_COPY_EVENT_IDS.RETURN, command, evidence.evidenceIds); }
  public recordDestruction(command: TechCopyCommand, evidence: CustodyCompletionEvidence): TechCopyMutation { this.guard(command, ["HANDED_OVER", "RETURN_DUE", "RETURNED", "OVERDUE"]); assertInternal(command.actor, TECH_COPY_PERMISSION_IDS.DESTROY); this.assertCompletion(command, evidence); this.value = { ...this.value, destructionEvidence: Object.freeze(structuredClone(evidence)) }; return this.move("DESTROYED", TECH_COPY_EVENT_IDS.DESTROY, command, evidence.evidenceIds); }
  private assertCompletion(command: TechCopyCommand, evidence: CustodyCompletionEvidence): void { if (evidence.completedByUserId !== command.actor.userId || evidence.completedAt !== command.occurredAt || evidence.pageCountReconciled !== this.value.print?.pageCount || !evidence.reason.trim() || evidence.evidenceIds.length === 0) fail("TECH_COPY_CUSTODY_EVIDENCE_INVALID", "All numbered pages, reason and append-only evidence are required."); }
  private withScope(scope: ControlledCopyRecipientScopeSnapshot): readonly ControlledCopyRecipientScopeSnapshot[] { return Object.freeze([...this.value.scopeRevalidations, Object.freeze(structuredClone(scope))]); }
  private requireRequester(actor: TechCopyActor): void { assertInternal(actor, TECH_COPY_PERMISSION_IDS.REQUEST); if (actor.userId !== this.value.request.requestedByUserId) fail("TECH_COPY_REQUESTER_REQUIRED", "Only the direct requester may submit."); }
  private guard(command: TechCopyCommand, states: readonly TechCopyState[]): void { if (this.value.optimisticVersion !== command.expectedVersion) fail("TECH_COPY_VERSION_CONFLICT", "Optimistic version conflict."); if (!states.includes(this.value.state)) fail("TECH_COPY_STATE_INVALID", `State ${this.value.state} cannot perform this transition.`); if (command.actor.kind === "VENDOR") fail("TECH_COPY_VENDOR_ACTION_DENIED", "Vendor render, print and custody actions are prohibited."); }
  private move(toState: TechCopyState, eventType: TechCopyCustodyEvent["eventType"], command: TechCopyCommand | Omit<TechCopyCommand, "expectedVersion">, evidenceIds: readonly Uuid[]): TechCopyMutation { const fromState = this.value.state; const event: TechCopyCustodyEvent = Object.freeze({ eventId: command.commandId, eventType, fromState, toState, actorUserId: command.actor.userId, occurredAt: command.occurredAt, evidenceIds: Object.freeze([...evidenceIds]) }); const expectedVersion = "expectedVersion" in command ? command.expectedVersion : 0 as Version; this.value = Object.freeze({ ...this.value, state: toState, optimisticVersion: (Number(this.value.optimisticVersion) + 1) as Version, custodyEvents: Object.freeze([...this.value.custodyEvents, event]), updatedAt: command.occurredAt }); return { expectedVersion, snapshot: this.snapshot(), custodyEvent: event, auditActionId: eventType as StableCode, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey }; }
  private record(fromState: undefined, toState: "REQUESTED", eventType: typeof TECH_COPY_EVENT_IDS.REQUEST, command: Omit<TechCopyCommand, "expectedVersion">, evidenceIds: readonly Uuid[]): TechCopyMutation { void fromState; void toState; const event: TechCopyCustodyEvent = Object.freeze({ eventId: command.commandId, eventType, toState: "REQUESTED", actorUserId: command.actor.userId, occurredAt: command.occurredAt, evidenceIds: Object.freeze([...evidenceIds]) }); this.value = Object.freeze({ ...this.value, optimisticVersion: 1 as Version, custodyEvents: Object.freeze([event]) }); return { expectedVersion: 0 as Version, snapshot: this.snapshot(), custodyEvent: event, auditActionId: eventType as StableCode, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey }; }
}

function assertRequest(value: ControlledCopyRequestSnapshot): void { const d = value.document, r = value.recipient; if (d.state !== "APPROVED" || !d.approvedAt || !d.sealedAt || d.securityLevel !== "L3" && d.securityLevel !== "L4" || d.versionNo < 1 || !d.projectId || !d.sourceAttachmentId || Number(d.sourceAttachmentRowVersion) < 0) fail("TECH_COPY_EXACT_APPROVED_DOCUMENT_REQUIRED", "Exact approved L3/L4 DocumentVersion and source tuple are required."); const reprintCoherent = Boolean(value.reprintOfCopyId) === Boolean(value.reprintReason?.trim()); if (!r.recipientUserId || !r.vendorId || !r.recipientDisplayName.trim() || !r.vendorDisplayName.trim() || !value.purpose.trim() || !value.copyNo.trim() || value.returnOrDestructionDueAt <= value.requestedAt || value.requestVersion !== 1 || value.requestSealedAt !== value.requestedAt || !reprintCoherent) fail("TECH_COPY_REQUEST_INVALID", "Exact recipient/vendor, purpose, unique copy number, sealed request, coherent reprint lineage and due time are required."); assertScope(value, value.initialScope, "REQUEST", value.requestedAt); }
function assertApproval(request: ControlledCopyRequestSnapshot, approval: CompletedControlledCopyApproval): void { if (approval.state !== "COMPLETED" || approval.subjectKind !== "TECHNICAL_DOCUMENT_COPY_REQUEST" || approval.technicalDocumentCopyId !== request.technicalDocumentCopyId || approval.requestVersion !== request.requestVersion || approval.requestChecksum !== request.requestChecksum || approval.requestSealedAt !== request.requestSealedAt || approval.documentVersionId !== request.document.documentVersionId || approval.documentVersionNo !== request.document.versionNo || approval.documentChecksum !== request.document.sealedSnapshotChecksum || approval.documentSealedAt !== request.document.sealedAt || approval.recipientUserId !== request.recipient.recipientUserId || approval.vendorId !== request.recipient.vendorId || approval.purposeHash !== request.purposeHash) fail("TECH_COPY_APPROVAL_SUBJECT_MISMATCH", "Approval must bind the exact request, document, recipient/vendor and purpose.");
  const director = approval.steps.filter((step) => step.positionId === "POSITION_LAB_DIRECTOR"); const representative = approval.steps.filter((step) => step.positionId === "POSITION_REPRESENTATIVE"); if (approval.steps.some((step) => !["POSITION_LAB_DIRECTOR", "POSITION_REPRESENTATIVE"].includes(step.positionId)) || director.length !== 1 || director[0]!.sequence !== 1 || director[0]!.completionMode !== "SEQUENTIAL" || director[0]!.participants.length !== 1 || director[0]!.participants[0]!.positionId !== "POSITION_LAB_DIRECTOR" || director[0]!.participants.filter((p) => p.actionId && p.approvedAt).length !== 1) fail("TECH_COPY_APPROVAL_LINE_INVALID", "A single completed Lab Director first step is required.");
  if (request.document.securityLevel === "L3" && representative.length !== 0 || request.document.securityLevel === "L4" && (representative.length !== 1 || representative[0]!.sequence !== 2 || representative[0]!.completionMode !== "ANY_ONE" || representative[0]!.participants.length !== 2 || representative[0]!.participants.some((p) => p.positionId !== "POSITION_REPRESENTATIVE") || representative[0]!.participants.filter((p) => p.actionId && p.approvedAt).length !== 1) || approval.steps.length !== (request.document.securityLevel === "L3" ? 1 : 2)) fail("TECH_COPY_APPROVAL_MATRIX_INVALID", "L3 requires Director only; L4 requires Director then one of two Representatives (ANY_ONE). "); const terminal = request.document.securityLevel === "L4" ? representative[0]!.participants.find((p) => p.actionId) : director[0]!.participants[0]; if (!terminal || terminal.actionId !== approval.terminalActionId || terminal.approvedAt !== approval.completedAt) fail("TECH_COPY_APPROVAL_TERMINAL_ACTION_INVALID", "Approval completion must be caused by the exact final required action."); }
function assertSnapshot(snapshot: TechnicalDocumentCopySnapshot): void { assertRequest(snapshot.request); if (snapshot.approval) assertApproval(snapshot.request, snapshot.approval); if (snapshot.state !== "REQUESTED" && snapshot.state !== "APPROVAL_PENDING" && !snapshot.approval) fail("TECH_COPY_APPROVAL_REQUIRED", "Approved lifecycle requires immutable approval evidence."); if (["RENDERED", "PRINTED", "HANDED_OVER", "RETURN_DUE", "RETURNED", "DESTROYED", "OVERDUE"].includes(snapshot.state) && !snapshot.render) fail("TECH_COPY_RENDER_REQUIRED", "Rendered lifecycle requires exact output evidence."); if (["PRINTED", "HANDED_OVER", "RETURN_DUE", "RETURNED", "DESTROYED", "OVERDUE"].includes(snapshot.state) && !snapshot.print) fail("TECH_COPY_PRINT_REQUIRED", "Printed lifecycle requires exact print evidence."); }
function assertScope(request: ControlledCopyRequestSnapshot, scope: ControlledCopyRecipientScopeSnapshot, action: ControlledCopyRecipientScopeSnapshot["action"], at: UtcInstant): void { const contractBound = request.document.contractId !== undefined; const contractMatches = contractBound ? scope.contractId === request.document.contractId && Boolean(scope.contractGrantId && scope.contractGrantVersion !== undefined) : scope.contractId === undefined && scope.contractGrantId === undefined && scope.contractGrantVersion === undefined; if (scope.action !== action || scope.recipientUserId !== request.recipient.recipientUserId || scope.vendorId !== request.recipient.vendorId || scope.projectId !== request.document.projectId || !scope.vendorMembershipId || !scope.projectGrantId || !contractMatches || scope.evidenceIds.length < (contractBound ? 3 : 2) || scope.evaluatedAt !== at || scope.validUntil <= at) fail("TECH_COPY_RECIPIENT_SCOPE_INVALID", "Active VendorMembership and exact Project grant are required; contract-bound copies additionally require the exact Contract grant."); }
function assertInternal(actor: TechCopyActor, permission: string): asserts actor is TechCopyActor & { userId: Uuid } { if (actor.kind !== "INTERNAL" || !actor.active || !actor.userId || !actor.permissionIds.includes(permission as StableCode)) fail("TECH_COPY_INTERNAL_PERMISSION_REQUIRED", `Active internal ${permission} permission is required.`); }
function assertSystem(actor: TechCopyActor, serviceId: NonNullable<TechCopyActor["serviceId"]>): void { if (actor.kind !== "SYSTEM" || !actor.active || actor.serviceId !== serviceId) fail("TECH_COPY_TRUSTED_SERVICE_REQUIRED", `Trusted ${serviceId} service is required.`); }
function fail(code: string, message: string): never { const error = new Error(message); error.name = code; throw error; }
