import { assertTrustedDeliveryAuthorization, type AuthorizedDeliveryRequest, type PrivateStoragePort, type PrivateUploadGrant, type ServerIssuedUploadIntent, type ShortLivedDelivery } from "@youone/core-file/public";
import type { Sha256, UtcInstant } from "@youone/shared-kernel/public";

export interface SupabasePrivateStorageClient { createSignedUploadToken(bucket:string,key:string,expiresInSeconds:number):Promise<string>; createSignedDownloadUrl(bucket:string,key:string,expiresInSeconds:number):Promise<string>; head(bucket:string,key:string):Promise<{mimeType:string;sizeBytes:number;sha256:Sha256}> }
export interface DeliveryAuditBoundary { audited<T>(input:{decisionId:string;attachmentId:string;granteeUserId:string;allowed:boolean;reasonCode:string;evidenceIds:readonly string[];obligations:readonly string[]},operation:()=>Promise<T>):Promise<T> }
export interface ReauthorizingDeliveryBroker { issue(input:{attachmentId:string;granteeUserId:string;authorizationDecisionId:string;expiresAt:UtcInstant;reauthorizeOnRedemption:true}):Promise<{redemptionEndpoint:string;oneTimeBrokerToken:string}> }
export class StorageContractError extends Error { constructor(readonly code:string){super(code);this.name="StorageContractError";} }
export class SupabasePrivateStorageAdapter implements PrivateStoragePort {
  constructor(private readonly client:SupabasePrivateStorageClient,private readonly privateBuckets:readonly string[],private readonly now:()=>UtcInstant,private readonly audit:DeliveryAuditBoundary,private readonly broker:ReauthorizingDeliveryBroker){}
  async createUploadGrant(request:ServerIssuedUploadIntent):Promise<PrivateUploadGrant>{this.guardPath(request.bucket,request.storageKey);const ttl=this.ttl(request.expiresAt);if(ttl<1||ttl>300)throw new StorageContractError("UPLOAD_TTL_INVALID");const opaqueUploadToken=await this.client.createSignedUploadToken(request.bucket,request.storageKey,ttl);return{attachmentId:request.attachmentId,provider:"SUPABASE_STORAGE",expiresAt:request.expiresAt,opaqueUploadToken};}
  async createAuthorizedDelivery(request:AuthorizedDeliveryRequest):Promise<ShortLivedDelivery>{const {attachment,authorization}=request;assertTrustedDeliveryAuthorization(authorization);const decisionId=authorization.authorizationDecisionId as string;const auditInput={decisionId,attachmentId:attachment.attachmentId as string,granteeUserId:authorization.granteeUserId as string,allowed:authorization.decision.allowed,reasonCode:authorization.decision.reasonCode as string,evidenceIds:authorization.evidenceIds as readonly string[],obligations:authorization.obligations as readonly string[]};return this.audit.audited(auditInput,async()=>{this.guardPath(attachment.bucket,attachment.storageKey);if(authorization.attachmentId!==attachment.attachmentId||authorization.action!=="technical_document.content.download"||this.now()>=authorization.validUntil)throw new StorageContractError("DELIVERY_AUTHORIZATION_STALE");if(!authorization.decision.allowed)throw new StorageContractError(authorization.decision.reasonCode);if(!Number.isInteger(request.requestedTtlSeconds)||request.requestedTtlSeconds<1||request.requestedTtlSeconds>authorization.decision.maxTtlSeconds||request.requestedTtlSeconds>300)throw new StorageContractError("DELIVERY_TTL_INVALID");const expiresAt=new Date(Date.parse(this.now())+request.requestedTtlSeconds*1000).toISOString() as UtcInstant;if(expiresAt>authorization.validUntil)throw new StorageContractError("DELIVERY_EXCEEDS_AUTHORIZATION_EXPIRY");const grant=await this.broker.issue({attachmentId:attachment.attachmentId as string,granteeUserId:authorization.granteeUserId as string,authorizationDecisionId:decisionId,expiresAt,reauthorizeOnRedemption:true});return{attachmentId:attachment.attachmentId,expiresAt,...grant};});}
  headObject(bucket:string,storageKey:string){this.guardPath(bucket,storageKey);return this.client.head(bucket,storageKey);}
  private guardPath(bucket:string,key:string){if(!this.privateBuckets.includes(bucket))throw new StorageContractError("PRIVATE_BUCKET_REQUIRED");if(!key.startsWith("private/")||key.includes("..")||key.includes("//"))throw new StorageContractError("STORAGE_KEY_INVALID");}
  private ttl(expiresAt:UtcInstant){return Math.floor((Date.parse(expiresAt)-Date.parse(this.now()))/1000);}
}
