import type { IdempotencyKey, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import { RND_LIFECYCLE_BLOCKED, RndProgram, type BudgetVersionSnapshot, type ExpenditureSnapshot, type ReportDeadlineSnapshot, type RndAuditObligation, type RndCommand, type RndEvidenceSnapshot, type RndMutation, type RndProgramSnapshot, type RndProjectLinkSnapshot, type RndRecordEvent } from "../domain/rnd.js";

export const RND_PERMISSION_IDS = Object.freeze({ PROGRAM_REGISTER: "rnd.program.register", PROGRAM_MANAGE: "rnd.program.manage", BUDGET_MANAGE: "rnd.budget.manage", EXPENDITURE_RECORD: "rnd.expenditure.record", EVIDENCE_RECORD: "rnd.evidence.record", DEADLINE_MANAGE: "rnd.deadline.manage", READ: "rnd.program.read" } as const);
export interface RndRepository { loadForUpdate(id: Uuid): Promise<RndProgramSnapshot | null>; insert(snapshot: RndProgramSnapshot): Promise<void>; save(snapshot: RndProgramSnapshot, expectedVersion: Version): Promise<boolean>; appendImmutableProjectLink(snapshot: RndProjectLinkSnapshot): Promise<void>; appendImmutableBudgetVersion(snapshot: BudgetVersionSnapshot): Promise<void>; appendImmutableExpenditure(snapshot: ExpenditureSnapshot): Promise<void>; appendImmutableEvidence(snapshot: RndEvidenceSnapshot): Promise<void>; appendImmutableDeadline(snapshot: ReportDeadlineSnapshot): Promise<void> }
export interface RndLinkValidationPort { assertProject(projectId: Uuid): Promise<void>; assertBudgetLine(input: { readonly budgetVersionId: Uuid; readonly budgetLineId: Uuid }): Promise<void>; assertExpenditureLinks(input: ExpenditureSnapshot): Promise<void>; assertEvidenceSubject(input: RndEvidenceSnapshot): Promise<void>; assertPrivateAttachment(input: RndEvidenceSnapshot): Promise<void> }
export interface RndEvidencePort { appendRecordVersion(input: { readonly rndProgramId: Uuid; readonly fromVersion: Version; readonly toVersion: Version; readonly eventType: StableCode; readonly occurredAt: UtcInstant }): Promise<void>; appendAudit(obligation: RndAuditObligation): Promise<void>; enqueue(event: RndRecordEvent): Promise<void> }
export interface DeadlineAlertSnapshot { readonly deadlineAlertId: Uuid; readonly rndProgramId: Uuid; readonly reportDeadlineId: Uuid; readonly alertPolicyVersionId: Uuid; readonly alertAt: UtcInstant; readonly idempotencyKey: IdempotencyKey; readonly channel: "IN_APP" | "EMAIL"; readonly recipientUserId: Uuid }
export interface DeadlineAlertRepository { insertIfAbsent(snapshot: DeadlineAlertSnapshot): Promise<"INSERTED" | "ALREADY_EXISTS"> }
export interface RndTransactionContext { readonly rndPrograms: RndRepository; readonly links: RndLinkValidationPort; readonly alerts: DeadlineAlertRepository; readonly evidence: RndEvidencePort }
export interface RndUnitOfWork { transact<T>(work: (context: RndTransactionContext) => Promise<T>): Promise<T> }
export class RndApplicationError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "RndApplicationError"; } }
async function appendEvidence(context: RndTransactionContext, mutation: RndMutation): Promise<void> { if (mutation.snapshot.version !== mutation.expectedVersion + 1) throw new RndApplicationError("RND_VERSION_NOT_DIRECT_NEXT" as StableCode, "R&D record version must increment exactly once."); await context.evidence.appendRecordVersion({ rndProgramId: mutation.snapshot.rndProgramId, fromVersion: mutation.expectedVersion, toVersion: mutation.snapshot.version, eventType: mutation.event.eventType, occurredAt: mutation.event.occurredAt }); await context.evidence.appendAudit(mutation.audit); await context.evidence.enqueue(mutation.event); }
async function save(context: RndTransactionContext, mutation: RndMutation): Promise<void> { if (mutation.expectedVersion === 0) { if (mutation.snapshot.version !== 1 || mutation.event.eventType !== "EVT-RND-REGISTER") throw new RndApplicationError("RND_REGISTER_VERSION_INVALID" as StableCode, "Registration must be version 0 to 1."); await context.rndPrograms.insert(mutation.snapshot); } else if (!await context.rndPrograms.save(mutation.snapshot, mutation.expectedVersion)) throw new RndApplicationError("RND_STALE_VERSION" as StableCode, "R&D optimistic lock lost."); if (mutation.immutableProjectLink) { await context.links.assertProject(mutation.immutableProjectLink.projectId); await context.rndPrograms.appendImmutableProjectLink(mutation.immutableProjectLink); } if (mutation.immutableBudgetVersion) await context.rndPrograms.appendImmutableBudgetVersion(mutation.immutableBudgetVersion); if (mutation.immutableExpenditure) { await context.links.assertBudgetLine({ budgetVersionId: mutation.immutableExpenditure.budgetVersionId, budgetLineId: mutation.immutableExpenditure.budgetLineId }); await context.links.assertExpenditureLinks(mutation.immutableExpenditure); await context.rndPrograms.appendImmutableExpenditure(mutation.immutableExpenditure); } if (mutation.immutableEvidence) { await context.links.assertEvidenceSubject(mutation.immutableEvidence); await context.links.assertPrivateAttachment(mutation.immutableEvidence); await context.rndPrograms.appendImmutableEvidence(mutation.immutableEvidence); } if (mutation.immutableDeadline) await context.rndPrograms.appendImmutableDeadline(mutation.immutableDeadline); await appendEvidence(context, mutation); }
export async function persistRndMutation(unitOfWork: RndUnitOfWork, mutation: RndMutation): Promise<void> { await unitOfWork.transact((context) => save(context, mutation)); }
export async function recordRndExpenditure(unitOfWork: RndUnitOfWork, input: { readonly rndProgramId: Uuid; readonly command: RndCommand; readonly expenditure: Omit<ExpenditureSnapshot, "rndProgramId" | "recordedByUserId" | "recordedAt" | "paymentInstructionCreated" | "accountingJournalCreated" | "rcmsWorkflowCloned"> }): Promise<RndProgramSnapshot> { return unitOfWork.transact(async (context) => { const snapshot = await context.rndPrograms.loadForUpdate(input.rndProgramId); if (!snapshot) throw new RndApplicationError("RND_PROGRAM_NOT_FOUND" as StableCode, "R&D Program was not found."); const mutation = RndProgram.restore(snapshot).recordExpenditure(input.command, input.expenditure); await save(context, mutation); return mutation.snapshot; }); }
export async function scheduleDeadlineAlerts(unitOfWork: RndUnitOfWork, alerts: readonly DeadlineAlertSnapshot[]): Promise<{ readonly inserted: number; readonly alreadyExists: number }> { return unitOfWork.transact(async (context) => { let inserted = 0; let alreadyExists = 0; const keys = new Set<string>(); for (const alert of alerts) { if (keys.has(alert.idempotencyKey)) throw new RndApplicationError("RND_ALERT_IDEMPOTENCY_DUPLICATE" as StableCode, "Alert batch idempotency keys must be unique."); keys.add(alert.idempotencyKey); const result = await context.alerts.insertIfAbsent(Object.freeze(structuredClone(alert))); if (result === "INSERTED") inserted += 1; else alreadyExists += 1; } return { inserted, alreadyExists }; }); }

export interface RndBudgetSummaryView { readonly currentBudgetVersionId?: string; readonly currentBudgetVersionNo?: number; readonly totalBudget: { readonly amount: string; readonly currency: string }; readonly totalExpenditure: { readonly amount: string; readonly currency: string }; readonly balance: { readonly amount: string; readonly currency: string }; readonly executionRate: string; readonly categoryTotals: readonly { readonly categoryCode: string; readonly budgetAmount: string; readonly expenditureAmount: string }[] }
export interface RndEvidenceSummaryView { readonly expenditureCount: number; readonly expenditureWithEvidenceCount: number; readonly evidenceCount: number; readonly missingEvidenceCount: number; readonly overdueEvidenceCount: number }
export interface RndDeadlineSummaryView { readonly total: number; readonly dueSoon: number; readonly overdue: number; readonly evidenceIncomplete: number }
export interface RndProgramSummaryView { readonly rndProgramId: string; readonly programCode: string; readonly title: string; readonly agreementFrom: string; readonly agreementTo: string; readonly managingAgency: string; readonly projectIds: readonly string[]; readonly budget: RndBudgetSummaryView; readonly evidence: RndEvidenceSummaryView; readonly deadlines: RndDeadlineSummaryView }
export interface RndProgramProjectionSource extends RndProgramSummaryView { readonly [key: string]: unknown }
export function projectRndProgramSummary(source: RndProgramProjectionSource): RndProgramSummaryView { return Object.freeze({ rndProgramId: source.rndProgramId, programCode: source.programCode, title: source.title, agreementFrom: source.agreementFrom, agreementTo: source.agreementTo, managingAgency: source.managingAgency, projectIds: Object.freeze([...source.projectIds]), budget: Object.freeze({ ...source.budget, totalBudget: Object.freeze({ ...source.budget.totalBudget }), totalExpenditure: Object.freeze({ ...source.budget.totalExpenditure }), balance: Object.freeze({ ...source.budget.balance }), categoryTotals: Object.freeze(source.budget.categoryTotals.map((item) => Object.freeze({ categoryCode: item.categoryCode, budgetAmount: item.budgetAmount, expenditureAmount: item.expenditureAmount }))) }), evidence: Object.freeze({ expenditureCount: source.evidence.expenditureCount, expenditureWithEvidenceCount: source.evidence.expenditureWithEvidenceCount, evidenceCount: source.evidence.evidenceCount, missingEvidenceCount: source.evidence.missingEvidenceCount, overdueEvidenceCount: source.evidence.overdueEvidenceCount }), deadlines: Object.freeze({ total: source.deadlines.total, dueSoon: source.deadlines.dueSoon, overdue: source.deadlines.overdue, evidenceIncomplete: source.deadlines.evidenceIncomplete }) }); }
export type RndProgramSummaryResult = { readonly availability: "AVAILABLE"; readonly summary: RndProgramSummaryView } | { readonly availability: "FORBIDDEN" | "NOT_FOUND"; readonly summary: null } | { readonly availability: "UNAVAILABLE"; readonly summary: null; readonly reason: "QUERY_ADAPTER_NOT_CONFIGURED" };
export type RndProgramListResult = { readonly availability: "AVAILABLE"; readonly items: readonly RndProgramSummaryView[] } | { readonly availability: "FORBIDDEN"; readonly items: readonly [] } | { readonly availability: "UNAVAILABLE"; readonly items: readonly []; readonly reason: "QUERY_ADAPTER_NOT_CONFIGURED" };
export interface RndQueryPort { listInternalSummaries(): Promise<RndProgramListResult>; getInternalSummary(rndProgramId: string): Promise<RndProgramSummaryResult>; getVendorSummary(_rndProgramId: string): Promise<{ readonly availability: "FORBIDDEN"; readonly summary: null }> }
export interface RndLifecycleCommandPort { execute(input: { readonly rndProgramId: string; readonly requestedCommand: "START" | "CLOSE" | "REOPEN" | "SETTLE" }): Promise<typeof RND_LIFECYCLE_BLOCKED> }
export class FailClosedRndLifecycleCommandPort implements RndLifecycleCommandPort { public async execute(): Promise<typeof RND_LIFECYCLE_BLOCKED> { return RND_LIFECYCLE_BLOCKED; } }
export const RND_FORBIDDEN_CAPABILITIES = Object.freeze(["RCMS_WORKFLOW", "BANK_TRANSFER", "PAYMENT_INSTRUCTION", "ACCOUNTING_JOURNAL", "VAT_REFUND_WORKFLOW", "VENDOR_RND_ACCESS"] as const);
