import { describe, expect, it, vi } from "vitest";
import type { ApprovalOutcomeInput } from "../../packages/core/approval/src/public.js";
import { PurchaseApprovalOutcomeService, persistPurchaseMutation, projectPurchaseDetail, revisePurchaseRequestAfterNegativeApproval, type PurchaseTransactionContext } from "../../packages/features/purchase/src/application/purchase-contracts.js";
import { PurchaseRequestApprovalSubjectAdapter, type PurchaseApprovalPolicySnapshot, type PurchaseRequestApprovalRecord } from "../../packages/features/purchase/src/approval/contracts.js";
import { PurchaseRequest, type PurchaseActorSnapshot, type PurchaseCommand, type PurchaseNegativeApprovalOutcomeSnapshot, type PurchaseSnapshot } from "../../packages/features/purchase/src/domain/purchase.js";
import { correlationId, idempotencyKey, money, sha256, stableCode, utcInstant, uuid, version } from "../../packages/shared-kernel/src/public.js";

const u = (n: number) => uuid(`92000000-0000-4000-8000-${String(n).padStart(12, "0")}`);
const requestId = u(1); const requestVersionId = u(2); const requesterId = u(3); const approverId = u(4); const sealedAt = utcInstant("2026-08-22T02:03:00Z"); const checksum = sha256("a".repeat(64));
let seq = 0;
const actor = (kind: PurchaseActorSnapshot["actorKind"], userId: typeof requesterId, ...permissions: string[]): PurchaseActorSnapshot => ({ actorKind: kind, userId, active: true, authorities: permissions.map(stableCode) });
function command(commandActor: PurchaseActorSnapshot, expectedVersion: number, at = `2026-08-22T02:${String(++seq).padStart(2, "0")}:00Z`): PurchaseCommand { return { actor: commandActor, expectedVersion: version(expectedVersion), at: utcInstant(at), eventId: u(100 + seq), correlationId: correlationId(`purchase-app-${seq}`), idempotencyKey: idempotencyKey(`purchase-app-${seq}`) }; }
function createCommand(commandActor: PurchaseActorSnapshot) { const { expectedVersion: _, ...rest } = command(commandActor, 0, "2026-08-22T02:00:00Z"); void _; return rest; }
function pending(): PurchaseSnapshot { const created = PurchaseRequest.create({ purchaseRequestId: requestId, requestNo: "PR-APP", requesterUserId: requesterId, purpose: "계측기 구매", lines: [{ purchaseRequestLineId: u(5), itemId: u(6), specification: "0.01mm", quantity: "1", unitCode: stableCode("EA"), expectedUnitPrice: money("900000", "KRW"), expectedAmount: money("900000", "KRW") }], quotations: [{ quotationId: u(7), supplierId: u(8), quotedAmount: money("900000", "KRW"), attachmentId: u(9), attachmentChecksum: sha256("b".repeat(64)), quotedAt: utcInstant("2026-08-22T02:00:00Z") }], projectIds: [u(10)], rndProgramIds: [], totalExpectedAmount: money("900000", "KRW") }, createCommand(actor("INTERNAL", requesterId, "purchase.request.create"))); const aggregate = PurchaseRequest.restore(created.snapshot); aggregate.draftRequest(command(actor("INTERNAL", requesterId), 1, "2026-08-22T02:01:00Z")); return aggregate.submit(command(actor("INTERNAL", requesterId), 2, String(sealedAt)), { purchaseRequestVersionId: requestVersionId, revisionNo: 1, checksum }).snapshot; }
function evidence() { return { appendTransition: vi.fn(async () => undefined), appendAudit: vi.fn(async () => undefined), enqueue: vi.fn(async () => undefined) }; }
function context(snapshot: PurchaseSnapshot, negative: PurchaseNegativeApprovalOutcomeSnapshot | null = null): PurchaseTransactionContext {
  return {
    purchases: { loadForUpdate: vi.fn(async () => snapshot), loadLatestNegativeApprovalOutcome: vi.fn(async () => negative), insert: vi.fn(), save: vi.fn(async () => true), appendImmutableRequestVersion: vi.fn(), appendImmutableApproval: vi.fn(), appendImmutableNegativeApprovalOutcome: vi.fn(), appendImmutableResolution: vi.fn(), appendImmutablePaymentFact: vi.fn(), appendImmutableReceipt: vi.fn(), appendImmutableReceiptOverage: vi.fn(), appendImmutableInspectionLink: vi.fn(), appendImmutableInspectionOutcome: vi.fn() },
    masters: { insertSupplier: vi.fn(), insertItem: vi.fn(), appendReviewedSupplierVendorLink: vi.fn() },
    links: { assertProjects: vi.fn(), assertRndPrograms: vi.fn(), assertItems: vi.fn(), assertSuppliers: vi.fn(), assertPrivateQuotationEvidence: vi.fn(), assertTypedInspection: vi.fn() }, evidence: evidence()
  };
}
const unit = (value: PurchaseTransactionContext) => ({ transact: async <T>(work: (context: PurchaseTransactionContext) => Promise<T>) => work(value) });
const policy: PurchaseApprovalPolicySnapshot = { presetVersionId: u(20), presetId: stableCode("PURCHASE-PRESET"), presetVersion: 1, presetChecksum: sha256("c".repeat(64)), tierId: "PURCHASE_UNDER_FIRST_THRESHOLD", approvalPolicyVersionId: u(21), approvalPolicyId: stableCode("PURCHASE-DIRECTOR"), approvalPolicyVersion: 1, approvalPolicyChecksum: sha256("d".repeat(64)), amountFacts: { vatInclusiveTotalBurden: money("900000", "KRW"), antiSplitCumulativeExposure: money("900000", "KRW"), policySelectionAmount: money("900000", "KRW"), antiSplitPolicyVersionId: u(22), antiSplitPolicyChecksum: sha256("e".repeat(64)), aggregationKeyHash: sha256("f".repeat(64)), aggregationWindowFrom: utcInstant("2026-08-01T00:00:00Z"), aggregationWindowTo: utcInstant("2026-09-01T00:00:00Z"), aggregationEvidenceIds: [u(23)], strengthenedLegalCheckRequired: false, strengthenedLegalCheckCompleted: false, legalChecklistEvidenceIds: [], factsChecksum: sha256("1".repeat(64)) }, selectedAt: sealedAt };
function record(amount = "900000"): PurchaseRequestApprovalRecord { return { purchaseRequestVersionId: requestVersionId, purchaseRequestId: requestId, revisionNo: 1, subjectVersion: version(1), sealedSnapshotChecksum: checksum, sealedAt, approvalState: "APPROVAL_PENDING", sealedVatInclusiveTotalBurden: money(amount, "KRW"), policySnapshot: policy, quotationRefs: [], evidenceRefs: [] }; }
function outcome(kind: "COMPLETED" | "REJECTED" = "COMPLETED"): ApprovalOutcomeInput { const approvalActor = { actorType: "USER" as const, accountKind: "INTERNAL" as const, authenticatedUserId: approverId, effectiveUserId: approverId, positionIds: [stableCode("POSITION_LAB_DIRECTOR")], roleIds: [] }; return { snapshot: { subject: { kind: "PURCHASE_REQUEST_VERSION", purchaseRequestVersionId: requestVersionId }, subjectVersion: version(1), checksum, sealedAt }, approvalInstanceId: u(30), approvalVersion: version(3), outcome: kind, provenance: { terminalAction: { actionId: u(kind === "COMPLETED" ? 31 : 32), kind: kind === "COMPLETED" ? "APPROVE" : "REJECT", at: utcInstant("2026-08-22T02:05:00Z"), actor: approvalActor, ...(kind === "REJECTED" ? { reasonCode: stableCode("PURCHASE-REVISION-REQUIRED") } : {}) }, ...(kind === "REJECTED" ? { terminalReasonCode: stableCode("PURCHASE-REVISION-REQUIRED") } : {}), actor: approvalActor, occurredAt: utcInstant("2026-08-22T02:05:00Z"), correlationId: correlationId(`purchase-${kind}`), idempotencyKey: idempotencyKey(`purchase-${kind}`) } }; }
function adapter(recordValue: PurchaseRequestApprovalRecord, service: PurchaseApprovalOutcomeService) { return new PurchaseRequestApprovalSubjectAdapter({ loadExact: async () => recordValue, loadPrevious: async () => null }, service, { resolve: async (input) => ({ approvalInstanceId: input.approvalInstanceId, approvalVersion: input.approvalVersion, approvalPolicyVersionId: policy.approvalPolicyVersionId, approvalPolicyChecksum: policy.approvalPolicyChecksum, approvalStepId: u(40), approvalParticipantId: u(41), approvalStepRole: "APPROVAL", approvalStepCompletionMode: "SEQUENTIAL", subject: { kind: "PURCHASE_REQUEST_VERSION", purchaseRequestVersionId: requestVersionId }, subjectVersion: version(1), subjectChecksum: checksum, subjectSealedAt: sealedAt, completedAt: input.provenance.occurredAt, officialApproverUserId: approverId, officialApproverPositionId: stableCode("POSITION_LAB_DIRECTOR") }) }); }

describe("Purchase application boundary", () => {
  it("accepts only a runtime-branded exact Approval outcome in the same UoW", async () => {
    const snapshot = pending(); const ctx = context(snapshot); const service = new PurchaseApprovalOutcomeService(unit(ctx));
    await adapter(record(), service).applyApprovalOutcome(outcome());
    expect(ctx.purchases.save).toHaveBeenCalledWith(expect.objectContaining({ state: "REQUEST_APPROVED", approval: expect.objectContaining({ purchaseRequestVersionId: requestVersionId, officialApproverUserId: approverId }) }), 3);
    expect(ctx.purchases.appendImmutableApproval).toHaveBeenCalledOnce(); expect(ctx.evidence.appendAudit).toHaveBeenCalledOnce(); expect(ctx.evidence.enqueue).toHaveBeenCalledOnce();
    await expect(service.applyApprovedOutcome({ decision: "APPROVED" } as never)).rejects.toMatchObject({ code: "PURCHASE_APPROVED_OUTCOME_NOT_TRUSTED" });
  });

  it("rejects a trusted Approval outcome when the VAT-inclusive amount snapshot differs", async () => {
    const ctx = context(pending()); const service = new PurchaseApprovalOutcomeService(unit(ctx));
    await expect(adapter(record("899999"), service).applyApprovalOutcome(outcome())).rejects.toMatchObject({ code: "PURCHASE_APPROVAL_POLICY_SNAPSHOT_INVALID" });
    expect(ctx.purchases.save).not.toHaveBeenCalled();
  });

  it("retains negative evidence with audit/outbox and permits only a direct changed replacement version", async () => {
    const snapshot = pending(); const ctx = context(snapshot); const service = new PurchaseApprovalOutcomeService(unit(ctx));
    await adapter(record(), service).applyApprovalOutcome(outcome("REJECTED"));
    expect(ctx.purchases.appendImmutableNegativeApprovalOutcome).toHaveBeenCalledWith(expect.objectContaining({ outcome: "REJECTED", purchaseRequestVersionId: requestVersionId }));
    expect(ctx.purchases.save).not.toHaveBeenCalled(); expect(ctx.evidence.enqueue).toHaveBeenCalledWith(expect.objectContaining({ payload: expect.objectContaining({ resolutionAllowed: false }) }));
    const negative = vi.mocked(ctx.purchases.appendImmutableNegativeApprovalOutcome).mock.calls[0]![0]; const revisionCtx = context(snapshot, negative);
    const result = await revisePurchaseRequestAfterNegativeApproval(unit(revisionCtx), { purchaseRequestId: requestId, command: command(actor("INTERNAL", requesterId, "purchase.request.manage"), 3, "2026-08-22T02:06:00Z"), revision: { purchaseRequestVersionId: u(50), revisionNo: 2, previousPurchaseRequestVersionId: requestVersionId, purpose: "계측기 구매(규격수정)", lines: snapshot.lines, quotations: snapshot.quotations, projectIds: snapshot.projectIds, rndProgramIds: snapshot.rndProgramIds, totalExpectedAmount: snapshot.totalExpectedAmount, checksum: sha256("9".repeat(64)) } });
    expect(result).toMatchObject({ state: "REQUEST_DRAFT", sealedRequestVersionId: u(50), sealedRequestVersionNo: 2, version: 4 });
    expect(revisionCtx.evidence.appendTransition).toHaveBeenCalledWith(expect.objectContaining({ eventType: "EVT-PURCHASE-REVISE-AFTER-NEGATIVE-APPROVAL", fromVersion: 3, toVersion: 4 }));
  });

  it("blocks raw approval persistence and strips malicious projection fields", async () => {
    const snapshot = pending(); const approved = PurchaseRequest.restore(snapshot).recordVerifiedApproval(command(actor("SYSTEM", approverId, "purchase.request.approve"), 3, "2026-08-22T02:05:00Z"), { approvalInstanceId: u(30), approvalVersion: version(3), approvalPolicyVersionId: u(21), approvalPolicyChecksum: policy.approvalPolicyChecksum, approvalStepId: u(40), approvalParticipantId: u(41), purchaseRequestVersionId: requestVersionId, subjectVersion: version(1), subjectChecksum: checksum, subjectSealedAt: sealedAt, completedAt: utcInstant("2026-08-22T02:05:00Z"), officialApproverUserId: approverId, officialApproverPositionId: stableCode("POSITION_LAB_DIRECTOR") });
    await expect(persistPurchaseMutation(unit(context(snapshot)), approved)).rejects.toMatchObject({ code: "PURCHASE_TRUSTED_APPROVAL_OUTCOME_REQUIRED" });
    const detail = projectPurchaseDetail({ purchaseRequestId: String(requestId), requestNo: "PR-APP", purpose: "계측기", state: "APPROVAL_PENDING", totalExpectedAmount: { amount: "900000", currency: "KRW" }, receivedLineCount: 0, totalLineCount: 1, inspectionStatus: "NOT_REQUESTED", nextAction: stableCode("purchase.request.manage"), lines: [], quotationSummaries: [], externalPaymentStatus: "NOT_RECORDED", bankAccount: "secret", approvalParticipants: ["secret"], internalNotes: "secret" });
    expect(detail).not.toHaveProperty("bankAccount"); expect(detail).not.toHaveProperty("approvalParticipants"); expect(detail).not.toHaveProperty("internalNotes");
  });
});
