import type { CorrelationId, IdempotencyKey, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import { nextVersion } from "@youone/shared-kernel/public";
import type { ContractActorSnapshot } from "./contract.js";

export const DELIVERABLE_MACHINE_ID = "SM-DELIVERABLE-V1" as const;
export const DELIVERABLE_EVENT_IDS = { DEFINED: "EVT-DELIVERABLE-DEFINE", STARTED: "EVT-DELIVERABLE-START", SUBMITTED: "EVT-DELIVERABLE-SUBMIT", REVIEW_STARTED: "EVT-DELIVERABLE-REVIEW-START", CORRECTION_REQUESTED: "EVT-DELIVERABLE-REQUEST-CORRECTION", ACCEPTED: "EVT-DELIVERABLE-ACCEPT", REJECTED: "EVT-DELIVERABLE-REJECT", SUPERSEDED: "EVT-DELIVERABLE-SUPERSEDE", CANCELLED: "EVT-DELIVERABLE-CANCEL" } as const;
export type DeliverableState = "EXPECTED" | "IN_PROGRESS" | "SUBMITTED" | "UNDER_REVIEW" | "CORRECTION_REQUIRED" | "ACCEPTED" | "REJECTED" | "SUPERSEDED" | "CANCELLED";

export interface DeliverableSnapshot { readonly deliverableId: Uuid; readonly contractId: Uuid; readonly contractMilestoneId: Uuid; readonly deliverableCode: string; readonly title: string; readonly assignedVendorId: Uuid; readonly state: DeliverableState; readonly submittedVersionId?: Uuid; readonly version: Version; readonly createdAt: UtcInstant; readonly updatedAt: UtcInstant }
export interface DeliverableManifestEntry { readonly manifestEntryId: Uuid; readonly deliverableVersionId: Uuid; readonly sequenceNo: number; readonly attachmentId: Uuid; readonly attachmentVersionId: Uuid; readonly contentHash: Sha256; readonly evidenceTypeCode: StableCode }
export interface DeliverableVersionSnapshot { readonly deliverableVersionId: Uuid; readonly deliverableId: Uuid; readonly versionNo: number; readonly manifestHash: Sha256; readonly manifestEntries: readonly DeliverableManifestEntry[]; readonly submitterUserId: Uuid; readonly createdAt: UtcInstant }
export interface DeliverableCommand { readonly actor: ContractActorSnapshot; readonly at: UtcInstant; readonly expectedVersion: Version; readonly eventId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey; readonly reason?: string }
export interface DeliverableMutation { readonly expectedVersion: Version; readonly snapshot: DeliverableSnapshot; readonly event: { readonly eventId: Uuid; readonly eventType: StableCode; readonly machineId: typeof DELIVERABLE_MACHINE_ID; readonly aggregateId: Uuid; readonly aggregateVersion: Version; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }; readonly audit: { readonly actionId: StableCode; readonly actor: ContractActorSnapshot; readonly deliverableId: Uuid; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly reason?: string } }

export class DeliverableDomainError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "DeliverableDomainError"; } }
function fail(code: string, message: string): never { throw new DeliverableDomainError(code as StableCode, message); }
function clone<T>(value: T): T { return structuredClone(value); }
function requireText(value: string, code: string): void { if (!value.trim()) fail(code, "A non-empty value is required."); }

export function createDeliverableVersion(input: DeliverableVersionSnapshot): DeliverableVersionSnapshot {
  if (!Number.isSafeInteger(input.versionNo) || input.versionNo <= 0) fail("DELIVERABLE_VERSION_NO_INVALID", "versionNo must be positive.");
  if (input.manifestEntries.length === 0) fail("DELIVERABLE_MANIFEST_EMPTY", "An exact non-empty evidence manifest is required.");
  const sequences = new Set<number>();
  for (const entry of input.manifestEntries) {
    if (entry.deliverableVersionId !== input.deliverableVersionId) fail("DELIVERABLE_MANIFEST_VERSION_MISMATCH", "Every manifest entry must bind the exact DeliverableVersion.");
    if (!Number.isSafeInteger(entry.sequenceNo) || entry.sequenceNo <= 0 || sequences.has(entry.sequenceNo)) fail("DELIVERABLE_MANIFEST_SEQUENCE_INVALID", "Manifest sequence numbers must be positive and unique.");
    sequences.add(entry.sequenceNo);
  }
  return Object.freeze({ ...clone(input), manifestEntries: Object.freeze(input.manifestEntries.map((entry) => Object.freeze(clone(entry)))) });
}

export class Deliverable {
  private constructor(private value: DeliverableSnapshot) {}
  public static define(input: Omit<DeliverableSnapshot, "state" | "submittedVersionId" | "version" | "createdAt" | "updatedAt">, command: Omit<DeliverableCommand, "expectedVersion">): DeliverableMutation { if (command.actor.actorKind !== "INTERNAL" || !command.actor.active || !command.actor.authorities.includes("CONTRACT_MANAGER")) fail("DELIVERABLE_MANAGER_REQUIRED", "Contract manager is required."); requireText(input.deliverableCode, "DELIVERABLE_CODE_REQUIRED"); requireText(input.title, "DELIVERABLE_TITLE_REQUIRED"); const snapshot = { ...clone(input), state: "EXPECTED" as const, version: 1 as Version, createdAt: command.at, updatedAt: command.at }; return Deliverable.mutation(snapshot, command, 0 as Version, DELIVERABLE_EVENT_IDS.DEFINED); }
  public static restore(snapshot: DeliverableSnapshot): Deliverable { return new Deliverable(clone(snapshot)); }
  public snapshot(): DeliverableSnapshot { return clone(this.value); }
  public start(command: DeliverableCommand): DeliverableMutation { this.guard(command, "EXPECTED"); this.requireAssignee(command.actor); return this.transition(command, "IN_PROGRESS", DELIVERABLE_EVENT_IDS.STARTED); }
  public submit(command: DeliverableCommand, exactVersion: DeliverableVersionSnapshot): DeliverableMutation { this.guard(command, "EXPECTED", "IN_PROGRESS", "CORRECTION_REQUIRED"); this.requireAssignee(command.actor); createDeliverableVersion(exactVersion); if (exactVersion.deliverableId !== this.value.deliverableId) fail("DELIVERABLE_VERSION_SUBJECT_MISMATCH", "Submitted version must bind the exact Deliverable."); this.value = { ...this.value, submittedVersionId: exactVersion.deliverableVersionId }; return this.transition(command, "SUBMITTED", DELIVERABLE_EVENT_IDS.SUBMITTED); }
  public startReview(command: DeliverableCommand): DeliverableMutation { this.guard(command, "SUBMITTED"); this.requireInternalReviewer(command.actor); return this.transition(command, "UNDER_REVIEW", DELIVERABLE_EVENT_IDS.REVIEW_STARTED); }
  public requestCorrection(command: DeliverableCommand): DeliverableMutation { this.guard(command, "UNDER_REVIEW"); this.requireInternalReviewer(command.actor); requireText(command.reason ?? "", "DELIVERABLE_CORRECTION_REASON_REQUIRED"); return this.transition(command, "CORRECTION_REQUIRED", DELIVERABLE_EVENT_IDS.CORRECTION_REQUESTED); }
  public accept(command: DeliverableCommand & { readonly authorizedInspectionResultId: Uuid }): DeliverableMutation { this.guard(command, "UNDER_REVIEW"); this.requireInternalReviewer(command.actor); return this.transition(command, "ACCEPTED", DELIVERABLE_EVENT_IDS.ACCEPTED); }
  public reject(command: DeliverableCommand): DeliverableMutation { this.guard(command, "UNDER_REVIEW"); this.requireInternalReviewer(command.actor); requireText(command.reason ?? "", "DELIVERABLE_REJECT_REASON_REQUIRED"); return this.transition(command, "REJECTED", DELIVERABLE_EVENT_IDS.REJECTED); }
  public supersede(command: DeliverableCommand & { readonly replacementVersionId: Uuid; readonly approvedChangeId: Uuid }): DeliverableMutation { this.guard(command, "ACCEPTED"); this.requireInternalReviewer(command.actor); return this.transition(command, "SUPERSEDED", DELIVERABLE_EVENT_IDS.SUPERSEDED); }
  public cancel(command: DeliverableCommand): DeliverableMutation { this.guard(command, "EXPECTED", "IN_PROGRESS", "SUBMITTED", "UNDER_REVIEW", "CORRECTION_REQUIRED"); if (command.actor.actorKind !== "INTERNAL" || !command.actor.active || !command.actor.authorities.includes("CONTRACT_MANAGER")) fail("DELIVERABLE_MANAGER_REQUIRED", "Contract manager is required."); requireText(command.reason ?? "", "DELIVERABLE_CANCEL_REASON_REQUIRED"); return this.transition(command, "CANCELLED", DELIVERABLE_EVENT_IDS.CANCELLED); }
  private guard(command: DeliverableCommand, ...states: readonly DeliverableState[]): void { if (command.expectedVersion !== this.value.version) fail("DELIVERABLE_STALE_VERSION", "Optimistic version mismatch."); if (!states.includes(this.value.state)) fail("DELIVERABLE_STATE_INVALID", `Operation is not allowed from ${this.value.state}.`); if (!command.actor.active) fail("DELIVERABLE_ACTOR_INACTIVE", "Inactive actors cannot change a Deliverable."); }
  private requireAssignee(actor: ContractActorSnapshot): void { if (actor.actorKind === "VENDOR") { if (actor.vendorId !== this.value.assignedVendorId || !actor.contractScopeId || actor.contractScopeContractId !== this.value.contractId) fail("DELIVERABLE_VENDOR_SCOPE_REQUIRED", "Only the exact assigned Vendor with exact ContractScope may act."); return; } if (actor.actorKind !== "INTERNAL" || !actor.userId) fail("DELIVERABLE_ASSIGNEE_REQUIRED", "An assigned active actor is required."); }
  private requireInternalReviewer(actor: ContractActorSnapshot): void { if (actor.actorKind !== "INTERNAL" || !actor.active || !actor.userId || (!actor.authorities.includes("DIRECTOR") && !actor.authorities.includes("CONTRACT_MANAGER"))) fail("DELIVERABLE_INTERNAL_REVIEWER_REQUIRED", "An authorized internal reviewer is required."); }
  private transition(command: DeliverableCommand, state: DeliverableState, eventType: string): DeliverableMutation { const expectedVersion = this.value.version; this.value = { ...this.value, state, version: nextVersion(this.value.version), updatedAt: command.at }; return Deliverable.mutation(this.value, command, expectedVersion, eventType); }
  private static mutation(snapshot: DeliverableSnapshot, command: Omit<DeliverableCommand, "expectedVersion">, expectedVersion: Version, eventType: string): DeliverableMutation { return { expectedVersion, snapshot: clone(snapshot), event: { eventId: command.eventId, eventType: eventType as StableCode, machineId: DELIVERABLE_MACHINE_ID, aggregateId: snapshot.deliverableId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey }, audit: { actionId: eventType as StableCode, actor: clone(command.actor), deliverableId: snapshot.deliverableId, occurredAt: command.at, correlationId: command.correlationId, ...(command.reason ? { reason: command.reason } : {}) } }; }
}
