import type { CorrelationId, IdempotencyKey, Money, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import { nextVersion } from "@youone/shared-kernel/public";

export const ECR_MACHINE_ID = "SM-ECR-V1" as const;
export const ECO_MACHINE_ID = "SM-ECO-V1" as const;
export type EcrState = "DRAFT" | "IMPACT_ANALYSIS" | "REVIEW_PENDING" | "APPROVAL_PENDING" | "APPROVED" | "REJECTED" | "CANCELLED" | "CONVERTED_TO_ECO";
export type EcoState = "DRAFT" | "APPROVAL_PENDING" | "RELEASED" | "IMPLEMENTING" | "VERIFICATION_PENDING" | "EFFECTIVE" | "CLOSED" | "SUSPENDED" | "CANCELLED";

export const ECR_EVENT_IDS = { CREATED: "EVT-ECR-CREATE", ANALYSIS_STARTED: "EVT-ECR-START-ANALYSIS", REVIEW_SUBMITTED: "EVT-ECR-SUBMIT-REVIEW", REVIEWED: "EVT-ECR-REVIEWED", APPROVED: "EVT-ECR-APPROVE", REJECTED: "EVT-ECR-REJECT", ECO_CREATED: "EVT-ECR-CREATE-ECO" } as const;
export const ECO_EVENT_IDS = { CREATED: "EVT-ECO-CREATE", SUBMITTED: "EVT-ECO-SUBMIT", RELEASED: "EVT-ECO-RELEASE", STARTED: "EVT-ECO-START", TARGET_IMPLEMENTED: "EVT-ECO-IMPLEMENT-TARGET", VERIFICATION_SUBMITTED: "EVT-ECO-SUBMIT-VERIFY", VERIFIED: "EVT-ECO-VERIFY", CLOSED: "EVT-ECO-CLOSE", SUSPENDED: "EVT-ECO-SUSPEND", RETROSPECTIVE_APPROVAL_RECORDED: "EVT-ECO-RECORD-RETROSPECTIVE-APPROVAL" } as const;
export type EcrTransitionEventId = Exclude<(typeof ECR_EVENT_IDS)[keyof typeof ECR_EVENT_IDS], "EVT-ECR-CREATE">;
export type EcoTransitionEventId = Exclude<(typeof ECO_EVENT_IDS)[keyof typeof ECO_EVENT_IDS], "EVT-ECO-CREATE" | "EVT-ECO-IMPLEMENT-TARGET" | "EVT-ECO-RECORD-RETROSPECTIVE-APPROVAL">;
export const ECR_TRANSITION_MAP: Readonly<Record<EcrTransitionEventId, { readonly from: readonly EcrState[]; readonly to: EcrState }>> = Object.freeze({
  "EVT-ECR-START-ANALYSIS": { from: ["DRAFT"], to: "IMPACT_ANALYSIS" }, "EVT-ECR-SUBMIT-REVIEW": { from: ["IMPACT_ANALYSIS"], to: "REVIEW_PENDING" }, "EVT-ECR-REVIEWED": { from: ["REVIEW_PENDING"], to: "APPROVAL_PENDING" }, "EVT-ECR-APPROVE": { from: ["APPROVAL_PENDING"], to: "APPROVED" }, "EVT-ECR-REJECT": { from: ["REVIEW_PENDING", "APPROVAL_PENDING"], to: "REJECTED" }, "EVT-ECR-CREATE-ECO": { from: ["APPROVED"], to: "CONVERTED_TO_ECO" }
});
export const ECO_TRANSITION_MAP: Readonly<Record<EcoTransitionEventId, { readonly from: readonly EcoState[]; readonly to: EcoState }>> = Object.freeze({
  "EVT-ECO-SUBMIT": { from: ["DRAFT"], to: "APPROVAL_PENDING" }, "EVT-ECO-RELEASE": { from: ["APPROVAL_PENDING"], to: "RELEASED" }, "EVT-ECO-START": { from: ["RELEASED"], to: "IMPLEMENTING" }, "EVT-ECO-SUBMIT-VERIFY": { from: ["IMPLEMENTING"], to: "VERIFICATION_PENDING" }, "EVT-ECO-VERIFY": { from: ["VERIFICATION_PENDING"], to: "EFFECTIVE" }, "EVT-ECO-CLOSE": { from: ["EFFECTIVE"], to: "CLOSED" }, "EVT-ECO-SUSPEND": { from: ["RELEASED", "IMPLEMENTING"], to: "SUSPENDED" }
});

export interface ChangeActorSnapshot { readonly actorKind: "INTERNAL" | "VENDOR" | "SYSTEM"; readonly userId?: Uuid; readonly vendorId?: Uuid; readonly active: boolean; readonly positionIds: readonly StableCode[]; readonly authorities: readonly StableCode[]; readonly projectScopeId?: Uuid; readonly projectScopeProjectId?: Uuid; readonly contractScopeId?: Uuid; readonly contractScopeContractId?: Uuid }
export interface ChangeCommand { readonly actor: ChangeActorSnapshot; readonly expectedVersion: Version; readonly at: UtcInstant; readonly eventId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }

export interface ImpactDimension { readonly effect: "NO_IMPACT" | "AFFECTED"; readonly analysis: string; readonly evidenceIds: readonly Uuid[] }
export interface CostImpact extends ImpactDimension { readonly estimatedDelta?: Money }
export interface ScheduleImpact extends ImpactDimension { readonly estimatedDaysDelta?: number }
export interface EcrImpactAnalysisSnapshot { readonly impactAnalysisId: Uuid; readonly changeRequestVersionId: Uuid; readonly cost: CostImpact; readonly schedule: ScheduleImpact; readonly quality: ImpactDimension; readonly safety: ImpactDimension; readonly security: ImpactDimension; readonly regulatory: ImpactDimension; readonly checksum: Sha256; readonly completedByUserId: Uuid; readonly completedAt: UtcInstant }
export interface OfficialChangeApprovalEvidence { readonly approvalInstanceId: Uuid; readonly approvalVersion: Version; readonly subjectVersionId: Uuid; readonly subjectVersion: Version; readonly subjectChecksum: Sha256; readonly subjectSealedAt: UtcInstant; readonly completedAt: UtcInstant; readonly officialApproverUserId: Uuid; readonly officialApproverPositionId: StableCode }
export interface EcrReviewSnapshot { readonly ecrReviewId: Uuid; readonly ecrId: Uuid; readonly changeRequestVersionId: Uuid; readonly ecrSealedVersion: Version; readonly sealedChecksum: Sha256; readonly sealedAt: UtcInstant; readonly reviewerUserId: Uuid; readonly reviewerPositionIds: readonly StableCode[]; readonly outcome: "REVIEW_ACCEPTED"; readonly comment: string; readonly evidenceIds: readonly Uuid[]; readonly reviewedAt: UtcInstant; readonly officialApproval: false }
export interface EcrSealedVersionSnapshot { readonly changeRequestVersionId: Uuid; readonly ecrId: Uuid; readonly subjectVersion: Version; readonly impactAnalysisId: Uuid; readonly checksum: Sha256; readonly sealedAt: UtcInstant }

export type ChangePriority = "LOW" | "NORMAL" | "HIGH" | "CRITICAL";
export interface EcrSnapshot { readonly ecrId: Uuid; readonly ecrNo: string; readonly title: string; readonly priority: ChangePriority; readonly projectId: Uuid; readonly contractId?: Uuid; readonly assignedVendorId?: Uuid; readonly linkedNcrIds: readonly Uuid[]; readonly rationale: string; readonly requestedChange: string; readonly state: EcrState; readonly impactAnalysis?: EcrImpactAnalysisSnapshot; readonly sealedSubjectVersionId?: Uuid; readonly sealedSubjectVersion?: Version; readonly sealedSubjectChecksum?: Sha256; readonly sealedSubjectAt?: UtcInstant; readonly officialApproval?: OfficialChangeApprovalEvidence; readonly convertedEcoId?: Uuid; readonly version: Version; readonly originatorUserId?: Uuid; readonly originatorVendorId?: Uuid; readonly createdAt: UtcInstant; readonly updatedAt: UtcInstant }

export type EcoTarget =
  | { readonly kind: "REQUIREMENT_REVISION"; readonly targetId: Uuid; readonly requirementId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid }
  | { readonly kind: "DOCUMENT_VERSION"; readonly targetId: Uuid; readonly documentId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid }
  | { readonly kind: "DELIVERABLE_VERSION"; readonly targetId: Uuid; readonly deliverableId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid }
  | { readonly kind: "INSPECTION_CHECKLIST_VERSION"; readonly targetId: Uuid; readonly inspectionChecklistId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid }
  | { readonly kind: "TEST_PLAN"; readonly targetId: Uuid; readonly testPlanId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid }
  | { readonly kind: "CONTRACT_VERSION"; readonly targetId: Uuid; readonly contractId: Uuid; readonly beforeRevisionId: Uuid; readonly afterRevisionId: Uuid };
export interface ContractChangeEffect { readonly changesScope: boolean; readonly changesAmount: boolean; readonly changesDeadline: boolean; readonly changesAcceptanceCriteria: boolean }
export interface ApprovedEcrOrigin { readonly kind: "APPROVED_ECR"; readonly ecrId: Uuid; readonly ecrVersion: Version; readonly ecrState: "APPROVED"; readonly sealedSubjectVersionId: Uuid; readonly sealedSubjectVersion: Version; readonly sealedSubjectChecksum: Sha256; readonly sealedSubjectAt: UtcInstant; readonly officialApproval: OfficialChangeApprovalEvidence }
export interface EmergencyChangeExceptionSnapshot { readonly kind: "EMERGENCY_EXCEPTION"; readonly emergencyExceptionId: Uuid; readonly policyVersionId: Uuid; readonly authorityCode: StableCode; readonly reason: string; readonly riskAssessment: string; readonly temporaryAuthorityAssignmentId: Uuid; readonly temporaryAuthorityUserId: Uuid; readonly authorizedByUserId: Uuid; readonly authorizedByPositionId: StableCode; readonly validFrom: UtcInstant; readonly validUntil: UtcInstant; readonly retrospectiveApprovalDueAt: UtcInstant; readonly evidenceIds: readonly Uuid[]; readonly recordedAt: UtcInstant }
export type EcoOrigin = ApprovedEcrOrigin | EmergencyChangeExceptionSnapshot;
export interface ExecutedSignedChangeContractSnapshot { readonly signedChangeSnapshotId: Uuid; readonly contractId: Uuid; readonly beforeContractVersionId: Uuid; readonly afterContractVersionId: Uuid; readonly signatureEvidenceAttachmentId: Uuid; readonly checksum: Sha256; readonly executedAt: UtcInstant }
export interface AppliedScopeSnapshot { readonly serialNumbers: readonly string[]; readonly lotNumbers: readonly string[]; readonly equipmentIds: readonly Uuid[] }
export interface EcoImplementationSnapshot { readonly ecoImplementationId: Uuid; readonly ecoId: Uuid; readonly targetId: Uuid; readonly beforeRevisionId: Uuid; readonly createdAfterRevisionId: Uuid; readonly implementedByUserId?: Uuid; readonly implementedByVendorId?: Uuid; readonly evidenceIds: readonly Uuid[]; readonly implementedAt: UtcInstant; readonly originalOverwritten: false }
export interface EcoVerificationRequirements { readonly retestRequired: boolean; readonly reinspectionRequired: boolean; readonly basis: string }
export interface EcoVerificationSnapshot { readonly ecoVerificationId: Uuid; readonly ecoId: Uuid; readonly verifierUserId: Uuid; readonly appliedScope: AppliedScopeSnapshot; readonly verifiedTargetIds: readonly Uuid[]; readonly evidenceIds: readonly Uuid[]; readonly retestEvidenceIds: readonly Uuid[]; readonly reinspectionEvidenceIds: readonly Uuid[]; readonly summary: string; readonly verifiedAt: UtcInstant }
export interface EcoSealedVersionSnapshot { readonly changeOrderVersionId: Uuid; readonly ecoId: Uuid; readonly subjectVersion: Version; readonly checksum: Sha256; readonly sealedAt: UtcInstant; readonly originKind: EcoOrigin["kind"]; readonly targetIds: readonly Uuid[] }
export interface EcoSnapshot { readonly ecoId: Uuid; readonly ecoNo: string; readonly title: string; readonly priority: ChangePriority; readonly projectId: Uuid; readonly contractId?: Uuid; readonly assignedVendorId?: Uuid; readonly linkedNcrIds: readonly Uuid[]; readonly origin: EcoOrigin; readonly targets: readonly EcoTarget[]; readonly contractChangeEffect: ContractChangeEffect; readonly verificationRequirements: EcoVerificationRequirements; readonly state: EcoState; readonly sealedDefinitionVersionId?: Uuid; readonly sealedDefinitionVersion?: Version; readonly sealedDefinitionChecksum?: Sha256; readonly sealedDefinitionAt?: UtcInstant; readonly releaseApproval?: OfficialChangeApprovalEvidence; readonly retrospectiveApproval?: OfficialChangeApprovalEvidence; readonly implementationCount: number; readonly implementedTargetIds: readonly Uuid[]; readonly implementationActorUserIds: readonly Uuid[]; readonly verification?: EcoVerificationSnapshot; readonly signedChangeContract?: ExecutedSignedChangeContractSnapshot; readonly version: Version; readonly createdAt: UtcInstant; readonly updatedAt: UtcInstant }

export interface ChangeDomainEvent { readonly eventId: Uuid; readonly eventType: StableCode; readonly machineId: typeof ECR_MACHINE_ID | typeof ECO_MACHINE_ID; readonly aggregateId: Uuid; readonly aggregateVersion: Version; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey; readonly payload: Readonly<Record<string, string | number | boolean | null>> }
export interface ChangeAuditObligation { readonly eventType: StableCode; readonly actor: ChangeActorSnapshot; readonly aggregateId: Uuid; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly reason?: string; readonly evidenceIds: readonly Uuid[] }
export interface EcrMutation { readonly expectedVersion: Version; readonly snapshot: EcrSnapshot; readonly event: ChangeDomainEvent; readonly audit: ChangeAuditObligation; readonly immutableImpactAnalysis?: EcrImpactAnalysisSnapshot; readonly immutableSealedVersion?: EcrSealedVersionSnapshot; readonly immutableReview?: EcrReviewSnapshot; readonly immutableOfficialApproval?: OfficialChangeApprovalEvidence }
export interface EcoMutation { readonly expectedVersion: Version; readonly snapshot: EcoSnapshot; readonly event: ChangeDomainEvent; readonly audit: ChangeAuditObligation; readonly immutableSealedVersion?: EcoSealedVersionSnapshot; readonly immutableImplementation?: EcoImplementationSnapshot; readonly immutableVerification?: EcoVerificationSnapshot; readonly immutableEmergencyException?: EmergencyChangeExceptionSnapshot; readonly immutableOfficialApproval?: OfficialChangeApprovalEvidence; readonly immutableRetrospectiveApproval?: OfficialChangeApprovalEvidence; readonly immutableSignedChangeContract?: ExecutedSignedChangeContractSnapshot }
export class ChangeDomainError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "ChangeDomainError"; } }
const fail = (code: string, message: string): never => { throw new ChangeDomainError(code as StableCode, message); };
const clone = <T>(value: T): T => structuredClone(value);
const immutable = <T>(value: T): T => Object.freeze(clone(value));
function text(value: string, code: string): void { if (!value.trim()) fail(code, "A non-empty value is required."); }
function evidence(ids: readonly Uuid[], code: string): void { if (ids.length === 0) fail(code, "Immutable evidence is required."); }
function has(actor: ChangeActorSnapshot, authority: string): boolean { return actor.active && actor.authorities.includes(authority as StableCode); }
function internal(actor: ChangeActorSnapshot, authority: string): Uuid { if (actor.actorKind !== "INTERNAL" || !actor.userId || !has(actor, authority)) return fail("CHANGE_INTERNAL_AUTHORITY_REQUIRED", `Active internal ${authority} authority is required.`); return actor.userId; }
function vendorScope(actor: ChangeActorSnapshot, projectId: Uuid, contractId: Uuid | undefined, assignedVendorId: Uuid | undefined): void { if (actor.actorKind !== "VENDOR" || !actor.active || actor.vendorId !== assignedVendorId || !actor.projectScopeId || actor.projectScopeProjectId !== projectId || (contractId !== undefined && (!actor.contractScopeId || actor.contractScopeContractId !== contractId))) fail("CHANGE_VENDOR_SCOPE_REQUIRED", "Exact active Vendor membership, ProjectScope, ContractScope and assignment are required."); }
function official(actor: ChangeActorSnapshot): Uuid { const userId = internal(actor, "change.request.approve"); if (actor.positionIds.includes("POSITION_SENIOR_RESEARCHER" as StableCode)) fail("CHANGE_OFFICIAL_APPROVER_INVALID", "Senior is review-only and cannot perform official change approval."); return userId; }
function validateImpactDimension(value: ImpactDimension, code: string): void { text(value.analysis, `${code}_ANALYSIS_REQUIRED`); if (value.effect !== "NO_IMPACT") evidence(value.evidenceIds, `${code}_EVIDENCE_REQUIRED`); }
function validateImpact(input: EcrImpactAnalysisSnapshot): void { validateImpactDimension(input.cost, "ECR_COST_IMPACT"); validateImpactDimension(input.schedule, "ECR_SCHEDULE_IMPACT"); validateImpactDimension(input.quality, "ECR_QUALITY_IMPACT"); validateImpactDimension(input.safety, "ECR_SAFETY_IMPACT"); validateImpactDimension(input.security, "ECR_SECURITY_IMPACT"); validateImpactDimension(input.regulatory, "ECR_REGULATORY_IMPACT"); if (input.cost.effect === "AFFECTED" && input.cost.estimatedDelta === undefined) fail("ECR_COST_DELTA_REQUIRED", "Affected cost requires an estimated delta and currency."); if (input.schedule.effect === "AFFECTED" && input.schedule.estimatedDaysDelta === undefined) fail("ECR_SCHEDULE_DELTA_REQUIRED", "Affected schedule requires an estimated day delta."); if (input.schedule.estimatedDaysDelta !== undefined && !Number.isSafeInteger(input.schedule.estimatedDaysDelta)) fail("ECR_SCHEDULE_DELTA_INVALID", "Schedule delta must be an integer number of days."); }
function uniqueTargets(targets: readonly EcoTarget[]): void { if (targets.length === 0) fail("ECO_TARGET_REQUIRED", "At least one exact typed change target is required."); const ids = new Set<string>(); for (const target of targets) { if (target.beforeRevisionId === target.afterRevisionId) fail("ECO_NEW_REVISION_REQUIRED", "Before and after immutable revision IDs must differ."); if (ids.has(target.targetId)) fail("ECO_TARGET_DUPLICATE", "Target IDs must be unique."); ids.add(target.targetId); } }

export class EngineeringChangeRequest {
  private constructor(private value: EcrSnapshot) {}
  public static create(input: Omit<EcrSnapshot, "state" | "impactAnalysis" | "sealedSubjectVersionId" | "sealedSubjectVersion" | "sealedSubjectChecksum" | "sealedSubjectAt" | "officialApproval" | "convertedEcoId" | "version" | "createdAt" | "updatedAt">, command: Omit<ChangeCommand, "expectedVersion">): EcrMutation {
    text(input.ecrNo, "ECR_NO_REQUIRED"); text(input.title, "ECR_TITLE_REQUIRED"); text(input.rationale, "ECR_RATIONALE_REQUIRED"); text(input.requestedChange, "ECR_CHANGE_REQUIRED");
    if (command.actor.actorKind === "VENDOR") { vendorScope(command.actor, input.projectId, input.contractId, input.assignedVendorId); if (!command.actor.userId || !has(command.actor, "change.request.create")) fail("CHANGE_VENDOR_ACTION_FORBIDDEN", "Vendor lacks an authenticated change.request.create actor."); if (input.originatorVendorId !== command.actor.vendorId || input.originatorUserId !== command.actor.userId) fail("ECR_ORIGINATOR_MISMATCH", "Trusted Vendor originator and membership must match the command actor."); }
    else { const userId = internal(command.actor, "change.request.create"); if (userId !== input.originatorUserId || input.originatorVendorId !== undefined) fail("ECR_ORIGINATOR_MISMATCH", "Trusted internal originator mismatch."); }
    const snapshot: EcrSnapshot = { ...clone(input), state: "DRAFT", version: 1 as Version, createdAt: command.at, updatedAt: command.at };
    return EngineeringChangeRequest.mutation(snapshot, command, 0 as Version, ECR_EVENT_IDS.CREATED, []);
  }
  public static restore(snapshot: EcrSnapshot): EngineeringChangeRequest { return new EngineeringChangeRequest(clone(snapshot)); }
  public snapshot(): EcrSnapshot { return clone(this.value); }
  public startAnalysis(command: ChangeCommand): EcrMutation { this.guard(command, ECR_EVENT_IDS.ANALYSIS_STARTED); this.originatorOrOwner(command.actor); return this.transition(command, ECR_EVENT_IDS.ANALYSIS_STARTED, []); }
  public submitReview(command: ChangeCommand, input: EcrImpactAnalysisSnapshot): EcrMutation { this.guard(command, ECR_EVENT_IDS.REVIEW_SUBMITTED); const userId = internal(command.actor, "change.impact.analyze"); if (userId !== input.completedByUserId) fail("ECR_IMPACT_ANALYST_MISMATCH", "Trusted impact analyst mismatch."); validateImpact(input); const sealedVersion = nextVersion(this.value.version); this.value = { ...this.value, impactAnalysis: immutable(input), sealedSubjectVersionId: input.changeRequestVersionId, sealedSubjectVersion: sealedVersion, sealedSubjectChecksum: input.checksum, sealedSubjectAt: command.at }; const mutation = this.transition(command, ECR_EVENT_IDS.REVIEW_SUBMITTED, [...input.cost.evidenceIds, ...input.schedule.evidenceIds, ...input.quality.evidenceIds, ...input.safety.evidenceIds, ...input.security.evidenceIds, ...input.regulatory.evidenceIds]); return { ...mutation, immutableImpactAnalysis: immutable(input), immutableSealedVersion: immutable({ changeRequestVersionId: input.changeRequestVersionId, ecrId: this.value.ecrId, subjectVersion: sealedVersion, impactAnalysisId: input.impactAnalysisId, checksum: input.checksum, sealedAt: command.at }) }; }
  public review(command: ChangeCommand, input: { readonly comment: string; readonly evidenceIds: readonly Uuid[] }): EcrMutation { this.guard(command, ECR_EVENT_IDS.REVIEWED); const reviewer = internal(command.actor, "change.request.review"); text(input.comment, "ECR_REVIEW_COMMENT_REQUIRED"); evidence(input.evidenceIds, "ECR_REVIEW_EVIDENCE_REQUIRED"); const sealedVersion = this.value.sealedSubjectVersion; const versionId = this.value.sealedSubjectVersionId; const checksum = this.value.sealedSubjectChecksum; const sealedAt = this.value.sealedSubjectAt; if (!sealedVersion || !versionId || !checksum || !sealedAt) fail("ECR_SEALED_SUBJECT_REQUIRED", "Exact sealed ECR is required."); const review: EcrReviewSnapshot = immutable({ ecrReviewId: command.eventId, ecrId: this.value.ecrId, changeRequestVersionId: versionId as Uuid, ecrSealedVersion: sealedVersion as Version, sealedChecksum: checksum as Sha256, sealedAt: sealedAt as UtcInstant, reviewerUserId: reviewer, reviewerPositionIds: [...command.actor.positionIds], outcome: "REVIEW_ACCEPTED", comment: input.comment, evidenceIds: [...input.evidenceIds], reviewedAt: command.at, officialApproval: false }); const mutation = this.transition(command, ECR_EVENT_IDS.REVIEWED, input.evidenceIds, input.comment); return { ...mutation, immutableReview: review }; }
  public approve(command: ChangeCommand, approval: OfficialChangeApprovalEvidence): EcrMutation { this.guard(command, ECR_EVENT_IDS.APPROVED); const approver = official(command.actor); if (approval.officialApproverUserId !== approver || approval.subjectVersionId !== this.value.sealedSubjectVersionId || approval.subjectVersion !== this.value.sealedSubjectVersion || approval.subjectChecksum !== this.value.sealedSubjectChecksum || approval.subjectSealedAt !== this.value.sealedSubjectAt) fail("ECR_EXACT_APPROVAL_REQUIRED", "Official approval must bind the exact sealed ECR and trusted approver."); this.value = { ...this.value, officialApproval: immutable(approval) }; const mutation = this.transition(command, ECR_EVENT_IDS.APPROVED, []); return { ...mutation, immutableOfficialApproval: immutable(approval) }; }
  public reject(command: ChangeCommand, input: { readonly reason: string; readonly evidenceIds: readonly Uuid[] }): EcrMutation { this.guard(command, ECR_EVENT_IDS.REJECTED); official(command.actor); text(input.reason, "ECR_REJECT_REASON_REQUIRED"); evidence(input.evidenceIds, "ECR_REJECT_EVIDENCE_REQUIRED"); return this.transition(command, ECR_EVENT_IDS.REJECTED, input.evidenceIds, input.reason); }
  public markEcoCreated(command: ChangeCommand, ecoId: Uuid): EcrMutation { this.guard(command, ECR_EVENT_IDS.ECO_CREATED); internal(command.actor, "change.order.manage"); if (!this.value.officialApproval) fail("ECR_APPROVAL_REQUIRED", "Only an approved ECR may be converted."); this.value = { ...this.value, convertedEcoId: ecoId }; return this.transition(command, ECR_EVENT_IDS.ECO_CREATED, []); }
  private originatorOrOwner(actor: ChangeActorSnapshot): void { if (actor.actorKind === "VENDOR") { vendorScope(actor, this.value.projectId, this.value.contractId, this.value.assignedVendorId); if (!has(actor, "change.request.create")) fail("CHANGE_VENDOR_ACTION_FORBIDDEN", "Vendor cannot start analysis."); } else if (actor.userId !== this.value.originatorUserId && !has(actor, "change.request.manage")) fail("ECR_ORIGINATOR_OR_OWNER_REQUIRED", "Originator or change owner required."); }
  private guard(command: ChangeCommand, eventId: EcrTransitionEventId): void { if (command.expectedVersion !== this.value.version) fail("ECR_STALE_VERSION", "Optimistic version mismatch."); if (!command.actor.active) fail("CHANGE_ACTOR_INACTIVE", "Inactive actor denied."); if (!ECR_TRANSITION_MAP[eventId].from.includes(this.value.state)) fail("ECR_TRANSITION_INVALID", `${eventId} is not allowed from ${this.value.state}.`); }
  private transition(command: ChangeCommand, eventId: EcrTransitionEventId, evidenceIds: readonly Uuid[], reason?: string): EcrMutation { const expected = this.value.version; this.value = { ...this.value, state: ECR_TRANSITION_MAP[eventId].to, version: nextVersion(this.value.version), updatedAt: command.at }; return EngineeringChangeRequest.mutation(this.value, command, expected, eventId, evidenceIds, reason); }
  private static mutation(snapshot: EcrSnapshot, command: Omit<ChangeCommand, "expectedVersion">, expectedVersion: Version, eventType: string, evidenceIds: readonly Uuid[], reason?: string): EcrMutation { return { expectedVersion, snapshot: immutable(snapshot), event: { eventId: command.eventId, eventType: eventType as StableCode, machineId: ECR_MACHINE_ID, aggregateId: snapshot.ecrId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, payload: { state: snapshot.state, projectId: snapshot.projectId, contractStateChanged: false, vendorResponsibilityWaived: false } }, audit: { eventType: eventType as StableCode, actor: clone(command.actor), aggregateId: snapshot.ecrId, occurredAt: command.at, correlationId: command.correlationId, ...(reason ? { reason } : {}), evidenceIds: [...evidenceIds] } }; }
}

export class EngineeringChangeOrder {
  private constructor(private value: EcoSnapshot) {}
  public static create(input: Omit<EcoSnapshot, "state" | "sealedDefinitionVersionId" | "sealedDefinitionVersion" | "sealedDefinitionChecksum" | "sealedDefinitionAt" | "releaseApproval" | "retrospectiveApproval" | "implementationCount" | "implementedTargetIds" | "implementationActorUserIds" | "verification" | "signedChangeContract" | "version" | "createdAt" | "updatedAt">, command: Omit<ChangeCommand, "expectedVersion">): EcoMutation {
    internal(command.actor, "change.order.manage"); text(input.ecoNo, "ECO_NO_REQUIRED"); text(input.title, "ECO_TITLE_REQUIRED"); text(input.verificationRequirements.basis, "ECO_VERIFICATION_BASIS_REQUIRED"); uniqueTargets(input.targets); if (input.origin.kind === "EMERGENCY_EXCEPTION") EngineeringChangeOrder.validateEmergency(input.origin, command.at); else EngineeringChangeOrder.validateApprovedEcrOrigin(input.origin);
    if (Object.values(input.contractChangeEffect).some(Boolean) && !input.contractId) fail("ECO_CONTRACT_LINK_REQUIRED", "A contract-affecting ECO requires an exact contract link.");
    if (Object.values(input.contractChangeEffect).some(Boolean) && !input.targets.some((target) => target.kind === "CONTRACT_VERSION")) fail("ECO_CONTRACT_TARGET_REQUIRED", "A contract-affecting ECO requires an exact CONTRACT_VERSION target.");
    const snapshot: EcoSnapshot = { ...clone(input), state: "DRAFT", implementationCount: 0, implementedTargetIds: [], implementationActorUserIds: [], version: 1 as Version, createdAt: command.at, updatedAt: command.at };
    return { ...EngineeringChangeOrder.mutation(snapshot, command, 0 as Version, ECO_EVENT_IDS.CREATED, input.origin.kind === "EMERGENCY_EXCEPTION" ? input.origin.evidenceIds : []), ...(input.origin.kind === "EMERGENCY_EXCEPTION" ? { immutableEmergencyException: immutable(input.origin) } : {}) };
  }
  public static restore(snapshot: EcoSnapshot): EngineeringChangeOrder { uniqueTargets(snapshot.targets); return new EngineeringChangeOrder(clone(snapshot)); }
  public snapshot(): EcoSnapshot { return clone(this.value); }
  public submit(command: ChangeCommand, input: { readonly changeOrderVersionId: Uuid; readonly checksum: Sha256 }): EcoMutation { this.guard(command, ECO_EVENT_IDS.SUBMITTED); internal(command.actor, "change.order.manage"); const sealedVersion = nextVersion(this.value.version); this.value = { ...this.value, sealedDefinitionVersionId: input.changeOrderVersionId, sealedDefinitionVersion: sealedVersion, sealedDefinitionChecksum: input.checksum, sealedDefinitionAt: command.at }; const mutation = this.transition(command, ECO_EVENT_IDS.SUBMITTED, []); return { ...mutation, immutableSealedVersion: immutable({ changeOrderVersionId: input.changeOrderVersionId, ecoId: this.value.ecoId, subjectVersion: sealedVersion, checksum: input.checksum, sealedAt: command.at, originKind: this.value.origin.kind, targetIds: this.value.targets.map((target) => target.targetId) }) }; }
  public release(command: ChangeCommand, approval?: OfficialChangeApprovalEvidence): EcoMutation { this.guard(command, ECO_EVENT_IDS.RELEASED); if (this.value.origin.kind === "EMERGENCY_EXCEPTION") { const userId = internal(command.actor, "change.order.emergency_release"); if (userId !== this.value.origin.temporaryAuthorityUserId || command.at < this.value.origin.validFrom || command.at >= this.value.origin.validUntil) fail("ECO_TEMPORARY_AUTHORITY_INVALID", "Emergency release requires the exact active temporary authority assignee."); return this.transition(command, ECO_EVENT_IDS.RELEASED, this.value.origin.evidenceIds, this.value.origin.reason); } const approver = official(command.actor); if (!approval || approval.officialApproverUserId !== approver || approval.subjectVersionId !== this.value.sealedDefinitionVersionId || approval.subjectVersion !== this.value.sealedDefinitionVersion || approval.subjectChecksum !== this.value.sealedDefinitionChecksum || approval.subjectSealedAt !== this.value.sealedDefinitionAt) fail("ECO_EXACT_APPROVAL_REQUIRED", "Release requires official approval of the exact sealed ECO definition."); this.value = { ...this.value, releaseApproval: immutable(approval) }; const mutation = this.transition(command, ECO_EVENT_IDS.RELEASED, []); return { ...mutation, immutableOfficialApproval: immutable(approval) }; }
  public recordRetrospectiveApproval(command: ChangeCommand, approval: OfficialChangeApprovalEvidence): EcoMutation { if (command.expectedVersion !== this.value.version) fail("ECO_STALE_VERSION", "Optimistic version mismatch."); const origin = this.value.origin; if (origin.kind !== "EMERGENCY_EXCEPTION") fail("ECO_NOT_EMERGENCY", "Retrospective approval applies only to emergency exceptions."); const emergencyOrigin = origin as EmergencyChangeExceptionSnapshot; if (this.value.retrospectiveApproval) fail("ECO_RETROSPECTIVE_APPROVAL_ALREADY_RECORDED", "Retrospective approval is immutable and may only be recorded once."); const approver = official(command.actor); if (approval.officialApproverUserId !== approver || approval.subjectVersionId !== this.value.sealedDefinitionVersionId || approval.subjectVersion !== this.value.sealedDefinitionVersion || approval.subjectChecksum !== this.value.sealedDefinitionChecksum || approval.subjectSealedAt !== this.value.sealedDefinitionAt || approval.completedAt > emergencyOrigin.retrospectiveApprovalDueAt) fail("ECO_RETROSPECTIVE_APPROVAL_INVALID", "Retrospective approval must bind the exact emergency ECO definition and complete by its deadline."); const expected = this.value.version; this.value = { ...this.value, retrospectiveApproval: immutable(approval), version: nextVersion(this.value.version), updatedAt: command.at }; const mutation = EngineeringChangeOrder.mutation(this.value, command, expected, ECO_EVENT_IDS.RETROSPECTIVE_APPROVAL_RECORDED, emergencyOrigin.evidenceIds); return { ...mutation, immutableRetrospectiveApproval: immutable(approval) }; }
  public start(command: ChangeCommand): EcoMutation { this.guard(command, ECO_EVENT_IDS.STARTED); this.implementer(command.actor); return this.transition(command, ECO_EVENT_IDS.STARTED, []); }
  public recordImplementation(command: ChangeCommand, input: Omit<EcoImplementationSnapshot, "ecoId" | "implementedByUserId" | "implementedByVendorId" | "implementedAt" | "originalOverwritten">): EcoMutation { if (command.expectedVersion !== this.value.version || this.value.state !== "IMPLEMENTING") fail("ECO_IMPLEMENTATION_STATE_INVALID", "Implementation record requires current IMPLEMENTING version."); const actor = this.implementer(command.actor); const target = this.value.targets.find((item) => item.targetId === input.targetId); if (!target || target.beforeRevisionId !== input.beforeRevisionId || target.afterRevisionId !== input.createdAfterRevisionId) fail("ECO_IMPLEMENTATION_TARGET_MISMATCH", "Implementation must create the exact new target version without overwriting the original."); if (this.value.implementedTargetIds.includes(input.targetId)) fail("ECO_TARGET_ALREADY_IMPLEMENTED", "Each exact target receives one immutable implementation record."); evidence(input.evidenceIds, "ECO_IMPLEMENTATION_EVIDENCE_REQUIRED"); const implementation: EcoImplementationSnapshot = immutable({ ...clone(input), ecoId: this.value.ecoId, implementedByUserId: actor, ...(command.actor.actorKind === "VENDOR" ? { implementedByVendorId: command.actor.vendorId } : {}), implementedAt: command.at, originalOverwritten: false }); const expected = this.value.version; const actors = !this.value.implementationActorUserIds.includes(actor) ? [...this.value.implementationActorUserIds, actor] : this.value.implementationActorUserIds; this.value = { ...this.value, implementationCount: this.value.implementationCount + 1, implementedTargetIds: [...this.value.implementedTargetIds, input.targetId], implementationActorUserIds: actors, version: nextVersion(this.value.version), updatedAt: command.at }; return { ...EngineeringChangeOrder.mutation(this.value, command, expected, ECO_EVENT_IDS.TARGET_IMPLEMENTED, input.evidenceIds), immutableImplementation: implementation }; }
  public submitVerification(command: ChangeCommand, evidenceIds: readonly Uuid[]): EcoMutation { this.guard(command, ECO_EVENT_IDS.VERIFICATION_SUBMITTED); this.implementer(command.actor); evidence(evidenceIds, "ECO_IMPLEMENTATION_EVIDENCE_REQUIRED"); if (this.value.implementedTargetIds.length !== this.value.targets.length || this.value.targets.some((target) => !this.value.implementedTargetIds.includes(target.targetId))) fail("ECO_IMPLEMENTATION_INCOMPLETE", "Every exact target requires a retained implementation record."); return this.transition(command, ECO_EVENT_IDS.VERIFICATION_SUBMITTED, evidenceIds); }
  public verify(command: ChangeCommand, input: { readonly verification: Omit<EcoVerificationSnapshot, "ecoId" | "verifierUserId" | "verifiedAt">; readonly signedChangeContract?: ExecutedSignedChangeContractSnapshot }): EcoMutation { this.guard(command, ECO_EVENT_IDS.VERIFIED); const verifier = internal(command.actor, "change.order.verify"); if (this.value.implementationActorUserIds.includes(verifier)) fail("ECO_SELF_VERIFICATION_FORBIDDEN", "An implementation actor cannot verify the ECO."); text(input.verification.summary, "ECO_VERIFICATION_SUMMARY_REQUIRED"); evidence(input.verification.evidenceIds, "ECO_VERIFICATION_EVIDENCE_REQUIRED"); if (this.value.verificationRequirements.retestRequired) evidence(input.verification.retestEvidenceIds, "ECO_RETEST_EVIDENCE_REQUIRED"); if (this.value.verificationRequirements.reinspectionRequired) evidence(input.verification.reinspectionEvidenceIds, "ECO_REINSPECTION_EVIDENCE_REQUIRED"); const scope = input.verification.appliedScope; if (scope.serialNumbers.length + scope.lotNumbers.length + scope.equipmentIds.length === 0) fail("ECO_APPLIED_SCOPE_REQUIRED", "Exact serial, lot or equipment applied scope is required."); if (new Set(input.verification.verifiedTargetIds).size !== this.value.targets.length || this.value.targets.some((target) => !input.verification.verifiedTargetIds.includes(target.targetId))) fail("ECO_TARGET_VERIFICATION_INCOMPLETE", "Every exact target requires verification."); if (this.value.origin.kind === "EMERGENCY_EXCEPTION" && (!this.value.retrospectiveApproval || this.value.retrospectiveApproval.completedAt > this.value.origin.retrospectiveApprovalDueAt)) fail("ECO_RETROSPECTIVE_APPROVAL_REQUIRED", "Emergency ECO requires on-time retrospective approval before effectiveness."); const changesContract = Object.values(this.value.contractChangeEffect).some(Boolean); if (changesContract) EngineeringChangeOrder.validateSignedChange(input.signedChangeContract, this.value); const verification: EcoVerificationSnapshot = immutable({ ...clone(input.verification), ecoId: this.value.ecoId, verifierUserId: verifier, verifiedAt: command.at }); this.value = { ...this.value, verification, ...(input.signedChangeContract ? { signedChangeContract: immutable(input.signedChangeContract) } : {}) }; const mutation = this.transition(command, ECO_EVENT_IDS.VERIFIED, [...input.verification.evidenceIds, ...input.verification.retestEvidenceIds, ...input.verification.reinspectionEvidenceIds]); return { ...mutation, immutableVerification: verification, ...(input.signedChangeContract ? { immutableSignedChangeContract: immutable(input.signedChangeContract) } : {}) }; }
  public close(command: ChangeCommand, evidenceIds: readonly Uuid[]): EcoMutation { this.guard(command, ECO_EVENT_IDS.CLOSED); internal(command.actor, "change.order.manage"); evidence(evidenceIds, "ECO_CLOSE_EVIDENCE_REQUIRED"); if (!this.value.verification) fail("ECO_VERIFICATION_REQUIRED", "Retained independent verification is required."); return this.transition(command, ECO_EVENT_IDS.CLOSED, evidenceIds); }
  public suspend(command: ChangeCommand, input: { readonly reason: string; readonly evidenceIds: readonly Uuid[] }): EcoMutation { this.guard(command, ECO_EVENT_IDS.SUSPENDED); internal(command.actor, "change.order.manage"); text(input.reason, "ECO_SUSPEND_REASON_REQUIRED"); evidence(input.evidenceIds, "ECO_SUSPEND_EVIDENCE_REQUIRED"); return this.transition(command, ECO_EVENT_IDS.SUSPENDED, input.evidenceIds, input.reason); }
  private implementer(actor: ChangeActorSnapshot): Uuid { if (actor.actorKind === "VENDOR") { vendorScope(actor, this.value.projectId, this.value.contractId, this.value.assignedVendorId); const userId = actor.userId; if (!userId || !has(actor, "change.order.implement")) fail("CHANGE_VENDOR_ACTION_FORBIDDEN", "Vendor lacks an authenticated ECO implementation actor or authority."); return userId as Uuid; } return internal(actor, "change.order.implement"); }
  private guard(command: ChangeCommand, eventId: EcoTransitionEventId): void { if (command.expectedVersion !== this.value.version) fail("ECO_STALE_VERSION", "Optimistic version mismatch."); if (!command.actor.active) fail("CHANGE_ACTOR_INACTIVE", "Inactive actor denied."); if (!ECO_TRANSITION_MAP[eventId].from.includes(this.value.state)) fail("ECO_TRANSITION_INVALID", `${eventId} is not allowed from ${this.value.state}.`); }
  private transition(command: ChangeCommand, eventId: EcoTransitionEventId, evidenceIds: readonly Uuid[], reason?: string): EcoMutation { const expected = this.value.version; this.value = { ...this.value, state: ECO_TRANSITION_MAP[eventId].to, version: nextVersion(this.value.version), updatedAt: command.at }; return EngineeringChangeOrder.mutation(this.value, command, expected, eventId, evidenceIds, reason); }
  private static validateApprovedEcrOrigin(origin: ApprovedEcrOrigin): void { const approval = origin.officialApproval; if (origin.ecrState !== "APPROVED" || approval.subjectVersionId !== origin.sealedSubjectVersionId || approval.subjectVersion !== origin.sealedSubjectVersion || approval.subjectChecksum !== origin.sealedSubjectChecksum || approval.subjectSealedAt !== origin.sealedSubjectAt) fail("ECO_APPROVED_ECR_ORIGIN_INVALID", "Standard ECO requires the exact immutable approved ECR version/checksum/sealedAt."); }
  private static validateEmergency(origin: EmergencyChangeExceptionSnapshot, at: UtcInstant): void { text(String(origin.policyVersionId), "ECO_EMERGENCY_POLICY_REQUIRED"); text(String(origin.authorityCode), "ECO_EMERGENCY_AUTHORITY_CODE_REQUIRED"); text(origin.reason, "ECO_EMERGENCY_REASON_REQUIRED"); text(origin.riskAssessment, "ECO_EMERGENCY_RISK_REQUIRED"); evidence(origin.evidenceIds, "ECO_EMERGENCY_EVIDENCE_REQUIRED"); if (origin.validFrom > at || at >= origin.validUntil || origin.retrospectiveApprovalDueAt <= at) fail("ECO_EMERGENCY_AUTHORITY_INVALID", "Emergency temporary authority must be active and retrospective approval due must be future."); }
  private static validateSignedChange(snapshot: ExecutedSignedChangeContractSnapshot | undefined, eco: EcoSnapshot): void { if (!snapshot || !eco.contractId || snapshot.contractId !== eco.contractId || snapshot.beforeContractVersionId === snapshot.afterContractVersionId || !eco.targets.some((target) => target.kind === "CONTRACT_VERSION" && target.beforeRevisionId === snapshot.beforeContractVersionId && target.afterRevisionId === snapshot.afterContractVersionId)) fail("ECO_SIGNED_CHANGE_CONTRACT_REQUIRED", "Contract effect requires an executed signed exact change-contract snapshot."); }
  private static mutation(snapshot: EcoSnapshot, command: Omit<ChangeCommand, "expectedVersion">, expectedVersion: Version, eventType: string, evidenceIds: readonly Uuid[], reason?: string): EcoMutation { return { expectedVersion, snapshot: immutable(snapshot), event: { eventId: command.eventId, eventType: eventType as StableCode, machineId: ECO_MACHINE_ID, aggregateId: snapshot.ecoId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, payload: { state: snapshot.state, projectId: snapshot.projectId, targetCount: snapshot.targets.length, emergency: snapshot.origin.kind === "EMERGENCY_EXCEPTION", contractStateChanged: false, vendorResponsibilityWaived: false } }, audit: { eventType: eventType as StableCode, actor: clone(command.actor), aggregateId: snapshot.ecoId, occurredAt: command.at, correlationId: command.correlationId, ...(reason ? { reason } : {}), evidenceIds: [...evidenceIds] } }; }
}
