import type { CorrelationId, IdempotencyKey, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";
import {assertTrustedActorContext,assertTrustedResourceContext,AuthorizationService,type TrustedActorContext,type TrustedResourceContext} from "@youone/core-authorization/public";
export type FileSecurityLevel = "L1"|"L2"|"L3"|"L4";
export type AttachmentState = "UPLOAD_INTENDED"|"UPLOADED"|"SCANNING"|"AVAILABLE"|"QUARANTINED"|"REJECTED";
export interface AttachmentSnapshot { readonly attachmentId: Uuid; readonly state: AttachmentState; readonly version: Version; readonly storageProvider: "SUPABASE_STORAGE"; readonly storageKey: string; readonly bucket: string; readonly declaredMimeType: string; readonly verifiedMimeType?: string;readonly detectedMimeType?:string; readonly declaredSizeBytes: number; readonly verifiedSizeBytes?: number; readonly expectedSha256: Sha256; readonly verifiedSha256?: Sha256; readonly securityLevel: FileSecurityLevel; readonly createdBy: Uuid; readonly createdAt: UtcInstant; readonly intentExpiresAt: UtcInstant;readonly scanEvidenceId?:Uuid;readonly scannerVersion?:StableCode; readonly quarantineReason?: StableCode }
export interface FileCommand { readonly actorUserId: Uuid; readonly actorKind:"INTERNAL"|"SYSTEM"; readonly at: UtcInstant; readonly expectedVersion: Version; readonly eventId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }
export interface FileMutation { readonly expectedVersion: Version; readonly snapshot: AttachmentSnapshot; readonly auditEvent: StableCode }
export class FileDomainError extends Error { constructor(readonly code: StableCode, message:string){super(message);this.name="FileDomainError";} }
const fail=(code:string,message:string):never=>{throw new FileDomainError(code as StableCode,message);};
const allowedMime = new Set(["application/pdf","image/png","image/jpeg","text/plain","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]);
export class Attachment {
  private constructor(private value: AttachmentSnapshot) {}
  static createIntent(input: Omit<AttachmentSnapshot,"state"|"version"|"verifiedMimeType"|"verifiedSizeBytes"|"verifiedSha256"|"detectedMimeType"|"scanEvidenceId"|"scannerVersion"|"quarantineReason">): Attachment { if (!input.storageKey.startsWith("private/") || input.storageKey.includes("..")) fail("FILE_STORAGE_KEY_INVALID","Server-issued private storage key required."); if (!allowedMime.has(input.declaredMimeType)) fail("FILE_MIME_NOT_ALLOWED","MIME type is not allowed."); if (!Number.isSafeInteger(input.declaredSizeBytes)||input.declaredSizeBytes<1||input.declaredSizeBytes>50_000_000) fail("FILE_SIZE_INVALID","File exceeds the 50MB P0 limit."); if (input.intentExpiresAt<=input.createdAt) fail("FILE_INTENT_EXPIRY_INVALID","Intent must expire after creation."); return new Attachment({...structuredClone(input),state:"UPLOAD_INTENDED",version:0 as Version}); }
  static restore(snapshot:AttachmentSnapshot):Attachment{if(snapshot.state==="AVAILABLE"&&(!snapshot.verifiedMimeType||!snapshot.detectedMimeType||snapshot.verifiedMimeType!==snapshot.detectedMimeType||snapshot.verifiedSizeBytes!==snapshot.declaredSizeBytes||snapshot.verifiedSha256!==snapshot.expectedSha256||!snapshot.scanEvidenceId||!snapshot.scannerVersion))fail("FILE_AVAILABLE_EVIDENCE_REQUIRED","AVAILABLE is the persisted result of a CLEAN scan and requires exact MIME, size, checksum, and scanner evidence.");return new Attachment(structuredClone(snapshot));}
  snapshot():AttachmentSnapshot{return structuredClone(this.value);}
  uploadVerified(command:FileCommand,actual:{intentOwnerUserId:Uuid;mimeType:string;sizeBytes:number;sha256:Sha256;headEvidenceId:Uuid}):FileMutation{this.guard(command,"UPLOAD_INTENDED");if(command.actorKind!=="SYSTEM"||actual.intentOwnerUserId!==this.value.createdBy)fail("FILE_STORAGE_VERIFIER_REQUIRED","Trusted FILE_INGEST worker and original intent evidence required.");if(command.at>=this.value.intentExpiresAt)fail("FILE_UPLOAD_INTENT_EXPIRED","Upload intent expired.");return this.change(command,{...this.value,state:"UPLOADED",verifiedMimeType:actual.mimeType,verifiedSizeBytes:actual.sizeBytes,verifiedSha256:actual.sha256},"AUDIT.FILE.UPLOADED");}
  beginScan(command:FileCommand):FileMutation{this.guard(command,"UPLOADED");if(command.actorKind!=="SYSTEM")fail("FILE_SCANNER_SYSTEM_REQUIRED","Only trusted scanner worker may start scan.");return this.change(command,{...this.value,state:"SCANNING"},"AUDIT.FILE.SCANNING");}
  scanCompleted(command:FileCommand,result:{clean:boolean;detectedMimeType:string;scanEvidenceId:Uuid;scannerVersion:StableCode;reason?:StableCode}):FileMutation{this.guard(command,"SCANNING");if(command.actorKind!=="SYSTEM")fail("FILE_SCANNER_SYSTEM_REQUIRED","Only trusted FILE_SCANNER worker may complete scan.");const evidence={detectedMimeType:result.detectedMimeType,scanEvidenceId:result.scanEvidenceId,scannerVersion:result.scannerVersion};if(this.value.verifiedMimeType!==this.value.declaredMimeType||this.value.verifiedSizeBytes!==this.value.declaredSizeBytes||this.value.verifiedSha256!==this.value.expectedSha256||result.detectedMimeType!==this.value.verifiedMimeType)return this.change(command,{...this.value,...evidence,state:"QUARANTINED",quarantineReason:"FILE_METADATA_OR_SIGNATURE_MISMATCH" as StableCode},"AUDIT.FILE.QUARANTINED");if(result.clean)return this.change(command,{...this.value,...evidence,state:"AVAILABLE"},"AUDIT.FILE.AVAILABLE");return this.change(command,{...this.value,...evidence,state:"QUARANTINED",quarantineReason:result.reason??("FILE_MALWARE_SUSPECTED" as StableCode)},"AUDIT.FILE.QUARANTINED");}
  private guard(command:FileCommand,state:AttachmentState){if(command.expectedVersion!==this.value.version)fail("FILE_STALE_VERSION","Optimistic conflict.");if(this.value.state!==state)fail("FILE_STATE_INVALID",`Expected ${state}.`);}
  private change(command:FileCommand,next:AttachmentSnapshot,auditEvent:string):FileMutation{this.value={...structuredClone(next),version:(Number(this.value.version)+1) as Version};return{expectedVersion:command.expectedVersion,snapshot:this.snapshot(),auditEvent:auditEvent as StableCode};}
}
export interface DeliveryDecision { readonly allowed:boolean; readonly reasonCode:StableCode; readonly maxTtlSeconds:60|120|300; readonly auditRequired:true }
const trustedAuthorizations=new WeakSet<object>();
export class TrustedDeliveryAuthorization { private constructor(readonly authorizationDecisionId:Uuid,readonly attachmentId:Uuid,readonly granteeUserId:Uuid,readonly action:StableCode,readonly decision:DeliveryDecision,readonly evaluatedAt:UtcInstant,readonly validUntil:UtcInstant,readonly evidenceIds:readonly Uuid[],readonly obligations:readonly StableCode[]){trustedAuthorizations.add(this);} static evaluate(service:AuthorizationService,actor:TrustedActorContext,resource:TrustedResourceContext,file:AttachmentSnapshot,authorizationDecisionId:Uuid){if(!(service instanceof AuthorizationService))fail("FILE_AUTHORIZATION_SERVICE_UNTRUSTED","Canonical AuthorizationService required.");assertTrustedActorContext(actor);assertTrustedResourceContext(resource);const action="technical_document.content.download" as StableCode;const authorization=service.decide(actor,{action,resource});let decision:DeliveryDecision;if(resource.resourceId!==file.attachmentId||file.state!=="AVAILABLE")decision={allowed:false,reasonCode:"FILE_RESOURCE_MISMATCH" as StableCode,maxTtlSeconds:60,auditRequired:true};else if(actor.actorKind==="VENDOR")decision={allowed:false,reasonCode:"VENDOR_DOCUMENT_DELIVERY_M05_DENIED" as StableCode,maxTtlSeconds:60,auditRequired:true};else if(authorization.effect!=="ALLOW")decision={allowed:false,reasonCode:authorization.reason,maxTtlSeconds:60,auditRequired:true};else if((file.securityLevel==="L3"||file.securityLevel==="L4")&&!resource.securityAllows)decision={allowed:false,reasonCode:"ADMIN_SYSTEM_L3_L4_SOURCE_DENIED" as StableCode,maxTtlSeconds:60,auditRequired:true};else decision={allowed:true,reasonCode:"FILE_DELIVERY_ALLOWED" as StableCode,maxTtlSeconds:60,auditRequired:true};const validUntil=new Date(Date.parse(actor.requestTime)+60_000).toISOString() as UtcInstant;return new TrustedDeliveryAuthorization(authorizationDecisionId,file.attachmentId,actor.authenticatedActorId,action,decision,actor.requestTime,validUntil,[...authorization.scopeEvidence,...actor.evidenceIds],authorization.obligations.map(x=>x as StableCode));} }
export function assertTrustedDeliveryAuthorization(value:TrustedDeliveryAuthorization){if(!trustedAuthorizations.has(value))fail("FILE_AUTHORIZATION_UNTRUSTED","Trusted server authorization required.");}
