import { nextVersion } from "@youone/shared-kernel/public";
import type { CorrelationId, IdempotencyKey, Sha256, StableCode, UtcInstant, Uuid, Version } from "@youone/shared-kernel/public";

export const SAFETY_INSPECTION_MACHINE_ID = "SM-SAFETY-INSPECTION-V1" as const;
export const SAFETY_INCIDENT_MACHINE_ID = "SM-SAFETY-INCIDENT-V1" as const;
export const SAFETY_PERMISSION_IDS = Object.freeze({ MANAGER_ASSIGN: "safety.assignment.manage", INSPECTION_MANAGE: "safety.inspection.manage", FINDING_RECORD: "safety.inspection.perform", STOP_WORK_MANAGE: "safety.inspection.manage", CORRECTION_MANAGE: "safety.finding.correct", VERIFY: "safety.inspection.manage", TRAINING_MANAGE: "safety.training.manage", INCIDENT_REPORT: "safety.incident.report", INCIDENT_RESPOND: "safety.incident.investigate", INCIDENT_INVESTIGATE: "safety.incident.investigate", RECURRENCE_SUBMIT: "safety.recurrence.submit", INCIDENT_CLOSE: "safety.incident.close", READ: "safety.record.read" } as const);
export const SAFETY_INSPECTION_EVENT_IDS = Object.freeze({ CREATE: "EVT-SAFETY-INSPECTION-PLAN", START: "EVT-SAFETY-INSPECTION-START", CLOSE_CLEAR: "EVT-SAFETY-INSPECTION-CLOSE-CLEAR", FINDINGS_ISSUE: "EVT-SAFETY-FINDINGS-ISSUE", STOP_WORK: "EVT-SAFETY-STOP-WORK", CORRECTION_ASSIGN: "EVT-SAFETY-CORRECTION-ASSIGN", SUBMIT_VERIFY: "EVT-SAFETY-SUBMIT-VERIFY", VERIFY_CLOSE: "EVT-SAFETY-VERIFY-CLOSE", VERIFY_FAIL: "EVT-SAFETY-VERIFY-FAIL", CANCEL: "EVT-SAFETY-INSPECTION-CANCEL" } as const);
export const SAFETY_INCIDENT_EVENT_IDS = Object.freeze({ REPORT: "EVT-SAFETY-INCIDENT-REPORT", EMERGENCY_RESPOND: "EVT-SAFETY-EMERGENCY-RESPOND", SECURE_SITE: "EVT-SAFETY-SECURE-SITE", START_INVESTIGATION: "EVT-SAFETY-START-INVESTIGATION", SET_RECURRENCE_ACTION: "EVT-SAFETY-SET-RECURRENCE-ACTION", SUBMIT_VERIFY: "EVT-SAFETY-SUBMIT-VERIFY", CLOSE: "EVT-SAFETY-CLOSE" } as const);
export const SAFETY_RECORD_EVENT_IDS = Object.freeze({ ASSIGN_MANAGER: "EVT-SAFETY-MANAGER-ASSIGN", RECORD_TRAINING: "EVT-SAFETY-TRAINING-RECORD", RECORD_ATTENDANCE: "EVT-SAFETY-TRAINING-ATTENDANCE", INCIDENT_SLA_ALERT: "EVT-SAFETY-INCIDENT-SLA-ALERT" } as const);

export type SafetyInspectionState = "PLANNED" | "IN_PROGRESS" | "FINDINGS_OPEN" | "STOP_WORK" | "CORRECTION_PENDING" | "VERIFICATION" | "CLOSED" | "CANCELLED";
export type SafetyIncidentState = "REPORTED" | "EMERGENCY_RESPONSE" | "SITE_SECURED" | "INVESTIGATION" | "RECURRENCE_ACTION" | "VERIFICATION" | "CLOSED";
export const SAFETY_INSPECTION_TRANSITIONS = Object.freeze({
  "EVT-SAFETY-INSPECTION-START": { from: ["PLANNED"], to: "IN_PROGRESS" },
  "EVT-SAFETY-INSPECTION-CLOSE-CLEAR": { from: ["IN_PROGRESS"], to: "CLOSED" },
  "EVT-SAFETY-FINDINGS-ISSUE": { from: ["IN_PROGRESS"], to: "FINDINGS_OPEN" },
  "EVT-SAFETY-STOP-WORK": { from: ["IN_PROGRESS", "FINDINGS_OPEN"], to: "STOP_WORK" },
  "EVT-SAFETY-CORRECTION-ASSIGN": { from: ["FINDINGS_OPEN", "STOP_WORK"], to: "CORRECTION_PENDING" },
  "EVT-SAFETY-SUBMIT-VERIFY": { from: ["CORRECTION_PENDING"], to: "VERIFICATION" },
  "EVT-SAFETY-VERIFY-CLOSE": { from: ["VERIFICATION"], to: "CLOSED" },
  "EVT-SAFETY-VERIFY-FAIL": { from: ["VERIFICATION"], to: "CORRECTION_PENDING" },
  "EVT-SAFETY-INSPECTION-CANCEL": { from: ["PLANNED"], to: "CANCELLED" }
} as const satisfies Readonly<Record<string, { readonly from: readonly SafetyInspectionState[]; readonly to: SafetyInspectionState }>>);
export const SAFETY_INCIDENT_TRANSITIONS = Object.freeze({
  "EVT-SAFETY-EMERGENCY-RESPOND": { from: ["REPORTED"], to: "EMERGENCY_RESPONSE" },
  "EVT-SAFETY-SECURE-SITE": { from: ["EMERGENCY_RESPONSE"], to: "SITE_SECURED" },
  "EVT-SAFETY-START-INVESTIGATION": { from: ["SITE_SECURED"], to: "INVESTIGATION" },
  "EVT-SAFETY-SET-RECURRENCE-ACTION": { from: ["INVESTIGATION"], to: "RECURRENCE_ACTION" },
  "EVT-SAFETY-SUBMIT-VERIFY": { from: ["RECURRENCE_ACTION"], to: "VERIFICATION" },
  "EVT-SAFETY-CLOSE": { from: ["VERIFICATION"], to: "CLOSED" }
} as const satisfies Readonly<Record<string, { readonly from: readonly SafetyIncidentState[]; readonly to: SafetyIncidentState }>>);

export interface SafetyActor { readonly actorKind: "INTERNAL" | "VENDOR" | "SYSTEM"; readonly userId?: Uuid; readonly active: boolean; readonly positionIds: readonly StableCode[]; readonly permissionIds: readonly StableCode[]; readonly safetyAssignmentId?: Uuid }
export interface SafetyCommand { readonly actor: SafetyActor; readonly expectedVersion: Version; readonly at: UtcInstant; readonly commandId: Uuid; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey }
export interface SafetyRetentionSnapshot { readonly policyVersionId: Uuid; readonly policyChecksum: Sha256; readonly referenceAt: UtcInstant; readonly minimumYears: 5; readonly applicableRegulatoryYears?: number; readonly legalHoldUntil?: UtcInstant; readonly retainUntil: UtcInstant }
export interface SafetyManagerAssignmentSnapshot { readonly safetyManagerAssignmentId: Uuid; readonly assigneeUserId: Uuid; readonly assignmentKind: "SAFETY_MANAGER" | "TEAM_COORDINATOR"; readonly assignmentScope?: { readonly kind: "TEAM"; readonly teamId: Uuid } | { readonly kind: "PROJECT"; readonly projectId: Uuid }; readonly designatedByLabDirectorUserId: Uuid; readonly validFrom: UtcInstant; readonly validUntil?: UtcInstant; readonly revokedAt?: UtcInstant; readonly evidenceIds: readonly Uuid[]; readonly retention: SafetyRetentionSnapshot; readonly version: Version }
export type SafetyScope = { readonly kind: "LAB" } | { readonly kind: "TEAM"; readonly teamId: Uuid } | { readonly kind: "PROJECT"; readonly projectId: Uuid } | { readonly kind: "WORK_AREA"; readonly workAreaCode: StableCode };
export interface SafetyInspectionItemSnapshot { readonly safetyInspectionItemId: Uuid; readonly checklistItemCode: StableCode; readonly result: "CONFORMING" | "NONCONFORMING" | "NOT_APPLICABLE"; readonly comment?: string; readonly evidenceIds: readonly Uuid[]; readonly retention: SafetyRetentionSnapshot }
export interface SafetyFindingSnapshot { readonly safetyFindingId: Uuid; readonly safetyInspectionId: Uuid; readonly inspectionItemId: Uuid; readonly severity: "MINOR" | "MAJOR" | "CRITICAL"; readonly description: string; readonly imminentRisk: boolean; readonly evidenceIds: readonly Uuid[]; readonly issuedByUserId: Uuid; readonly issuedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface StopWorkOrderSnapshot { readonly stopWorkOrderId: Uuid; readonly safetyInspectionId: Uuid; readonly findingIds: readonly Uuid[]; readonly scope: SafetyScope; readonly reason: string; readonly evidenceIds: readonly Uuid[]; readonly orderedByUserId: Uuid; readonly orderedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface SafetyCorrectionAssignmentSnapshot { readonly safetyCorrectionAssignmentId: Uuid; readonly safetyInspectionId: Uuid; readonly findingIds: readonly Uuid[]; readonly ownerUserId: Uuid; readonly dueAt: UtcInstant; readonly instruction: string; readonly assignedByUserId: Uuid; readonly evidenceIds: readonly Uuid[]; readonly assignedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface SafetyCorrectionSubmissionSnapshot { readonly safetyCorrectionSubmissionId: Uuid; readonly correctionAssignmentId: Uuid; readonly submittedByUserId: Uuid; readonly summary: string; readonly evidenceIds: readonly Uuid[]; readonly submittedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface SafetyCorrectionVerificationSnapshot { readonly safetyCorrectionVerificationId: Uuid; readonly correctionAssignmentId: Uuid; readonly submissionId: Uuid; readonly verifierUserId: Uuid; readonly effective: boolean; readonly comment: string; readonly evidenceIds: readonly Uuid[]; readonly verifiedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface SafetyInspectionSnapshot { readonly safetyInspectionId: Uuid; readonly inspectionNo: string; readonly inspectionType: "MONTHLY_REGULAR" | "WEEKLY_TEAM_SELF" | "AD_HOC" | "SPECIAL"; readonly scope: SafetyScope; readonly scheduledFor: string; readonly frequencyPolicyVersionId: Uuid; readonly frequencyPolicyChecksum: Sha256; readonly assignedSafetyManagerAssignmentId: Uuid; readonly state: SafetyInspectionState; readonly itemIds: readonly Uuid[]; readonly findingIds: readonly Uuid[]; readonly activeCorrectionAssignmentId?: Uuid; readonly activeCorrectionOwnerUserId?: Uuid; readonly latestCorrectionSubmissionId?: Uuid; readonly retention: SafetyRetentionSnapshot; readonly version: Version; readonly createdAt: UtcInstant; readonly updatedAt: UtcInstant }

export interface SafetyTrainingSessionSnapshot { readonly safetyTrainingSessionId: Uuid; readonly trainingType: "NEW_JOINER" | "SEMIANNUAL_REGULAR" | "SPECIAL"; readonly title: string; readonly scheduledAt: UtcInstant; readonly trainerUserId: Uuid; readonly policyVersionId: Uuid; readonly policyChecksum: Sha256; readonly materialAttachmentIds: readonly Uuid[]; readonly retention: SafetyRetentionSnapshot; readonly recordedByUserId: Uuid; readonly recordedAt: UtcInstant }
export interface SafetyTrainingAttendanceSnapshot { readonly safetyTrainingAttendanceId: Uuid; readonly safetyTrainingSessionId: Uuid; readonly attendeeUserId: Uuid; readonly status: "ATTENDED" | "ABSENT" | "INCOMPLETE"; readonly completionEvidenceIds: readonly Uuid[]; readonly remedialRequired: boolean; readonly remedialDueAt?: UtcInstant; readonly remedialForAttendanceId?: Uuid; readonly recordedByUserId: Uuid; readonly recordedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }

export interface SafetyIncidentSnapshot { readonly safetyIncidentId: Uuid; readonly incidentNo: string; readonly severity: "MINOR" | "MAJOR" | "CRITICAL"; readonly scope: SafetyScope; readonly summary: string; readonly occurredAt: UtcInstant; readonly reportedAt: UtcInstant; readonly reportedByUserId: Uuid; readonly investigationDueAt: UtcInstant; readonly state: SafetyIncidentState; readonly emergencyResponseId?: Uuid; readonly siteSecuringId?: Uuid; readonly investigationId?: Uuid; readonly investigationStartedAt?: UtcInstant; readonly recurrenceActionId?: Uuid; readonly recurrenceOwnerUserId?: Uuid; readonly verificationId?: Uuid; readonly retention: SafetyRetentionSnapshot; readonly version: Version; readonly updatedAt: UtcInstant }
export interface EmergencyResponseSnapshot { readonly emergencyResponseId: Uuid; readonly safetyIncidentId: Uuid; readonly actionsTaken: string; readonly notificationEvidenceIds: readonly Uuid[]; readonly responderUserId: Uuid; readonly respondedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface SiteSecuringSnapshot { readonly siteSecuringId: Uuid; readonly safetyIncidentId: Uuid; readonly preservationSummary: string; readonly evidenceIds: readonly Uuid[]; readonly securedByUserId: Uuid; readonly securedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface IncidentInvestigationSnapshot { readonly incidentInvestigationId: Uuid; readonly safetyIncidentId: Uuid; readonly startedByUserId: Uuid; readonly startedAt: UtcInstant; readonly internalSlaDueAt: UtcInstant; readonly statutoryDeadlineValidated: false; readonly retention: SafetyRetentionSnapshot }
export interface IncidentRecurrenceActionSnapshot { readonly incidentRecurrenceActionId: Uuid; readonly safetyIncidentId: Uuid; readonly causeAnalysis: string; readonly actionPlan: string; readonly ownerUserId: Uuid; readonly dueAt: UtcInstant; readonly evidenceIds: readonly Uuid[]; readonly setByUserId: Uuid; readonly setAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }
export interface IncidentVerificationSnapshot { readonly incidentVerificationId: Uuid; readonly recurrenceActionId: Uuid; readonly submittedByUserId: Uuid; readonly verifierUserId: Uuid; readonly effective: true; readonly evidenceIds: readonly Uuid[]; readonly verifiedAt: UtcInstant; readonly retention: SafetyRetentionSnapshot }

export interface SafetyTransition { readonly machineId: typeof SAFETY_INSPECTION_MACHINE_ID | typeof SAFETY_INCIDENT_MACHINE_ID; readonly aggregateId: Uuid; readonly fromState?: SafetyInspectionState | SafetyIncidentState; readonly toState: SafetyInspectionState | SafetyIncidentState; readonly eventId: StableCode; readonly fromVersion: Version; readonly toVersion: Version; readonly actorUserId: Uuid; readonly occurredAt: UtcInstant; readonly commandId: Uuid; readonly correlationId: CorrelationId }
export interface SafetyDomainEvent { readonly eventId: StableCode; readonly aggregateId: Uuid; readonly aggregateVersion: Version; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly idempotencyKey: IdempotencyKey; readonly payload: Readonly<Record<string, string | number | boolean | null>> }
export interface SafetyAuditObligation { readonly actionId: StableCode; readonly aggregateId: Uuid; readonly actor: SafetyActor; readonly occurredAt: UtcInstant; readonly correlationId: CorrelationId; readonly evidenceIds: readonly Uuid[] }
export interface SafetyInspectionMutation { readonly expectedVersion: Version; readonly snapshot: SafetyInspectionSnapshot; readonly transition: SafetyTransition; readonly event: SafetyDomainEvent; readonly audit: SafetyAuditObligation; readonly appendedItems?: readonly SafetyInspectionItemSnapshot[]; readonly appendedFindings?: readonly SafetyFindingSnapshot[]; readonly stopWorkOrder?: StopWorkOrderSnapshot; readonly correctionAssignment?: SafetyCorrectionAssignmentSnapshot; readonly correctionSubmission?: SafetyCorrectionSubmissionSnapshot; readonly correctionVerification?: SafetyCorrectionVerificationSnapshot }
export interface SafetyIncidentMutation { readonly expectedVersion: Version; readonly snapshot: SafetyIncidentSnapshot; readonly transition: SafetyTransition; readonly event: SafetyDomainEvent; readonly audit: SafetyAuditObligation; readonly emergencyResponse?: EmergencyResponseSnapshot; readonly siteSecuring?: SiteSecuringSnapshot; readonly investigation?: IncidentInvestigationSnapshot; readonly recurrenceAction?: IncidentRecurrenceActionSnapshot; readonly verification?: IncidentVerificationSnapshot }

export class SafetyDomainError extends Error { public constructor(public readonly code: StableCode, message: string) { super(message); this.name = "SafetyDomainError"; } }
const fail = (code: string, message: string): never => { throw new SafetyDomainError(code as StableCode, message); };
const immutable = <T>(value: T): T => Object.freeze(structuredClone(value));
const text = (value: string, code: string): void => { if (!value.trim()) fail(code, "A non-empty value is required."); };
const internal = (actor: SafetyActor, permission: string): Uuid => { const userId = actor.userId; if (actor.actorKind !== "INTERNAL" || !actor.active || !userId || !actor.permissionIds.includes(permission as StableCode)) fail("SAFETY_INTERNAL_PERMISSION_REQUIRED", `Active internal ${permission} permission is required; Vendor is denied by default.`); return userId as Uuid; };
const incidentReporter = (actor: SafetyActor): Uuid => { const userId = actor.userId; if (!actor.active || !userId || !["INTERNAL", "VENDOR"].includes(actor.actorKind) || !actor.permissionIds.includes(SAFETY_PERMISSION_IDS.INCIDENT_REPORT as StableCode)) fail("SAFETY_INCIDENT_REPORT_SCOPE_REQUIRED", "Active internal permission or exact Vendor Safety incident-report scope is required."); return userId as Uuid; };
const exactIsoDate = (value: string): void => { if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(`${value}T00:00:00Z`))) fail("SAFETY_DATE_INVALID", "ISO date is required."); };
const plusYears = (instant: UtcInstant, years: number): UtcInstant => { const date = new Date(instant); date.setUTCFullYear(date.getUTCFullYear() + years); return date.toISOString() as UtcInstant; };
const plusHours = (instant: UtcInstant, hours: number): UtcInstant => new Date(new Date(instant).getTime() + hours * 3_600_000).toISOString() as UtcInstant;

export function createSafetyRetention(input: Omit<SafetyRetentionSnapshot, "minimumYears" | "retainUntil">): SafetyRetentionSnapshot {
  const regulatoryYears = input.applicableRegulatoryYears ?? 0;
  if (!Number.isInteger(regulatoryYears) || regulatoryYears < 0) fail("SAFETY_RETENTION_YEARS_INVALID", "Regulatory retention years must be a non-negative integer.");
  let retainUntil = plusYears(input.referenceAt, Math.max(5, regulatoryYears));
  if (input.legalHoldUntil && input.legalHoldUntil > retainUntil) retainUntil = input.legalHoldUntil;
  return immutable({ ...input, minimumYears: 5 as const, retainUntil });
}

export function designateSafetyManager(input: Omit<SafetyManagerAssignmentSnapshot, "designatedByLabDirectorUserId" | "version">, actor: SafetyActor): SafetyManagerAssignmentSnapshot {
  const directorId = internal(actor, SAFETY_PERMISSION_IDS.MANAGER_ASSIGN);
  if (!actor.positionIds.includes("POSITION_LAB_DIRECTOR" as StableCode) || input.validUntil && input.validUntil <= input.validFrom || input.revokedAt !== undefined || input.evidenceIds.length === 0 || input.assignmentKind === "TEAM_COORDINATOR" && input.assignmentScope?.kind !== "TEAM") fail("SAFETY_MANAGER_DESIGNATION_INVALID", "Lab Director evidence, valid effective period and exact optional Project/team scope are required.");
  return immutable({ ...input, designatedByLabDirectorUserId: directorId, version: 1 as Version });
}

export function createTrainingSession(input: Omit<SafetyTrainingSessionSnapshot, "recordedByUserId" | "recordedAt">, actor: SafetyActor, at: UtcInstant): SafetyTrainingSessionSnapshot { const userId = internal(actor, SAFETY_PERMISSION_IDS.TRAINING_MANAGE); text(input.title, "SAFETY_TRAINING_TITLE_REQUIRED"); if (input.materialAttachmentIds.length === 0) fail("SAFETY_TRAINING_MATERIAL_REQUIRED", "Training material evidence is required."); return immutable({ ...input, recordedByUserId: userId, recordedAt: at }); }
export function recordTrainingAttendance(input: Omit<SafetyTrainingAttendanceSnapshot, "recordedByUserId" | "recordedAt">, actor: SafetyActor, at: UtcInstant): SafetyTrainingAttendanceSnapshot { const userId = internal(actor, SAFETY_PERMISSION_IDS.TRAINING_MANAGE); const needsRemedial = input.status !== "ATTENDED"; if (input.remedialRequired !== needsRemedial || needsRemedial !== Boolean(input.remedialDueAt) || input.status === "ATTENDED" && input.completionEvidenceIds.length === 0 || input.remedialForAttendanceId === input.safetyTrainingAttendanceId) fail("SAFETY_TRAINING_ATTENDANCE_INVALID", "Attendance evidence and supplementary-training obligation must match the recorded outcome."); return immutable({ ...input, recordedByUserId: userId, recordedAt: at }); }

export class SafetyInspection {
  private constructor(private value: SafetyInspectionSnapshot) {}
  static plan(input: Omit<SafetyInspectionSnapshot, "state" | "itemIds" | "findingIds" | "activeCorrectionAssignmentId" | "activeCorrectionOwnerUserId" | "latestCorrectionSubmissionId" | "version" | "createdAt" | "updatedAt">, command: Omit<SafetyCommand, "expectedVersion">): SafetyInspectionMutation { const actorId = internal(command.actor, SAFETY_PERMISSION_IDS.INSPECTION_MANAGE); text(input.inspectionNo, "SAFETY_INSPECTION_NO_REQUIRED"); exactIsoDate(input.scheduledFor); const snapshot: SafetyInspectionSnapshot = { ...structuredClone(input), state: "PLANNED", itemIds: [], findingIds: [], version: 1 as Version, createdAt: command.at, updatedAt: command.at }; return SafetyInspection.mutation(snapshot, undefined, command, 0 as Version, SAFETY_INSPECTION_EVENT_IDS.CREATE, actorId, []); }
  static restore(snapshot: SafetyInspectionSnapshot): SafetyInspection { return new SafetyInspection(structuredClone(snapshot)); }
  snapshot(): SafetyInspectionSnapshot { return structuredClone(this.value); }
  start(command: SafetyCommand): SafetyInspectionMutation { return this.change(command, SAFETY_INSPECTION_EVENT_IDS.START, SAFETY_PERMISSION_IDS.INSPECTION_MANAGE, []); }
  closeClear(command: SafetyCommand, items: readonly Omit<SafetyInspectionItemSnapshot, "retention">[]): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.CLOSE_CLEAR, SAFETY_PERMISSION_IDS.FINDING_RECORD); if (items.length === 0 || items.some((item) => item.result === "NONCONFORMING") || new Set(items.map((item) => item.checklistItemCode)).size !== items.length) fail("SAFETY_CLEAR_INSPECTION_INCOMPLETE", "A clear close requires a complete unique checklist with no nonconforming result."); const records = items.map((item) => immutable({ ...item, retention: this.value.retention })); this.value = { ...this.value, itemIds: records.map((item) => item.safetyInspectionItemId) }; const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.CLOSE_CLEAR, actorId, records.flatMap((item) => item.evidenceIds)); return { ...mutation, appendedItems: immutable(records) }; }
  cancel(command: SafetyCommand, reason: string, evidenceIds: readonly Uuid[]): SafetyInspectionMutation { text(reason, "SAFETY_INSPECTION_CANCEL_REASON_REQUIRED"); if (evidenceIds.length === 0) fail("SAFETY_INSPECTION_CANCEL_EVIDENCE_REQUIRED", "Cancellation evidence is required."); return this.change(command, SAFETY_INSPECTION_EVENT_IDS.CANCEL, SAFETY_PERMISSION_IDS.INSPECTION_MANAGE, evidenceIds); }
  issueFindings(command: SafetyCommand, items: readonly Omit<SafetyInspectionItemSnapshot, "retention">[], findings: readonly Omit<SafetyFindingSnapshot, "safetyInspectionId" | "issuedByUserId" | "issuedAt" | "retention">[]): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.FINDINGS_ISSUE, SAFETY_PERMISSION_IDS.FINDING_RECORD); if (items.length === 0 || findings.length === 0) fail("SAFETY_FINDING_EVIDENCE_REQUIRED", "Checklist items and at least one evidence-backed finding are required."); const itemRecords: SafetyInspectionItemSnapshot[] = items.map((item) => immutable({ ...item, retention: this.value.retention })); const itemIds = new Set(itemRecords.map((item) => item.safetyInspectionItemId)); const records: SafetyFindingSnapshot[] = findings.map((finding) => { if (!itemIds.has(finding.inspectionItemId) || !finding.description.trim() || finding.evidenceIds.length === 0 || finding.imminentRisk && finding.severity !== "CRITICAL") fail("SAFETY_FINDING_INVALID", "Finding must reference an exact item and preserve severity/evidence; imminent risk is CRITICAL."); return immutable({ ...finding, safetyInspectionId: this.value.safetyInspectionId, issuedByUserId: actorId, issuedAt: command.at, retention: this.value.retention }); }); this.value = { ...this.value, itemIds: itemRecords.map((item) => item.safetyInspectionItemId), findingIds: records.map((finding) => finding.safetyFindingId) }; const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.FINDINGS_ISSUE, actorId, records.flatMap((finding) => finding.evidenceIds)); return { ...mutation, appendedItems: immutable(itemRecords), appendedFindings: immutable(records) }; }
  stopWorkForImminentFinding(command: SafetyCommand, input: { readonly order: Omit<StopWorkOrderSnapshot, "safetyInspectionId" | "findingIds" | "orderedByUserId" | "orderedAt" | "retention">; readonly item: Omit<SafetyInspectionItemSnapshot, "retention">; readonly finding: Omit<SafetyFindingSnapshot, "safetyInspectionId" | "issuedByUserId" | "issuedAt" | "retention"> }): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.STOP_WORK, SAFETY_PERMISSION_IDS.STOP_WORK_MANAGE); if (this.value.state !== "IN_PROGRESS" || input.item.result !== "NONCONFORMING" || input.finding.inspectionItemId !== input.item.safetyInspectionItemId || input.finding.severity !== "CRITICAL" || !input.finding.imminentRisk || input.finding.evidenceIds.length === 0 || input.order.evidenceIds.length === 0) fail("SAFETY_STOP_WORK_IMMINENT_RISK_REQUIRED", "Direct stop-work requires one exact nonconforming item and critical imminent-risk finding with evidence."); text(input.finding.description, "SAFETY_FINDING_DESCRIPTION_REQUIRED"); text(input.order.reason, "SAFETY_STOP_WORK_REASON_REQUIRED"); const item: SafetyInspectionItemSnapshot = immutable({ ...input.item, retention: this.value.retention }); const finding: SafetyFindingSnapshot = immutable({ ...input.finding, safetyInspectionId: this.value.safetyInspectionId, issuedByUserId: actorId, issuedAt: command.at, retention: this.value.retention }); const order: StopWorkOrderSnapshot = immutable({ ...input.order, safetyInspectionId: this.value.safetyInspectionId, findingIds: [finding.safetyFindingId], orderedByUserId: actorId, orderedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, itemIds: [...this.value.itemIds, item.safetyInspectionItemId], findingIds: [...this.value.findingIds, finding.safetyFindingId] }; const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.STOP_WORK, actorId, [...input.finding.evidenceIds, ...input.order.evidenceIds]); return { ...mutation, appendedItems: [item], appendedFindings: [finding], stopWorkOrder: order }; }
  stopWork(command: SafetyCommand, input: Omit<StopWorkOrderSnapshot, "safetyInspectionId" | "orderedByUserId" | "orderedAt" | "retention">, findings: readonly SafetyFindingSnapshot[]): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.STOP_WORK, SAFETY_PERMISSION_IDS.STOP_WORK_MANAGE); const critical = findings.filter((finding) => input.findingIds.includes(finding.safetyFindingId) && finding.safetyInspectionId === this.value.safetyInspectionId && this.value.findingIds.includes(finding.safetyFindingId) && finding.severity === "CRITICAL" && finding.imminentRisk); if (critical.length !== input.findingIds.length || input.findingIds.length === 0 || input.evidenceIds.length === 0) fail("SAFETY_STOP_WORK_IMMINENT_RISK_REQUIRED", "Stop-work requires exact current-inspection critical imminent-risk findings and evidence."); text(input.reason, "SAFETY_STOP_WORK_REASON_REQUIRED"); const order: StopWorkOrderSnapshot = immutable({ ...input, safetyInspectionId: this.value.safetyInspectionId, orderedByUserId: actorId, orderedAt: command.at, retention: this.value.retention }); const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.STOP_WORK, actorId, input.evidenceIds); return { ...mutation, stopWorkOrder: order }; }
  assignCorrection(command: SafetyCommand, input: Omit<SafetyCorrectionAssignmentSnapshot, "safetyInspectionId" | "assignedByUserId" | "assignedAt" | "retention">): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.CORRECTION_ASSIGN, SAFETY_PERMISSION_IDS.CORRECTION_MANAGE); if (input.findingIds.length === 0 || input.findingIds.length !== this.value.findingIds.length || input.findingIds.some((id) => !this.value.findingIds.includes(id)) || input.dueAt <= command.at || input.evidenceIds.length === 0) fail("SAFETY_CORRECTION_ASSIGNMENT_INVALID", "Correction must cover every exact open finding with a future deadline and evidence."); text(input.instruction, "SAFETY_CORRECTION_INSTRUCTION_REQUIRED"); const assignment: SafetyCorrectionAssignmentSnapshot = immutable({ ...input, safetyInspectionId: this.value.safetyInspectionId, assignedByUserId: actorId, assignedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, activeCorrectionAssignmentId: assignment.safetyCorrectionAssignmentId, activeCorrectionOwnerUserId: assignment.ownerUserId }; const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.CORRECTION_ASSIGN, actorId, input.evidenceIds); return { ...mutation, correctionAssignment: assignment }; }
  submitVerification(command: SafetyCommand, input: Omit<SafetyCorrectionSubmissionSnapshot, "correctionAssignmentId" | "submittedByUserId" | "submittedAt" | "retention">): SafetyInspectionMutation { const actorId = this.assert(command, SAFETY_INSPECTION_EVENT_IDS.SUBMIT_VERIFY, SAFETY_PERMISSION_IDS.CORRECTION_MANAGE); const assignmentId = this.value.activeCorrectionAssignmentId; if (actorId !== this.value.activeCorrectionOwnerUserId || !assignmentId || input.evidenceIds.length === 0) fail("SAFETY_CORRECTION_OWNER_EVIDENCE_REQUIRED", "Exact correction owner and implementation evidence are required."); text(input.summary, "SAFETY_CORRECTION_SUMMARY_REQUIRED"); const submission: SafetyCorrectionSubmissionSnapshot = immutable({ ...input, correctionAssignmentId: assignmentId as Uuid, submittedByUserId: actorId, submittedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, latestCorrectionSubmissionId: submission.safetyCorrectionSubmissionId }; const mutation = this.apply(command, SAFETY_INSPECTION_EVENT_IDS.SUBMIT_VERIFY, actorId, input.evidenceIds); return { ...mutation, correctionSubmission: submission }; }
  verify(command: SafetyCommand, input: Omit<SafetyCorrectionVerificationSnapshot, "correctionAssignmentId" | "submissionId" | "verifierUserId" | "verifiedAt" | "retention">): SafetyInspectionMutation { const eventId = input.effective ? SAFETY_INSPECTION_EVENT_IDS.VERIFY_CLOSE : SAFETY_INSPECTION_EVENT_IDS.VERIFY_FAIL; const verifierId = this.assert(command, eventId, SAFETY_PERMISSION_IDS.VERIFY); const assignmentId = this.value.activeCorrectionAssignmentId; const submissionId = this.value.latestCorrectionSubmissionId; if (!assignmentId || !submissionId || verifierId === this.value.activeCorrectionOwnerUserId || input.evidenceIds.length === 0) fail("SAFETY_INDEPENDENT_VERIFICATION_REQUIRED", "Independent verifier and evidence are required."); text(input.comment, "SAFETY_VERIFICATION_COMMENT_REQUIRED"); const verification: SafetyCorrectionVerificationSnapshot = immutable({ ...input, correctionAssignmentId: assignmentId as Uuid, submissionId: submissionId as Uuid, verifierUserId: verifierId, verifiedAt: command.at, retention: this.value.retention }); const mutation = this.apply(command, eventId, verifierId, input.evidenceIds); return { ...mutation, correctionVerification: verification }; }
  private assert(command: SafetyCommand, eventId: keyof typeof SAFETY_INSPECTION_TRANSITIONS, permission: string): Uuid { if (command.expectedVersion !== this.value.version) fail("SAFETY_INSPECTION_STALE_VERSION", "Optimistic version mismatch."); const transition = SAFETY_INSPECTION_TRANSITIONS[eventId]; if (!(transition.from as readonly SafetyInspectionState[]).includes(this.value.state)) fail("SAFETY_INSPECTION_TRANSITION_INVALID", `${eventId} is not allowed from ${this.value.state}.`); return internal(command.actor, permission); }
  private change(command: SafetyCommand, eventId: keyof typeof SAFETY_INSPECTION_TRANSITIONS, permission: string, evidenceIds: readonly Uuid[]): SafetyInspectionMutation { const actorId = this.assert(command, eventId, permission); return this.apply(command, eventId, actorId, evidenceIds); }
  private apply(command: SafetyCommand, eventId: keyof typeof SAFETY_INSPECTION_TRANSITIONS, actorId: Uuid, evidenceIds: readonly Uuid[]): SafetyInspectionMutation { const from = this.value.state; const expected = this.value.version; this.value = { ...this.value, state: SAFETY_INSPECTION_TRANSITIONS[eventId].to, version: nextVersion(this.value.version), updatedAt: command.at }; return SafetyInspection.mutation(this.value, from, command, expected, eventId, actorId, evidenceIds); }
  private static mutation(snapshot: SafetyInspectionSnapshot, from: SafetyInspectionState | undefined, command: Omit<SafetyCommand, "expectedVersion">, expectedVersion: Version, eventId: string, actorId: Uuid, evidenceIds: readonly Uuid[]): SafetyInspectionMutation { const stableEventId = eventId as StableCode; return { expectedVersion, snapshot: immutable(snapshot), transition: { machineId: SAFETY_INSPECTION_MACHINE_ID, aggregateId: snapshot.safetyInspectionId, ...(from ? { fromState: from } : {}), toState: snapshot.state, eventId: stableEventId, fromVersion: expectedVersion, toVersion: snapshot.version, actorUserId: actorId, occurredAt: command.at, commandId: command.commandId, correlationId: command.correlationId }, event: { eventId: stableEventId, aggregateId: snapshot.safetyInspectionId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, payload: { state: snapshot.state, p1HazardousMaterialImplemented: false, autoCompleted: false } }, audit: { actionId: stableEventId, aggregateId: snapshot.safetyInspectionId, actor: structuredClone(command.actor), occurredAt: command.at, correlationId: command.correlationId, evidenceIds: [...evidenceIds] } }; }
}

export class SafetyIncident {
  private constructor(private value: SafetyIncidentSnapshot) {}
  static report(input: Omit<SafetyIncidentSnapshot, "reportedAt" | "reportedByUserId" | "investigationDueAt" | "state" | "emergencyResponseId" | "siteSecuringId" | "investigationId" | "investigationStartedAt" | "recurrenceActionId" | "recurrenceOwnerUserId" | "verificationId" | "version" | "updatedAt">, command: Omit<SafetyCommand, "expectedVersion">): SafetyIncidentMutation { const reporter = incidentReporter(command.actor); text(input.incidentNo, "SAFETY_INCIDENT_NO_REQUIRED"); text(input.summary, "SAFETY_INCIDENT_SUMMARY_REQUIRED"); if (input.occurredAt > command.at) fail("SAFETY_INCIDENT_OCCURRENCE_INVALID", "Incident occurrence cannot be in the future."); const snapshot: SafetyIncidentSnapshot = { ...structuredClone(input), reportedAt: command.at, reportedByUserId: reporter, investigationDueAt: plusHours(command.at, 48), state: "REPORTED", version: 1 as Version, updatedAt: command.at }; return SafetyIncident.mutation(snapshot, undefined, command, 0 as Version, SAFETY_INCIDENT_EVENT_IDS.REPORT, reporter, []); }
  static restore(snapshot: SafetyIncidentSnapshot): SafetyIncident { return new SafetyIncident(structuredClone(snapshot)); }
  snapshot(): SafetyIncidentSnapshot { return structuredClone(this.value); }
  respond(command: SafetyCommand, input: Omit<EmergencyResponseSnapshot, "safetyIncidentId" | "responderUserId" | "respondedAt" | "retention">): SafetyIncidentMutation { const actorId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.EMERGENCY_RESPOND, SAFETY_PERMISSION_IDS.INCIDENT_RESPOND); text(input.actionsTaken, "SAFETY_EMERGENCY_ACTION_REQUIRED"); if (input.notificationEvidenceIds.length === 0) fail("SAFETY_EMERGENCY_NOTIFICATION_EVIDENCE_REQUIRED", "Emergency response notification evidence is required."); const record = immutable({ ...input, safetyIncidentId: this.value.safetyIncidentId, responderUserId: actorId, respondedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, emergencyResponseId: record.emergencyResponseId }; const mutation = this.apply(command, SAFETY_INCIDENT_EVENT_IDS.EMERGENCY_RESPOND, actorId, input.notificationEvidenceIds); return { ...mutation, emergencyResponse: record }; }
  secureSite(command: SafetyCommand, input: Omit<SiteSecuringSnapshot, "safetyIncidentId" | "securedByUserId" | "securedAt" | "retention">): SafetyIncidentMutation { const actorId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.SECURE_SITE, SAFETY_PERMISSION_IDS.INCIDENT_RESPOND); text(input.preservationSummary, "SAFETY_SITE_PRESERVATION_REQUIRED"); if (input.evidenceIds.length === 0) fail("SAFETY_SITE_EVIDENCE_REQUIRED", "Site-preservation evidence is required."); const record = immutable({ ...input, safetyIncidentId: this.value.safetyIncidentId, securedByUserId: actorId, securedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, siteSecuringId: record.siteSecuringId }; const mutation = this.apply(command, SAFETY_INCIDENT_EVENT_IDS.SECURE_SITE, actorId, input.evidenceIds); return { ...mutation, siteSecuring: record }; }
  startInvestigation(command: SafetyCommand, incidentInvestigationId: Uuid): SafetyIncidentMutation { const actorId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.START_INVESTIGATION, SAFETY_PERMISSION_IDS.INCIDENT_INVESTIGATE); const record: IncidentInvestigationSnapshot = immutable({ incidentInvestigationId, safetyIncidentId: this.value.safetyIncidentId, startedByUserId: actorId, startedAt: command.at, internalSlaDueAt: this.value.investigationDueAt, statutoryDeadlineValidated: false, retention: this.value.retention }); this.value = { ...this.value, investigationId: record.incidentInvestigationId, investigationStartedAt: record.startedAt }; const mutation = this.apply(command, SAFETY_INCIDENT_EVENT_IDS.START_INVESTIGATION, actorId, []); return { ...mutation, investigation: record }; }
  setRecurrenceAction(command: SafetyCommand, input: Omit<IncidentRecurrenceActionSnapshot, "safetyIncidentId" | "setByUserId" | "setAt" | "retention">): SafetyIncidentMutation { const actorId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.SET_RECURRENCE_ACTION, SAFETY_PERMISSION_IDS.INCIDENT_INVESTIGATE); text(input.causeAnalysis, "SAFETY_INCIDENT_CAUSE_REQUIRED"); text(input.actionPlan, "SAFETY_RECURRENCE_PLAN_REQUIRED"); if (input.dueAt <= command.at || input.evidenceIds.length === 0) fail("SAFETY_RECURRENCE_EVIDENCE_REQUIRED", "Recurrence action requires future due date and evidence."); const record = immutable({ ...input, safetyIncidentId: this.value.safetyIncidentId, setByUserId: actorId, setAt: command.at, retention: this.value.retention }); this.value = { ...this.value, recurrenceActionId: record.incidentRecurrenceActionId, recurrenceOwnerUserId: record.ownerUserId }; const mutation = this.apply(command, SAFETY_INCIDENT_EVENT_IDS.SET_RECURRENCE_ACTION, actorId, input.evidenceIds); return { ...mutation, recurrenceAction: record }; }
  submitVerification(command: SafetyCommand, evidenceIds: readonly Uuid[]): SafetyIncidentMutation { const actorId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.SUBMIT_VERIFY, SAFETY_PERMISSION_IDS.RECURRENCE_SUBMIT); if (actorId !== this.value.recurrenceOwnerUserId || evidenceIds.length === 0) fail("SAFETY_RECURRENCE_OWNER_EVIDENCE_REQUIRED", "Recurrence owner and implementation evidence are required."); return this.apply(command, SAFETY_INCIDENT_EVENT_IDS.SUBMIT_VERIFY, actorId, evidenceIds); }
  close(command: SafetyCommand, input: Omit<IncidentVerificationSnapshot, "recurrenceActionId" | "verifierUserId" | "verifiedAt" | "effective" | "retention">): SafetyIncidentMutation { const verifierId = this.assert(command, SAFETY_INCIDENT_EVENT_IDS.CLOSE, SAFETY_PERMISSION_IDS.INCIDENT_CLOSE); const recurrenceActionId = this.value.recurrenceActionId; if (!command.actor.positionIds.includes("POSITION_LAB_DIRECTOR" as StableCode) || !recurrenceActionId || verifierId === this.value.recurrenceOwnerUserId || input.submittedByUserId !== this.value.recurrenceOwnerUserId || input.evidenceIds.length === 0) fail("SAFETY_INCIDENT_DIRECTOR_VERIFICATION_REQUIRED", "Lab Director independent effectiveness verification and evidence are required."); const record: IncidentVerificationSnapshot = immutable({ ...input, recurrenceActionId: recurrenceActionId as Uuid, verifierUserId: verifierId, effective: true, verifiedAt: command.at, retention: this.value.retention }); this.value = { ...this.value, verificationId: record.incidentVerificationId }; const mutation = this.apply(command, SAFETY_INCIDENT_EVENT_IDS.CLOSE, verifierId, input.evidenceIds); return { ...mutation, verification: record }; }
  private assert(command: SafetyCommand, eventId: keyof typeof SAFETY_INCIDENT_TRANSITIONS, permission: string): Uuid { if (command.expectedVersion !== this.value.version) fail("SAFETY_INCIDENT_STALE_VERSION", "Optimistic version mismatch."); const transition = SAFETY_INCIDENT_TRANSITIONS[eventId]; if (!(transition.from as readonly SafetyIncidentState[]).includes(this.value.state)) fail("SAFETY_INCIDENT_TRANSITION_INVALID", `${eventId} is not allowed from ${this.value.state}.`); return internal(command.actor, permission); }
  private apply(command: SafetyCommand, eventId: keyof typeof SAFETY_INCIDENT_TRANSITIONS, actorId: Uuid, evidenceIds: readonly Uuid[]): SafetyIncidentMutation { const from = this.value.state; const expected = this.value.version; this.value = { ...this.value, state: SAFETY_INCIDENT_TRANSITIONS[eventId].to, version: nextVersion(this.value.version), updatedAt: command.at }; return SafetyIncident.mutation(this.value, from, command, expected, eventId, actorId, evidenceIds); }
  private static mutation(snapshot: SafetyIncidentSnapshot, from: SafetyIncidentState | undefined, command: Omit<SafetyCommand, "expectedVersion">, expectedVersion: Version, eventId: string, actorId: Uuid, evidenceIds: readonly Uuid[]): SafetyIncidentMutation { const stableEventId = eventId as StableCode; return { expectedVersion, snapshot: immutable(snapshot), transition: { machineId: SAFETY_INCIDENT_MACHINE_ID, aggregateId: snapshot.safetyIncidentId, ...(from ? { fromState: from } : {}), toState: snapshot.state, eventId: stableEventId, fromVersion: expectedVersion, toVersion: snapshot.version, actorUserId: actorId, occurredAt: command.at, commandId: command.commandId, correlationId: command.correlationId }, event: { eventId: stableEventId, aggregateId: snapshot.safetyIncidentId, aggregateVersion: snapshot.version, occurredAt: command.at, correlationId: command.correlationId, idempotencyKey: command.idempotencyKey, payload: { state: snapshot.state, internalInvestigationSlaHours: 48, statutoryDeadlineValidated: false, autoCompleted: false } }, audit: { actionId: stableEventId, aggregateId: snapshot.safetyIncidentId, actor: structuredClone(command.actor), occurredAt: command.at, correlationId: command.correlationId, evidenceIds: [...evidenceIds] } }; }
}

export const SAFETY_P1_EXCLUDED = Object.freeze(["HAZARDOUS_MATERIAL", "MSDS", "WASTE_LOG", "EMERGENCY_DRILL"] as const);
