import type { ApprovalSubject, ApprovalSubjectSnapshot, TypedApprovalSubjectPort } from "@youone/core-approval/public";
import { DocumentVersion, type DocumentMutation, type DocumentVersionSnapshot } from "../domain/document.js";
import type { JsonValue, Sha256, Uuid, Version } from "@youone/shared-kernel/public";
import { DocumentManifestFactory, type DocumentAttachmentManifestItem, type DocumentCommand, type DocumentManifestBuilder } from "../domain/document.js";

type DocumentApprovalSubject = Extract<ApprovalSubject,{kind:"DOCUMENT_VERSION"}>;
export interface DocumentVersionRepository { loadExact(documentVersionId: Uuid): Promise<DocumentVersionSnapshot|null>; save(snapshot: DocumentVersionSnapshot, expectedVersion: Version): Promise<boolean>; appendEvidence(evidence: DocumentMutation["evidence"]): Promise<void>; enqueue(evidence: DocumentMutation["evidence"]): Promise<void> }
export interface DocumentUnitOfWork { transact<T>(work: (repository: DocumentVersionRepository) => Promise<T>): Promise<T> }
export interface DocumentSealRepository extends DocumentVersionRepository { loadForUpdate(id:Uuid):Promise<DocumentVersionSnapshot|null>; listAvailableAttachmentsForUpdate(id:Uuid):Promise<readonly DocumentAttachmentManifestItem[]> }
export interface DocumentSealUnitOfWork { transact<T>(work:(repository:DocumentSealRepository)=>Promise<T>):Promise<T> }
export class DocumentSealService{constructor(private readonly uow:DocumentSealUnitOfWork,private readonly manifestBuilder:DocumentManifestBuilder){}async seal(input:{documentVersionId:Uuid;command:DocumentCommand;rendererId:import("@youone/shared-kernel/public").StableCode;rendererVersion:import("@youone/shared-kernel/public").StableCode}):Promise<DocumentMutation>{return this.uow.transact(async repository=>{const record=await repository.loadForUpdate(input.documentVersionId);if(!record)throw new Error("DOCUMENT_VERSION_NOT_FOUND");const attachments=await repository.listAvailableAttachmentsForUpdate(input.documentVersionId);const manifest=await new DocumentManifestFactory(this.manifestBuilder).create({manifestSchemaId:"DOCUMENT.MANIFEST.V1" as never,manifestSchemaVersion:1,contentChecksum:record.contentChecksum,templateVersionId:record.template?.templateVersionId,templateChecksum:record.template?.checksum,attachments,effectiveSecurityLevel:record.securityLevel,rendererId:input.rendererId,rendererVersion:input.rendererVersion});const mutation=DocumentVersion.restore(record).seal(input.command,manifest);if(!await repository.save(mutation.snapshot,mutation.expectedVersion))throw new Error("DOCUMENT_STALE_VERSION");await repository.appendEvidence(mutation.evidence);await repository.enqueue(mutation.evidence);return mutation;});}}
export interface ApprovalOutcomeCommandFactory { create(input:{approvalInstanceId:Uuid;approvalVersion:Version;documentVersionId:Uuid;outcome:"COMPLETED"|"REJECTED"|"RECALLED"}):DocumentCommand }
export interface EditorSchemaRegistry { validateAndCanonicalize(schemaId:import("@youone/shared-kernel/public").StableCode,schemaVersion:number,data:unknown):Promise<JsonValue|null> }
/** Must call the authoritative PostgreSQL app_private.canonical_json_sha256(jsonb); JS serialization is forbidden. */
export interface CanonicalJsonHasher { hashCanonicalJson(value:JsonValue):Promise<Sha256> }
export class StrictEditorContentCanonicalizer { constructor(private readonly schemas:EditorSchemaRegistry,private readonly hasher:CanonicalJsonHasher,private readonly evidenceId:()=>Uuid){}async validateCanonicalizeAndHash(raw:unknown){if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("DOCUMENT_EDITOR_SHAPE_INVALID");const record=raw as Record<string,unknown>;if(typeof record.schemaId!=="string"||!Number.isInteger(record.schemaVersion)||Number(record.schemaVersion)<1)throw new Error("DOCUMENT_EDITOR_SCHEMA_INVALID");const serialized=JSON.stringify(record.data);if(/<(?:script|iframe|object)|\"(?:rawHtml|html|script)\"\s*:/i.test(serialized))throw new Error("DOCUMENT_EDITOR_UNSAFE_CONTENT");const data=await this.schemas.validateAndCanonicalize(record.schemaId as never,Number(record.schemaVersion),record.data);if(data===null)throw new Error("DOCUMENT_EDITOR_UNKNOWN_OR_INVALID_SCHEMA");return{content:{schemaId:record.schemaId as never,schemaVersion:Number(record.schemaVersion),data},checksum:await this.hasher.hashCanonicalJson(data),validationEvidenceId:this.evidenceId()};}}
export class DocumentApprovalSubjectAdapter implements TypedApprovalSubjectPort<DocumentApprovalSubject> {
  readonly kind = "DOCUMENT_VERSION" as const;
  constructor(private readonly repository: DocumentVersionRepository, private readonly commands:ApprovalOutcomeCommandFactory) {}
  async sealExactVersion(subject: DocumentApprovalSubject): Promise<ApprovalSubjectSnapshot> { const record = await this.required(subject.documentVersionId); if (record.state !== "REVIEW_READY" && record.state !== "APPROVAL_PENDING" || !record.sealedSnapshotChecksum) throw new Error("DOCUMENT_VERSION_NOT_SEALED"); return { subject, subjectVersion: record.versionNo as Version, checksum: record.sealedSnapshotChecksum, sealedAt: record.sealedAt! }; }
  async assertExactVersion(snapshot: ApprovalSubjectSnapshot): Promise<void> { if (snapshot.subject.kind !== this.kind) throw new Error("DOCUMENT_SUBJECT_KIND_MISMATCH"); const record = await this.required(snapshot.subject.documentVersionId); if (record.versionNo !== Number(snapshot.subjectVersion) || record.sealedSnapshotChecksum !== snapshot.checksum || record.sealedAt !== snapshot.sealedAt) throw new Error("DOCUMENT_EXACT_VERSION_MISMATCH"); }
  async assertResubmissionLineage({previous,current}: {previous: ApprovalSubjectSnapshot; current: ApprovalSubjectSnapshot}): Promise<void> { if (previous.subject.kind !== this.kind || current.subject.kind !== this.kind) throw new Error("DOCUMENT_LINEAGE_KIND_MISMATCH"); const old = await this.required(previous.subject.documentVersionId); const next = await this.required(current.subject.documentVersionId); await this.assertExactVersion(previous); await this.assertExactVersion(current); if (old.documentId !== next.documentId || next.versionNo <= old.versionNo || next.priorVersionId !== old.documentVersionId) throw new Error("DOCUMENT_LINEAGE_INVALID"); }
  async applyApprovalOutcome(input: {snapshot: ApprovalSubjectSnapshot; approvalInstanceId: Uuid; approvalVersion: Version; outcome: "COMPLETED"|"REJECTED"|"RECALLED"|"CANCELLED"}): Promise<void> { await this.assertExactVersion(input.snapshot); if (input.snapshot.subject.kind !== this.kind || input.outcome === "CANCELLED") return; const record = await this.required(input.snapshot.subject.documentVersionId);if(record.approvalInstanceId!==input.approvalInstanceId)throw new Error("DOCUMENT_APPROVAL_INSTANCE_MISMATCH"); const aggregate = DocumentVersion.restore(record); const outcome=input.outcome;const mutation = aggregate.applyApprovalOutcome(this.commands.create({approvalInstanceId:input.approvalInstanceId,approvalVersion:input.approvalVersion,documentVersionId:record.documentVersionId,outcome}), outcome === "COMPLETED" ? "APPROVED" : outcome); if (!await this.repository.save(mutation.snapshot, mutation.expectedVersion)) throw new Error("DOCUMENT_STALE_VERSION"); await this.repository.appendEvidence(mutation.evidence); await this.repository.enqueue(mutation.evidence); }
  private async required(id: Uuid): Promise<DocumentVersionSnapshot> { const found = await this.repository.loadExact(id); if (!found) throw new Error("DOCUMENT_VERSION_NOT_FOUND"); return found; }
}
export interface DocumentInboxItem { readonly documentVersionId: Uuid; readonly documentNo: string; readonly versionNo: number; readonly state: DocumentVersionSnapshot["state"]; readonly securityLevel: DocumentVersionSnapshot["securityLevel"] }
export type DocumentQueryResult<T> = {readonly availability:"AVAILABLE";readonly value:T}|{readonly availability:"UNAVAILABLE";readonly value:null;readonly reason:"QUERY_ADAPTER_NOT_CONFIGURED"};
export interface DocumentQueryPort { listMine(): Promise<DocumentQueryResult<readonly DocumentInboxItem[]>>; getMine(id: Uuid): Promise<DocumentQueryResult<DocumentVersionSnapshot>> }
